### ISSUE TITLE
Just wanted to say I love deadbeef. Thanks for creating a non-cluttered player. 2 small issues tho :)

### ISSUE THREAD

**Issue by cocoonkid** [DeaDBeeF-Player/deadbeef#2605] opened 2021-05-20 13:50 UTC
1.

## Steps to reproduce the problem

Import  folder of tracks.

### What's going on? Describe the problem in as much detail as possible.

Have to wait until import finished before I can start playing.

2.
## Steps to reproduce the problem

Enable Pulseaudio Plugin.

### What's going on? Describe the problem in as much detail as possible.

Everything works but deadbeef is not listed in pulseaudio plugin xfce players so it doesn't show up.

### Information about the software:

Deadbeef version: 1.8.4
OS: Arch Linux

**Comment by Alexey-Yakovenko** [comment] 2021-05-20 15:50
Hello, and thanks for the kind words :)
The issue with importing is a duplicate of #690
The issue about pulseaudio -- I'm not sure.. But I suggest to try the modernized pulseaudio plugin from here: https://github.com/saivert/ddb_output_pulse2 (also available on the plugins page, but I'm not sure if it's up to date).
If the problem is not solved, please report as a separate issue.

**Closed by Alexey-Yakovenko** 2021-05-20 15:50 UTC
