### ISSUE TITLE
 Feature request: "Open containing folder" menu option on right mouse click

### ISSUE THREAD

**Issue by predokxiii** [DeaDBeeF-Player/deadbeef#1957] opened 2018-01-06 21:44 UTC
Right mouse click on file in playlist > select "Open containing folder" menu option to open folder where this file from. Very useful option.

**Comment by Alexey-Yakovenko** [comment] 2018-01-06 22:01
Duplicate of #1526

**Closed by Alexey-Yakovenko** 2018-01-06 22:01 UTC
Labels: duplicate
