### ISSUE TITLE
bug: loud noise when switching between different sample rate.(ALSA usb dac direct output) 

### ISSUE THREAD

**Issue by kennychenfs** [DeaDBeeF-Player/deadbeef#2933] opened 2023-03-26 16:02 UTC
### Steps to reproduce the problem

1. Connect a USB DAC
2. Select ALSA output/Direct hardware device without any conversions as the output method.
3. Play a music track with a sample rate of, for example, 44.1kHz
4. Switch to another track with a different sample rate, e.g. 96kHz

### What's going on? Describe the problem in as much detail as possible.

When switching to a track with a different sample rate, there is a loud noise coming from the USB DAC. This noise is of high intensity and could potentially damage your hearing. Restarting the track will resolve the problem. This problem has persisted for some time.

### Software information:

Deadbeef version: 1.9.5
OS: Ubuntu 22.04.2

### Suggestions for improvement:

To mitigate this problem, I recommend pausing for a very short time between tracks to allow the USB DAC to adjust to the new sample rate. This may prevent the loud noise from occurring and potentially causing damage.

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-26 18:20
There's a variable that you can add to the config file: `streamer.format_change_silence X` where X is the number of seconds. You can specify fractional number to get a value smaller values than 1 seconds - e.g. 0.1 and so on.
Could you give it a try and see if it helps? I'm pretty sure that this issue was already reported in the past, but I can't remember whether adding such pausing will help anything.

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-26 18:22
The variable needs to be added to the file `~/.config/deadbeef/config`, and when adding it -- the player must not be running, otherwise the variable will not be used and will get overwritten.

**Comment by kennychenfs** [comment] 2023-03-27 00:14
Thanks, I'll try it later.
By the way, I searched for past issues but couldn't find any related to this one.

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-27 06:29
True, I can't find it either. Maybe that other issue was reported by email or discord

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-27 10:44
Noise playback is not an indicator of wrong samplerate.
Wrong samplerate is indicated by wrong playback speed.

**Comment by kennychenfs** [comment] 2023-04-20 16:03
I found that this problem only happens on certain DACs. My new DAC doesn't have this problem without doing any fixes.

**Comment by Oleksiy-Yakovenko** [comment] 2023-05-05 10:31
Closing since there's not enough information or technical possibility to act on this issue.

**Closed by Oleksiy-Yakovenko** 2023-05-05 10:31 UTC

**Comment by mitanshu7** [comment] 2024-06-15 10:02
Hello, 

Apologies for reviving an old thread @kennyfs @Oleksiy-Yakovenko.

I have the exact same issue, and I am using Shanling UA2. In case any of you have a solution regarding this, please let me know!

Thanks.

**Comment by Oleksiy-Yakovenko** [comment] 2024-06-15 10:04
@mitanshu7 unfortunately this problem is nearly impossible to fix without being able to reproduce it. I tried to apply some potential solutions back in the day, and nothing helped.

**Comment by mitanshu7** [comment] 2024-06-15 10:09
@Oleksiy-Yakovenko, Thank you very much for your quick reply. 

I see. 

I remember adding supported sampling rates by the card to some config file, however when i issue `cat /proc/asound/card2/stream0` I see all the rates being mentioned there. 

Anyway, thanks a lot for your time!
