### ISSUE TITLE
Feature request: Checkboxes to enable/disable plugins

### ISSUE THREAD

**Issue by ao-il** [DeaDBeeF-Player/deadbeef#1860] opened 2017-08-18 22:39 UTC
Provide checkboxes so that users can enable/disable unused plugins.

**Comment by Bfgeshka** [comment] 2017-08-18 23:32
Now deadbeef enables all modules it can find. It could be really handy to enable/disable them in runtime, I miss this feature when it is needed eventually.

**Comment by Alexey-Yakovenko** [comment] 2017-08-19 08:26
What is the expected functionality of the checkbox? What exactly should be a consequence of disabling a plugin?

**Comment by ao-il** [comment] 2017-08-19 11:36
Checked state should load plugin and unchecked should unload (when not in use). System plugins are enabled by default.

**Comment by Alexey-Yakovenko** [comment] 2017-08-19 11:58
Unloaded - as in .so is skipped during init?

In this case, disabled plugins won't ever appear in the list, and you won't be able to re-enable them.

**Comment by ao-il** [comment] 2017-08-19 12:10
Disabled plugins should not be loaded on init but should be visible on gui to allow user to re-enable them. You should have "pointers" to the plugins that are disabled so they can be enabled at runtime.

**Comment by Alexey-Yakovenko** [comment] 2017-08-19 12:11
That's exactly the problem -- only loaded plugins are visible in the list. There's no way to create this list without loading the plugins.

**Comment by ao-il** [comment] 2017-08-19 18:47
Can you not scan the plugin directory for the list? Or manage a db for the plugins? A good design pattern would be to have a plugin manager that takes care of the plugins (install/remove, enable/disable). Another approach is to assign a dummy load callback for plugins that are disabled and then reset when they are re-enabled.

**Comment by Alexey-Yakovenko** [comment] 2017-08-19 20:23
It's not as simple as it looks.

On mac and android, the plugins directory may contain other DLLs which are not plugins. This allows to share more code across plugins, and better comply with the licenses. A simple directory scan would mis-detect these DLLs as plugins. And this will soon come to Linux version too, when I solve some build and runtime issues.

Then, another problem is that without **loading** the plugin DLL, it's not possible to get the plugin name, description, etc. Only a filename. This is not user friendly.

And last but not least, disabling plugins would not work immediately -- you'd still need to restart the whole player for changes to take effect. We can't just drop the code from RAM while it's being executed.

Some of this can be solved, some can't.

Implementing a half-working feature is not worth it, so unless we can up to solutions to all of the things -- it's not going to happen.

**Comment by ao-il** [comment] 2017-08-19 21:20
Ok, I see. Would having a naming pattern for plugins help to solve the issue of misdetecting plugins? Is it possible to save plugin information to a properties file? And then use this to provide info for gui? It could also benefit the user to be able to disable load for certain plugins via a config file. This could work as a temporary solution. For me, I think It's normal to restart player for changes to take effect.

**Comment by Alexey-Yakovenko** [comment] 2017-08-19 23:05
We can't really change existing published plugins -- I mean, people already have them installed, and some dont't get updated for years, and I don't want to add more complexity for the devs via additional properties files.

**Comment by ao-il** [comment] 2017-08-20 10:25
Ok, but before this feature is available, how can I prevent a plugin from being loaded? Can I just simply hide (.plugin.so) the .so file or must I remove it from the directory? I feel there's no use having plugins in RAM to take up unnecessary space.

**Comment by Alexey-Yakovenko** [comment] 2017-08-20 11:03
you can either remove unnecessary plugins, or rename it to any other name -- they won't work if the .so name is different from the plugin entry point name.

**Comment by ao-il** [comment] 2017-08-21 20:07
I got a lot of loading errors after renaming, does it mean that db still attempts to load renamed plugins? First, I did `rename 's/^/--/' *.so` and then renamed/enabled the important ones.

**Comment by Alexey-Yakovenko** [comment] 2017-08-21 20:13
Yes, it doesn't know which .so are plugins and which are not, so it loads each .so, and tries to find an entry point with the same name in it (`${name_without_so_extension}_load` function). If the function is found -- it's a valid plugin, and it's loaded.

**Comment by ao-il** [comment] 2017-08-21 20:20
Ok, since it looks for .so I'll just add -- to the end.

**Comment by ao-il** [comment] 2017-08-21 20:31
Ok, that was a bad rename, it was being interpreted as an option (--acc.so : unknown option). I'll just move them instead.

**Comment by dafanasiev** [comment] 2017-10-01 11:31
You can also enumerate plugins filenames (without `.so` at the end) in `blacklist_plugins` setting variable (edit `~/.config/deadbeef/config` file) and deadbeef skip to load this DLL.
See: `plugins.c` `load_plugin_dir` function.

**Comment by ao-il** [comment] 2017-10-01 18:57
Aha.. Did not know that earlier. I have just moved the plugins to another directory. Thanks.

**Comment by Alexey-Yakovenko** [comment] 2021-07-19 16:50
duplicate of #620

**Closed by Alexey-Yakovenko** 2021-07-19 16:50 UTC
Labels: Enhancement
