### ISSUE TITLE
Global shortcuts with media keys become disabled after wake up

### ISSUE THREAD

**Issue by vmarkovtsev** [DeaDBeeF-Player/deadbeef#2469] opened 2020-10-22 11:31 UTC
### Steps to reproduce the problem

- Specify any global scope shortcut using a media key of your laptop, e.g. to play/pause.
- It works.
- Put your laptop to sleep.
- Wake it from sleep.
- That shortcut no longer works.

### What's going on? Describe the problem in as much detail as possible.

When I restart the player, the shortcuts work again.
If I set a global shortcut to a non-media key, e.g. "Alt-P", it continues to work after waking up.

This is my example:

![image](https://user-images.githubusercontent.com/2793551/96865384-2ed91680-146a-11eb-9a13-c2b33e0d9191.png)

![image](https://user-images.githubusercontent.com/2793551/96865873-ca6a8700-146a-11eb-9224-1470ea905fa7.png)

I see these in my syslog after waking up and attempting to press a media key:

```
Oct 22 13:19:32 vadim-XPS-13-9380 gsd-media-keys[3832]: Error calling method Timeout was reached
Oct 22 13:19:33 vadim-XPS-13-9380 gsd-media-keys[3832]: Error calling method Timeout was reached
```

### Information about the software:

Deadbeef version: 1.8.4
OS: Ubuntu 20.04

Hardware: Dell XPS 13 9380.

**Comment by Alexey-Yakovenko** [comment] 2020-10-22 12:10
Duplicate of #2428

**Closed by Alexey-Yakovenko** 2020-10-22 12:10 UTC
Labels: Duplicate
