### ISSUE TITLE
SuperEQ distorts 24 bit output on raspbian armv7l

### ISSUE THREAD

**Issue by eshchenko** [DeaDBeeF-Player/deadbeef#1986] opened 2018-03-12 22:29 UTC
### Steps to reproduce the problem
The problem was investigated in configuration described in #1978

Connect external 24bit usb card to Raspberry Pi2 with fresh Raspbian installed
Compile stable DeaDBeeF 0.7.2 from source.
Use the external usb card in most direct way:
ALSA output plugin
Output device: Dr DAC Direct Hardware Device without any conversions
ALSA resampling is not enabled.

Take a 24bit file, be sure that it can be played correctly by the aplay:
pi@raspberrypi:~/development/bin $ aplay -D hw:CARD=prime,DEV=0 tmp.wav
Playing WAVE 'tmp.wav' : Signed 24 bit Little Endian in 3bytes, Rate 48000 Hz, Stereo

Start to play this 24bit pcm (*.wav) file by the deadbeef player.
Be sure the internal volume is set to the very right position +0 dB.
 
### What's going on? Describe the problem in as much detail as possible.
Open SiperEQ window.
Enable  equalizer. This will result to huge sound distortions
Disable equalizer. Distortions will disappear.

Play any 16bit file - No distortions.

### Information about the software:

Deadbeef version: 
0.7.2 stable
OS:
Paspberri Pi 2B
Raspbian GNU/Linux 8 (jessie)
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**I had also tried the last development version.
In this case the EQ does not work neither with 16bit nor with 24bit files**
The signal is not changed independent on the enabling/disabling the EQ. 

### Additional information:
For the crosscheck I compiled the development version of the deadbeef on 
Linux HP-EliteBook-8530p 4.4.0-040400-generic #201601101930 SMP Mon Jan 11 00:32:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
and reconnected the 24bit usb card to this Intel PC.

**On Intel the SuperEQ works as expected** and without distortions both with internal 32bit card and external 24bit card
(when playing 24bit file on internal card there is warning -  
cannot set sample format to 24 bps (error: Invalid argument), trying all supported formats
Found compatible format 32 bps) 
When playing 24bit file with 24bit card there are no warnings.

**Comment by Alexey-Yakovenko** [comment] 2018-03-13 10:08
deadbeef 0.7 series are not going to receive updates I'm afraid. I thought that the issue was that EQ is not working at all on trunk. Is that still the case?

**Comment by Alexey-Yakovenko** [comment] 2018-03-13 10:13
So.. there was a regression that was causing this exact issue, that supereq didn't work at all. It was fixed in commit d2fc9efdccab1e0317e1561f0689674f193dfe67. Can you please verify that your build is up to date? It sounds like you might be a few commits behind.

**Comment by Alexey-Yakovenko** [comment] 2018-03-14 09:39
I don't have access to ARM hardware to test this on, but I made what looks like a fix. Please let me know if the latest version works.

**Closed by Alexey-Yakovenko** 2018-03-14 09:39 UTC

**Comment by eshchenko** [comment] 2018-03-14 11:28
I did
make clean
git pull
./configure --prefix=/home/pi/development/ --disable-gtk3
 make -j4

Finally I got an error:

make[2]: Entering directory '/home/pi/development/deadbeef'
  CC       plmeta.o
  CC       pltmeta.o
  CC       dsp.o
  CC       streamreader.o
  CC       premix.o
  CC       messagepump.o
premix.c: In function ‘pcm_write_samples_float_to_24’:
premix.c:427:17: error: ‘ousample’ undeclared (first use in this function)
             if (ousample >= 0x7fffff) {
                 ^
premix.c:427:17: note: each undeclared identifier is reported only once for
each function it appears in
  CC       conf.o
Makefile:774: recipe for target 'premix.o' failed
make[2]: *** [premix.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/pi/development/deadbeef'
Makefile:876: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/development/deadbeef'
Makefile:617: recipe for target 'all' failed
make: *** [all] Error 2


On Wed, Mar 14, 2018 at 10:39 AM, Alexey Yakovenko <notifications@github.com

**Comment by Alexey-Yakovenko** [comment] 2018-03-14 12:15
Sorry, I accidentally deleted a character from the variable name. Please try again.

**Comment by eshchenko** [comment] 2018-03-14 21:15
Dear Alexey

Thanks a lot!
Now EQ works with 24 bit without distortions!
I think you can add the Raspberry to the list of the supported platforms...
As you do not have the hardwire - you are more than welcome to contact me
if you need to check something on Raspberry...

Best, Dmitry

**Comment by Alexey-Yakovenko** [comment] 2018-03-14 22:05
There's no official list of supported platforms as such..
And while it's supposed to work, claiming it's "supported" would not be true, since there's no dedicated maintainer for supporting it.

Thanks for reporting and verifying the issue!
