### ISSUE TITLE
Tracks with distinct embedded artworks in an album only showing one artwork

### ISSUE THREAD

**Issue by TheTerrior** [DeaDBeeF-Player/deadbeef#2505] opened 2021-01-19 00:44 UTC
### Steps to reproduce the problem
Have many different tracks as part of one album,where each track has a distinct artwork.

### What's going on? Describe the problem in as much detail as possible.
When I play a track out of the album, its embedded artwork gets saved into deadbeef's cache with the album's name. Once I play another song from the album, deadbeef grabs the first song's artwork from cache and displays that instead of the embedded artwork inside the current song. If I delete the artwork from cache, it will save the current track's artwork instead, but continue the issue once I play yet another song from that album.

### Information about the software:

Deadbeef version: 1.8.5
OS: Linux Mint 20

**Comment by Alexey-Yakovenko** [comment] 2021-01-19 20:00
This is a known issue, but is hard to fix with the linux artwork plugin, since it's caching mechanism is based on the album name.

This issue will be resolved when GTKUI is upgraded to the new artwork plugin, that's still under development.

**Comment by ryran** [comment] 2022-01-06 11:18
Dupe of #1118 ?

**Comment by Alexey-Yakovenko** [comment] 2022-01-06 13:46
duplicate of #1118

**Closed** 2022-02-04 22:46 UTC
Labels: Duplicate, Enhancement

**Comment by Alexey-Yakovenko** [comment] 2022-02-04 22:48
Can anyone try deadbeef 1.9.0-beta3 and verify whether this is fixed?
