### ISSUE TITLE
Save playlists on exit

### ISSUE THREAD

**Issue by kpcee** [DeaDBeeF-Player/deadbeef#2257] opened 2019-11-03 19:16 UTC
I'm just experimenting a bit and I noticed that DeaDBeeF saves the configuration and the playlists with every small change. However, it doesn't save the playlists when it quits. I would suggest to change this behavior and save only or mainly only when the program ends (this is aleady done in the tag editor). DeaDBeeF runs so smoothly that program crashes never happen. But it would have other advantages:

* Saving large playlists (my largest one is 23 MB) might interrupt playback (for example removing a track from playlist or drag and drop a single track within the playlist)
* You could solve the problem "// FIXME: the tracks in the list might be from other playlist(s)" and avoid data loss
* There are places where saving is incomplete e.g. in the Replaygain scanner
* The Plug-Ins don't have to save the playlists everywhere anymore
* The playlists would always be up to date and all the single calls to save the lists could be removed

If there is interest I could have a look.

**Comment by Alexey-Yakovenko** [comment] 2019-11-03 19:45
The main reason it's done this way is because Linux lacks a standard and/or fully working and cross-DE compatible session management mechanism. And most likely never will, because it's too easy for a user to disable one if it existed, or to not even install one in the first place.

When you shutdown your X session, your app will receive SIGTERM, and then GTK will kill the app before you know it.

Catching SIGTERM and saving your stuff won't work either, because GTK will kill the app with an `exit` call way faster than saving would complete, in which case you would get corrupt files.

However now that we run GTK stuff on the main thread, maybe this problem could be solved. But I doubt it.

Anyway, this was discussed in detail more than once. I would suggest reading the case #1014 about that, although it's partly in Russian and you would have to use google translate I suppose.

Regarding your points.. considering all things known, I believe they should be considered bugs, and fixed with the constraints of the situation.

And last but not least, deadbeef actually does save all playlists when it quits.

**Comment by Alexey-Yakovenko** [comment] 2019-11-03 19:45
closed as duplicate of #1014 014

**Closed by Alexey-Yakovenko** 2019-11-03 19:45 UTC

**Comment by kpcee** [comment] 2019-11-04 08:24
Oh I didn't find this discussion, yes it could a problem for people who don't close the applications manually. I will read it later.

However, I disagree that deadbeef automatically saves the playlists on exit. I've just tried the 1.82 again and it doesn't. Start deadbeef, delete the playlists and quit it again. Every now and then a playlist is saved but in most cases nothing happens - try it with more as one playlist.

**Comment by Alexey-Yakovenko** [comment] 2019-11-04 08:44
It's an unconditional call to pl_save_all in main_cleanup_and_quit, so it should happen.
Can you try to find an example repro when a playlist would not save?

**Comment by kpcee** [comment] 2019-11-04 16:42
I have now done the following, version 1.82 started with empty profile. On startup a new playlist is created, I add two more. Now I have three files (0.dbpl, 1.dbpl, 2.dbpl).

- Next I delete the three files and quit Deadbeef.
- Now we have the three files again, they were saved by Deadbeef on exit. All okay!
- We start deadbeef again, delete the three files and quit again.
Now you can see that the three files are no longer saved, the directory remains empty no matter how often you start and quit deadbeef. This also happens with filled playlists.
Is this reproducible?

**Comment by Alexey-Yakovenko** [comment] 2019-11-04 16:45
It's supposed to be this way. Playlist are not rewritten unless changed within the player.
There's a check for that: https://github.com/DeaDBeeF-Player/deadbeef/blob/a16b5edd4667d7d6d76f03734414f98302fcfc9b/playlist.c#L1995

**Comment by Alexey-Yakovenko** [comment] 2019-11-04 16:47
The main point of this optimization is to avoid unnecessary writes, both for performance reasons, and because it's not nice for SSDs write cycle spending.

**Comment by kpcee** [comment] 2019-11-04 17:44
Okay, but it's flawed, tested with 1.82:
Create a playlist with tracks, exit deadbeef once and restart, then delete the playlist

* select track, perform ReplayGain, exit deadbeef -> no playlist written
* select track, open tag editor, edit a tag, click apply, exit deadbeef -> success, playlist written
* select track, open tag editor, edit a tag, click close, click on No in the dialog, click apply now and quit deadbeef -> no playlist written

**Comment by Alexey-Yakovenko** [comment] 2019-11-04 17:46
This is a bug. ReplayGain probably doesn't call plt_save or plt_modified after scanning.
I'll check.

**Comment by Alexey-Yakovenko** [comment] 2019-11-04 18:24
The fix is not perfect, but better than nothing.
It assumes that rgScan/rgRemove will complete, so saving would occur even if operation was cancelled.

It would still not handle cases, when a single track is reused in multiple playlists - this is no supported in general with the current codebase though, but something that will occur in the future.

**Comment by Alexey-Yakovenko** [comment] 2019-11-04 18:34
So, this report has helped to spot and fix multiple bugs, but this one is still present.
It would be great if you create an issue for it.

> Saving large playlists (my largest one is 23 MB) might interrupt playback (for example removing a track from playlist or drag and drop a single track within the playlist)
