### ISSUE TITLE
SACD ISO playback support

### ISSUE THREAD

**Issue by ArminiusTux** [DeaDBeeF-Player/deadbeef#2059] opened 2018-10-27 22:30 UTC
Since DeaDBeeF can handle any types of DSD [uncompressed, DST & Wavpack-DSD], it would be nice seeing SACD ISOs completing the chain and being accepted as well [drag&drop].

Useful code can be borrowed from e.g. [sacd-ripper](https://github.com/setmind/sacd-ripper) & [vfs.sacd](https://github.com/xbmc/vfs.sacd)

Deadbeef version: 1.8.x
OS: Linux [x86_64 & armhf], macOS

**Comment by Alexey-Yakovenko** [comment] 2018-10-27 23:07
duplicate of #683

**Closed by Alexey-Yakovenko** 2018-10-27 23:07 UTC
Labels: duplicate
