### ISSUE TITLE
MP3 file durations not correct causing playback to end prematurely

### ISSUE THREAD

**Issue by yoyoma2** [DeaDBeeF-Player/deadbeef#2390] opened 2020-05-21 05:48 UTC
### Steps to reproduce the problem
1) Add a constant bitrate [mp3 file](https://github.com/DeaDBeeF-Player/deadbeef/files/4660669/sample01.zip) with different frame sizes to the playlist
2) Observe the deadbeef duration is shorter than what videolan, audacious, mp3info think it is
3) Play the end of the file in multiple players
4) deadbeef cuts off before the end of the file while others play the whole thing

### What's going on? Describe the problem in as much detail as possible.
Deadbeef scans 200 frames and extrapolates to make an educated guess of the duration of the file. If the guess is wrong, and on a longer file this error becomes significant, deadbeef sticks with the error until the end which in this case truncates the end of the playback.
### Information about the software:

Deadbeef version: 1.8.2-1
OS: ubuntu 18.04 LTS

A build of a git clone of the latest code has the same problem.

### Workaround
This [patch](https://github.com/DeaDBeeF-Player/deadbeef/files/4660715/mp3.patch.zip) works around the problem by conditionally turning on MP3_PARSE_FULLSCAN which may be slower but gets the length right and plays the entire file. Example usage to turn on MP3_PARSE_FULLSCAN:

DEADBEEF_MP3_PARSE_FULLSCAN= /opt/deadbeef/bin/deadbeef

Only the mp3_parse_file() calls that affected my use case were patched. This is not a "ready to merge" patch. Anyone having problems with mp3 file durations can try this workaround until a bug fix is merged.

**Comment by Alexey-Yakovenko** [comment] 2020-05-21 08:31
duplicate of #2309 
already fixed in 1.8.3

**Comment by yoyoma2** [comment] 2020-05-21 12:34
As stated in the original bug report this bug is in the latest DeaDBeeF-devel latest code that was just built. Did you try the given in step 1?

> A build of a git clone of the latest code has the same problem.

**Comment by Alexey-Yakovenko** [comment] 2020-05-21 20:40
My bad. It's a slightly different issue. Reopened.
I'm intending to add a better duration calculation, but to make it work fast enough, a lot of work is needed, so please don't expect it to be done soon.

**Comment by yoyoma2** [comment] 2020-05-21 23:36
No problem if it takes a long time as the workaround is OK for now. Congratulations on a terrific audio player BTW.

**Comment by Alexey-Yakovenko** [comment] 2020-05-22 09:56
Handling of the specific situation, like in the provided sample file, has been fixed.

**Closed** 2020-05-22 09:55 UTC
Labels: Triage

**Comment by yoyoma2** [comment] 2020-05-22 16:47
Pulled the latest, stopped using the fullscan workaround and everything works!

I think there is a copy/paste error in line 567 that should be _prev_length_ instead of _prev_br_ or the _variable_packets_ flag will get set unnecessarily often.

`prev_br != packet.packetlength`

**Comment by Alexey-Yakovenko** [comment] 2020-05-22 18:57
Thank you for noticing and pointing this out, I should have been more careful.

**Comment by yoyoma2** [comment] 2020-05-23 00:28
Pulled the latest and it works great. Thanks for the quick fix!
