### ISSUE TITLE
[QUESTION] - Any Update Infobar Plugin?

### ISSUE THREAD

**Issue by 0pLuS0** [DeaDBeeF-Player/deadbeef#2427] opened 2020-08-07 00:41 UTC
The Infobar devleopment stopped close to 7 years ago, since then I have not seen anything else.

https://bitbucket.org/dsimbiriatin/deadbeef-infobar/wiki/Home

So I wanted to ask this question here, does anyone know of any updated plugin for this to work with the latest deadbeef?

I posted an issue in regards to this not working;

https://github.com/DeaDBeeF-Player/deadbeef/issues/2112

Going back last year, there was talk about an updated version coming around, but that doesn't seem to be happening, there's been no word on this.

If anyone knows anything, it would be greatly appreciated, because this is the only thing holding me back from updating deadbeef.

I still have to use 0.7.2 :face_with_head_bandage:

**Comment by Alexey-Yakovenko** [comment] 2020-08-07 06:08
It doesn't appear like there are any updates adding to #2112 conversation.

**Comment by Alexey-Yakovenko** [comment] 2020-08-07 06:09
duplicate of #2112

**Closed by Alexey-Yakovenko** 2020-08-07 06:08 UTC

**Comment by Alexey-Yakovenko** [comment] 2020-08-07 06:13
Actually, there's a slightly related news, which, in the long run, might help the people who need to browse music folders in deadbeef UI.

I'm working on media library implementation, which also has folder mode.

Looks like this. It's very far from finished, and right now is only developed for macOS, but hopefully it will be ported to linux as well.

![image](https://user-images.githubusercontent.com/1895698/89614972-d2f8eb80-d885-11ea-88a8-a1e0d70f2a62.png)

**Comment by 0pLuS0** [comment] 2020-08-09 01:48
@Alexey-Yakovenko 

That looks really nice, but I really want/need my Infobar... 

This is how I've always played the Deadbeef UI, since you started this project.

![deadbeef_bio](https://user-images.githubusercontent.com/36190223/89723174-5891ae00-d9e2-11ea-89e8-465bec4435fb.png)


![deadbeef_lyrics](https://user-images.githubusercontent.com/36190223/89723177-5deef880-d9e2-11ea-8220-7ee375fe3327.png)

**Comment by Alexey-Yakovenko** [comment] 2020-08-09 11:22
I'm sorry for your troubles, but there's not much I can do to help you even if I wanted, at least at the moment.
Currently my computer can't run virtualbox, since I'm using macOS Big Sur Beta.. and GTK doesn't run on it natively either.

Also, sorry for confusing the InfoBar plugin with another (also broken) plugin called FileBrowser.

**Comment by 0pLuS0** [comment] 2020-08-09 21:40
No worries, it's just hard having this in the past, and then nothing for it now.

There's really nothing like it, that will work with the latest deadbeef?

I'm really surprised people haven't gotten onboard with deadbeef keeping plugins developed... sad...

**Comment by Alexey-Yakovenko** [comment] 2020-08-10 06:10
I haven't heard of one even if it exists..
And .. it's understandable that people move on with their lives and projects.
Most likely, the original dev of the plugin have stopped using deadbeef ~5 years ago.

**Comment by 0pLuS0** [comment] 2020-08-11 23:03
I mentioned in the other post, you really need to have ```In House``` plugin developers working along side you on this project, this would really boost deadbeef popularity in the world of Linux.

But for now, having it the 3rd party way, it's just killing the flexibility of having this support, that is constantly lacking, like in situations like this...
