### ISSUE TITLE
Feature requests | rescan folder

### ISSUE THREAD

**Issue by x09** [DeaDBeeF-Player/deadbeef#2097] opened 2019-03-15 08:02 UTC
i have a folder with my mp3 - for example - /var/mp3/
My playlist include all folders and subfolder from /var/mp3/
If i add new album to the /var/mp3/ i need remove playlist and create new. And wait too long time.
Why deadbeef dont append new files to playlist, as clementine player for example ? 
Or add "rescan folder" feature.

Deadbeef version: 0.7.1
OS: AltLinux

**Comment by Bfgeshka** [comment] 2019-03-15 08:49
Automated playlist renewal is a bad idea for how deadbeef playlists are designed. More, often such action may not be desirable for various reasons:
* You may specifically not want to include all files from the path into the playlist.
* Listed files are no more, but you want to save playlist as-is.
* Slow access to storage is making file monitoring costly.
* You playlist is huge.

But what does make sense, in my opinion, is ability to manually call for such renewal. Though, it may require to have some manipulations for desirable effect (blacklisting paths, saving removed but not deleted elements, recursive update from arbitrary path and so on, there are plenty). All in all, it sounds like a solid plugin-sized chunk of functions.

And keep in mind that clementine has no standarts, allowing all sorts on nyan-cats and whistles into the release, which it suffers from on the perfomance side, while being functionaly probably even weaker than deadbeef.

**Comment by Alexey-Yakovenko** [comment] 2019-03-15 10:09
Duplicate of #654

**Closed by Alexey-Yakovenko** 2019-03-15 10:09 UTC
Labels: duplicate
