### ISSUE TITLE
mp3-seek is extremely slow on very large files / linux

### ISSUE THREAD

**Issue by unclebrr** [DeaDBeeF-Player/deadbeef#2266] opened 2019-11-10 13:33 UTC
### Steps to reproduce the problem
Start deadbeef and load/play huge mp3-file (200-500Mb, 40-90 minutes). Point to the end of the file and click.
### What's going on? Describe the problem in as much detail as possible.
It takes aprx. 20 seconds for deadbeef to start playing.
### Information about the software:

Deadbeef version: 1.8.3  (0407215)  dev.ver.
OS: linux leap 15.1 (opensuse stable) x86_64, ext4
Hardware: Intel(R) Core(TM)2 Quad CPU Q6600  @ 2.40GHz, 16Gb, Samsung SSD 850

**Comment by rthg** [comment] 2019-11-24 18:32
Have same issue after changing drive. Was fast before with same mp3 files.

**Comment by unclebrr** [comment] 2019-11-30 10:53
The fact is that there is no such problem in 0.7.2! This just appeared to happen in 1.8.2 version. Maybe we shall take a one more look at what has been changed between these two?

**Comment by Alexey-Yakovenko** [comment] 2019-11-30 14:50
It will not be very helpful, for a number of reasons:

* deadbeef 1.8 got an entirely new mp3 parser / backend, so looking at the diff won't be helpful
* it's quite obvious, that the slow performance you're experiencing is caused by the removal of inaccurate seeking option, which you probably used in 0.7.2. Which itself had a number of problems, which are now resolved.
* All this means that it's not feasible to fix this problem by simply restoring the old code. It would have to be fixed in a different way -- caching, seek table, whatever. It's not going to be quick.

**Comment by Alexey-Yakovenko** [comment] 2019-11-30 15:03
Also, I believe you can use a super simple workaround: try using the mp3 plugin from deadbeef 0.7.2 in deadbeef 1.8.2. It's supposed to work. It will probably have some other old issues, but if they don't bother you -- it should be fine.

**Comment by unclebrr** [comment] 2019-12-04 20:40
Hmmm... that's an idea! Thank you! ;)

**Comment by unclebrr** [comment] 2019-12-06 09:27
We are talking about mp3.so right?
The one from 0.7.2 works much faster. The seek on the same files is less than 1 (one) second!

**Comment by JakeSFR** [comment] 2019-12-31 12:47
I noticed that seeking in MP3 files that have this field in Properties:
`<CODEC_PROFILE> MP3 VBR`
but at the same time **don't** have this field:
`<MP3_VBR_METHOD> ...`
is indeed noticeably slower in comparison to 0.7.2.
Maybe that was also your case @unclebrr?

**Comment by unclebrr** [comment] 2020-01-05 20:42
Quite possible, but I've solved this problem by using old version of mp3 plugin already ;)

**Comment by Alexey-Yakovenko** [comment] 2020-04-12 19:55
From re-reading the conversation, it seems that only some specific files cause the issue. Can someone share such file for investigation? Please use email if you do so.

**Closed** 2020-04-13 10:52 UTC
Labels: Bug

**Comment by unclebrr** [comment] 2020-04-13 15:01
@Alexey-Yakovenko How do you see sending a half-gig file my email? ;)
Using mp3.so from 0.7.2 with no problems since.
I'w also glad to see deadbeef appearing at packman repository.
Thank you!
P.S. You can do such file by yourself, just use ffmpeg or bladeenc at 256k.

**Comment by Alexey-Yakovenko** [comment] 2020-04-13 15:22
@unclebrr no worries, the problem is already resolved, case closed.

also, deadbeef has been in arch community repo for ~10 years, but I have nothing to do with it, so you don't need to thank me.

**Comment by unclebrr** [comment] 2020-04-14 07:37
Not Arch - SUSE. Just arrived there ;)

**Comment by Alexey-Yakovenko** [comment] 2020-04-14 07:56
either way, I'm not affiliated with packagers in anyway.
