### ISSUE TITLE
It doesn't jump to the next song when the song ends if I double click a random song.

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2306] opened 2020-01-10 15:14 UTC
### Steps to reproduce the problem
Mode: Shuffle -> Album
Resume previous session = yes

1. Play the music which is chosen manually.
2. Jump to the next song.
### What's going on? Describe the problem in as much detail as possible.
It jumps to a different album when the music ends or I manually jumps to the next song.
I need to switch from Shuffle->Album to Shuffle->Track then switch back to make it work again.
### Information about the software:

Deadbeef version: r8770.fe514eeb3-1
OS: Manjaro

**Comment by laichiaheng** [comment] 2020-01-13 11:36
@Alexey-Yakovenko Big trouble for shuffle album mode.

**Comment by Alexey-Yakovenko** [comment] 2020-01-27 15:09
duplicate of #2308

**Comment by Alexey-Yakovenko** [comment] 2020-02-02 15:07
Repro steps:

when I have "Shuffle" set to "Album" and 4 albums added to playlist:

1. After double-clicking the first track of the first album and then click "Next", DB usually jumps to the first track of some other, random album.
1. Only sometimes it jumps to the next track of the same album.
1. Clicking "Next" again and again plays subequent tracks of that album until it ends.
1. But if I manually double-click any track (even the one that is currently playing), then clicking "Next" jumps to a different album again.

**Closed** 2020-02-02 19:57 UTC
Labels: Triage
