### ISSUE TITLE
192KHz streams stuttering with PulseAudio

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1897] opened 2017-09-27 16:31 UTC
It doesn't happen to the ALSA output, but it is stuttering with the PulseAudio output
If I set the resampler output format to 44100, the problem is gone, but I want it to output 192khz, DeaDBeeF is only available for 44.1khz now!!

I saw an update which was released a day ago (https://github.com/DeaDBeeF-Player/deadbeef/commit/1f8f7f3e8aad82c07aeafd72d2fe862b561cb7f8), so I update it today, is it caused by this?
There was no such problem with the older build

### Steps to reproduce the problem
Set the Target Samplerate to 96000 or 192000
### What's going on? Describe the problem in as much detail as possible.
The music is stuttering, although there is low CPU usage.
### Information about the software:
```
starting deadbeef devel
installdir: /usr
confdir: /home/laichiaheng/.config
docdir: /usr/share/doc/deadbeef
plugindir: /usr/lib/deadbeef
pixmapdir: /usr/share/deadbeef/pixmaps
server_start
searching for GUI plugins in /home/laichiaheng/.local/lib64/deadbeef
searching for GUI plugins in /home/laichiaheng/.local/lib/deadbeef
searching for GUI plugins in /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 56 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/laichiaheng/.local/lib64/deadbeef
loading plugins from /home/laichiaheng/.local/lib/deadbeef
loading plugins from /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 56 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alac.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk2.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_bs2b.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/ffmpeg.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/in_sc68.so
loading plugin /usr/lib/deadbeef/jack.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mp3.so
loading plugin /usr/lib/deadbeef/mpris.so
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib/deadbeef/psf.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/rg_scanner.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
loading plugin /usr/lib/deadbeef/wma.so
selected output plugin: PulseAudio output plugin
INFO: from file /home/laichiaheng/.config/deadbeef/playlists/0.dbpl
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.22.21
connecting button tray signals
quitting gtk
gtkui_stop completed
gui plugin has quit; waiting for mainloop thread to finish
plug_disconnect_all
plug_unload_all
stopping GTK3 user interface...
quitting gtk
stopping Adplug player...
stopping ALSA output plugin...
stopping Album Artwork...
stopping Converter...
stopping dts decoder...
stopping DUMB module player...
stopping Game-Music-Emu player...
stopping Hotkey manager...
stopping SC68 player (Atari ST SNDH YM2149)...
stopping JACK output plugin...
stopping last.fm scrobbler...
stopping MPRISv2 plugin...
stopping MusePack decoder...
stopping OSD Notify...
stopping Null output plugin...
stopping OSS output plugin...
stopping PSF player using Audio Overload SDK...
stopping PulseAudio output plugin...
stopping Shell commands...
stopping SID player...
stopping WAV/PCM player...
stopping SuperEQ...
stopping tta decoder...
stopping cURL vfs...
stopping OggVorbis decoder...
stopping VTX player...
stopping WildMidi player...
stopping FFMPEG audio player...
stopped all plugins
all plugins had been unloaded
messagepump_free
plug_cleanup
logger_free
hej-hej!

```
Deadbeef version: r7398.075edeab-1
OS: Antergos

**Comment by Alexey-Yakovenko** [comment] 2017-09-28 10:45
This issue was present for at least a few months, it's not caused by any recent change.

**Comment by JulianLai** [comment] 2017-09-28 14:45
@Alexey-Yakovenko If I set the buffer size of PulseAudio plugin to 8192, the problem is gone.
The default buffer size is too small, did you change the default buffer size before?

**Comment by Alexey-Yakovenko** [comment] 2017-09-28 14:58
There's no difference in default buffer size between 0.7.2 and master.

**Comment by Alexey-Yakovenko** [comment] 2017-11-17 13:22
This should be fixed now.

**Closed by Alexey-Yakovenko** 2017-11-17 13:22 UTC
Labels: bug
