### ISSUE TITLE
[Feature request] Ask for confirmation before clearing playlist

### ISSUE THREAD

**Issue by FridgeRacer** [DeaDBeeF-Player/deadbeef#2819] opened 2022-06-15 10:46 UTC
### Steps to reproduce the problem
With a playlist open, click "Edit" then "Empty" (or clear, depending on your language)
![bilde](https://user-images.githubusercontent.com/40672277/173808727-dc1f1963-edb3-4905-862b-6b801de48570.png)

### What's going on? Describe the problem in as much detail as possible.
Unfortunately I happened to misclick this with my internet radio playlist, where I have collected links to many many many various channels. Now I gotta hunt them down again! Not the end of the world, just a little annoying that I wasn't more careful, really :)

It'd be nice if there could be a way to, perhaps optionally, make this prompt the user if they really want to clear a playlist before doing so.

### Information about the software:
Deadbeef version: 1.9.1
OS: Arch Linux

Thanks again for all your hard work on the DeaDBeeF project!

💛💙

**Comment by Alexey-Yakovenko** [comment] 2022-06-15 10:50
duplicate of #490

**Closed by Alexey-Yakovenko** 2022-06-15 10:50 UTC

**Comment by FridgeRacer** [comment] 2022-06-15 10:52
My bad, I'll look deeper into my searches next time 😄
