### ISSUE TITLE
deadbeef, plugin and artworks [feature request]

### ISSUE THREAD

**Issue by dieug** [DeaDBeeF-Player/deadbeef#2252] opened 2019-10-28 19:15 UTC
could be nice for artwork plugin to save album artwork in album folder after downloading it from internet resources (musicbrainz etc.).

for now plugin and player works fine, but artworks has save just in some cache directory.

Deadbeef version: 1.8.2
Album Artwork 1.3
OS: debian linux x64

ps:
it's a feature request.

**Comment by Alexey-Yakovenko** [comment] 2019-10-28 19:31
duplicate of #552

**Closed by Alexey-Yakovenko** 2019-10-28 19:31 UTC
