### ISSUE TITLE
Minimal mode

### ISSUE THREAD

**Issue by sljunkie** [DeaDBeeF-Player/deadbeef#1708] opened 2017-02-06 01:47 UTC
deadbeef could have a 'minimal mode' like Winamp, XMMS, VLC and Sonata (MPD Client) by showing a window somewhat like this:

![screenshot from 2017-02-05 23-39-03](https://cloud.githubusercontent.com/assets/7532854/22632027/eaef7d9a-ebfc-11e6-8a70-de00250343b6.png)

This is a nice feature once you set up your playlist(s) and want to avoid clutter on the desktop.

**Comment by Alexey-Yakovenko** [comment] 2021-07-19 16:38
duplicate of #595

**Closed by Alexey-Yakovenko** 2021-07-19 16:38 UTC
Labels: Enhancement
