### ISSUE TITLE
Option to have the album art display follow the selection in the playlist.

### ISSUE THREAD

**Issue by RobertZenz** [DeaDBeeF-Player/deadbeef#2121] opened 2019-04-13 20:19 UTC
Currently the album art display does only show the album art of the currently played track. It would be nice to get an option to make it display the album art of the currently selected track in the playlist, f.e. the metadata view is already following the selection.

**Comment by kpcee** [comment] 2019-04-14 09:44
You can generally display the covers in the playlist, as shown on this [screenshot](http://deadbeef.sourceforge.net/screenshots/0.6/05.png).

**Comment by RobertZenz** [comment] 2019-04-14 09:48
@kpcee I was unaware that this was possibel, thank you. Though, my original request still stands.

**Comment by mallniya** [comment] 2022-02-21 20:21
Guess it's a duplicate of https://github.com/DeaDBeeF-Player/deadbeef/issues/971

**Comment by Alexey-Yakovenko** [comment] 2022-02-21 20:22
cool. Also, this has been implemented in the 1.9.0

**Closed by Alexey-Yakovenko** 2022-02-21 20:22 UTC
Labels: Enhancement
