### ISSUE TITLE
Feature request: Media library with multiple columns sourced from tags and a search bar like foo_facets

### ISSUE THREAD

**Issue by BatteryPine** [DeaDBeeF-Player/deadbeef#2746] opened 2022-02-16 20:17 UTC
I've switched over from Windows to Linux for some time and DeaDBeeF has been an immensely useful music player after using foobar2000 for years. If there's one feature I miss from foobar was the foo_facets plugin which allowed me to setup multiple columns where I could organize my music by tags instead of browsing them through a folder tree. I also miss being able to browse through songs by searching for information from their tags instead of through their filenames. Would it be possible to implement these features in the media library?

### Information about the software:

Deadbeef version: 1.8.8
OS: Kubuntu 21.10

Heres a screenshot of how I setup foo_facets as an example of how it looked:
![unknown (2)](https://user-images.githubusercontent.com/22846912/154348882-fe7d050d-a119-4e55-9313-f81e93114462.png)

**Comment by Alexey-Yakovenko** [comment] 2022-02-16 20:20
duplicate of #2710

**Closed by Alexey-Yakovenko** 2022-02-16 20:20 UTC
Labels: Duplicate
