### ISSUE TITLE
As a user, when I add a folder to a playlist, I want the "import" to be a background process so I can still use the player #Enhancement

### ISSUE THREAD

**Issue by ldexterldesign** [DeaDBeeF-Player/deadbeef#2324] opened 2020-02-01 01:09 UTC
Hi all,

Thanks for great software

Hope you're well

As title

# Steps to reproduce issue

1. Create new playlist (file > new playlist)
2. Add folders (file > add folder(s))

# Unexpected behaviour

Application "locks up" during import process (i.e. unable to switch playlists, select tracks or use playback controls)

# Expected behaviour

Application does not "lock up" during import process (i.e. able to use all player functions)

It would be useful to be able to import the music I have (terabytes) without losing the use of the player

Screen cast: https://www.dropbox.com/s/73017f8izo3chaq/foo.webm

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up great work!

Yours hopefully 

PS please update the about view for next release! 🙏

<img width="392" alt="Screenshot 2020-02-01 at 02 00 11" src="https://user-images.githubusercontent.com/1715809/73584132-a1e2cd00-4496-11ea-86f4-d011d1208915.png">

hardware: Apple, MacBook Pro (16-inch, 2019)
software - operating system: Apple, macOS, 10.15.2 (19C57)
software - application: DeaDBeeF, erm... latest version?

**Comment by Alexey-Yakovenko** [comment] 2020-02-01 10:52
duplicate of #690

**Closed by Alexey-Yakovenko** 2020-02-01 10:52 UTC
