### ISSUE TITLE
Ogg-FLAC streams and files do no play

### ISSUE THREAD

**Issue by bubbleguuum** [DeaDBeeF-Player/deadbeef#3059] opened 2024-03-19 18:01 UTC
For example, Radio Paradise:

https://stream.radioparadise.com/flacm

It results in this error:

`No suitable decoder found for stream https://stream.radioparadise.com/flacm of content-type application/ogg`

Tap mapping for network streams and `application/ogg` mime-type is the default value `stdogg opus ffmpeg`

FFmpeg plugin is of course installed.

A file with ogg container with FLAC audio does not play as well.

Such file can be trivially generated from any FLAC file with:

`ffmpeg -i file.flac -c:a copy -vn file.ogg`

**Comment by Oleksiy-Yakovenko** [comment] 2024-03-19 18:02
duplicate of #1122

**Closed by Oleksiy-Yakovenko** 2024-03-19 18:02 UTC
Labels: Duplicate
