### ISSUE TITLE
[Feature Request] 32-bit sample size support

### ISSUE THREAD

**Issue by Single34** [DeaDBeeF-Player/deadbeef#2003] opened 2018-04-13 02:15 UTC
### Steps to reproduce the problem
deadbeef music.m4a
### What's going on? Describe the problem in as much detail as possible.

The player crashes with this:

FIXME: unimplemented sample size 32
FIXME: unimplemented sample size 32
Segmentation Fault
backtrace() returned 6 addresses
deadbeef(+0x32dba) [0x5645a9839dba]
/usr/lib/libc.so.6(+0x348e0) [0x7fa6a07328e0]
/usr/lib/deadbeef/alac.so(+0x444a) [0x7fa69541544a]
deadbeef(+0x43cdc) [0x5645a984acdc]
/usr/lib/libpthread.so.0(+0x708c) [0x7fa6a0abc08c]
/usr/lib/libc.so.6(clone+0x3f) [0x7fa6a07f3e7f]

Probably the sample size is not implemented in the player?

And by the way, I got this from ffprobe music.m4a

  Duration: 00:02:51.01, start: 0.000000, bitrate: 4013 kb/s
    Stream #0:0(und): Audio: alac (alac / 0x63616C61), 96000 Hz, stereo, s32p, 3957 kb/s (default)
    Metadata:
      creation_time   : 2018-03-30T18:24:01.000000Z
    Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 1668x1647, 90k tbr, 90k tbn, 90k tbc

### Information about the software:

Deadbeef version:0.7.2
OS:Arch linux

**Comment by Alexey-Yakovenko** [comment] 2018-04-13 09:36
I could not reproduce this problem with a 32 bit ALAC test that I could come up with..
Could you provide a way to create such file, or share your file somewhere?

**Comment by Alexey-Yakovenko** [comment] 2018-04-13 09:37
Actually.. I think that maybe the problem has been fixed on trunk already.

**Comment by Alexey-Yakovenko** [comment] 2018-04-23 08:56
no response from OP, can't repro - closing

**Closed by Alexey-Yakovenko** 2018-04-23 08:56 UTC
Labels: bug
