### ISSUE TITLE
How to add local cover art image to mp3 file?

### ISSUE THREAD

**Issue by bcoolumbo1** [DeaDBeeF-Player/deadbeef#2234] opened 2019-10-05 15:07 UTC
How to add local cover art image to mp3 file?
Cannot find a menu point to do that.
I do NOT want to connect any thirdparty online service.
I want to add my own locally saved image as cover art.
I could do that with eyeD3 --add-image but this is way too complicated.
Maybe there is a solution with custom shell command?
Thanks.
Linux, Deadbeef devel

**Comment by Alexey-Yakovenko** [comment] 2019-10-05 16:15
I don't think deadbeef can do this yet.
It is however a duplicate of #1031

**Closed by Alexey-Yakovenko** 2019-10-05 16:15 UTC
