### ISSUE TITLE
Open latest files dialog instead of remembering the last opened directory

### ISSUE THREAD

**Issue by BigSerpent** [DeaDBeeF-Player/deadbeef#2083] opened 2019-02-06 18:20 UTC
### Steps to reproduce the problem
Open file via File-Open files dialog.

### What's going on? Describe the problem in as much detail as possible.
The resulted dialog does not contain the latest directory as the initial one. Instead it is a dialog with the latest opened files of the Mate desktop.

### Information about the software:
Deadbeef version: the latest from the repository http://ppa.launchpad.net/alex-p/deadbeef/ubuntu bionic main

OS:
Mint Linux 19.1 Mate x64

**Comment by Alexey-Yakovenko** [comment] 2019-03-10 11:54
Can't reproduce.

**Comment by Alexey-Yakovenko** [comment] 2019-03-10 11:56
NOTE: I'm not using MATE or Mint, however, this is not something that should differ across different environments. If it differs - it should be verified with other applications / other environments, and perhaps forwarded to Mint or MATE devs.

**Comment by BigSerpent** [comment] 2019-03-12 20:14
I use several gtk+ programs at my computer, including gimp 2.10.8, darktable (gtk+-3),  inkscape, geeqie. Neither of them have such a problem. It was introduced not far ago. I've just downloaded statically build 0.7.2 from sf.net and it does not have this problem.

**Comment by BigSerpent** [comment] 2019-03-12 20:17
![Снимок экрана в 2019-03-12 23-15-26](https://user-images.githubusercontent.com/47396887/54232931-e2eb8f00-451c-11e9-9a08-289e8e520a04.png)
![Снимок экрана в 2019-03-12 23-14-48](https://user-images.githubusercontent.com/47396887/54232966-f860b900-451c-11e9-8ab6-b55e9ace962b.png)
Here is the difference in the file open dialogs.

**Comment by Alexey-Yakovenko** [comment] 2019-03-12 20:40
OK.. that's weird since I don't think anything has changed in the code which could have caused this problem. I will find a way to install mint/mate, and reproduce the problem.

**Comment by BigSerpent** [comment] 2019-03-13 05:29
Sorry. I'm mistaken. I've just tried to open a file in gimp and saw the same problem (usually I open it via external viewer). So it's the fail of Mint.
P.S. Strange, but the old version of deadbeef works perfectly.

**Comment by BigSerpent** [comment] 2019-03-16 10:24
So after conversations with Mint developers and thorough look how GIMP opens files I think the problem is in deadbeef.  GIMP shows the same dialog for the first time in a session (it is the first file after program was started), but further it proposes the full path with the last directory from the session. And deadbeef does not remember the directory within session. 
Mint developers said they hadn't updated libgtk2.0-0 after the system release.

**Comment by BigSerpent** [comment] 2019-03-16 11:25
Yes, of course :)
![Peek 2019-03-16 14-23](https://user-images.githubusercontent.com/47396887/54474556-54665e80-47f7-11e9-9b98-a4e8429e2b07.gif)

**Comment by Alexey-Yakovenko** [comment] 2019-03-16 11:35
Ok.. This is definitely not happening on my Ubuntu.
This is what I see when the dialog opens here.
It doesn't automatically go to "Recent" -- instead, it goes to the previous / saved directory.
So I still tend to believe that this is something that's either preconfigured in Mint, or something that you've configured locally.

Have you tried running this in another DE or clean X11 session without any WM?
Preferably on a clean new user account.

![image](https://user-images.githubusercontent.com/1895698/54474625-57f1e980-47e7-11e9-9fe5-88a912e053bf.png)

**Comment by Alexey-Yakovenko** [comment] 2019-03-16 11:36
Please see this stackexchange post: https://unix.stackexchange.com/questions/74031/disable-recently-used-in-gtk-file-directory-selector

It describes exactly how this behavior can be configured, and the user who posted it apparently had the same problem as you.

**Comment by Alexey-Yakovenko** [comment] 2019-03-16 11:41
Closing the issue again, because it's quite apparent that's a local configuration problem, and there isn't much I can do with it.

**Comment by Alexey-Yakovenko** [comment] 2019-07-13 10:46
Reopening since now I can reproduce this issue on default configuration of ubuntu 18.04

**Comment by Alexey-Yakovenko** [comment] 2019-07-13 10:58
blame: 0a165ae8df0ca15aaccf2e4c69f32a84f4e1a814

**Comment by Alexey-Yakovenko** [comment] 2019-07-13 11:00
Fixed in commit c9cf1d7e81a2384b775e94783c40a203f5e06d09

**Closed by Alexey-Yakovenko** 2019-07-13 11:00 UTC
Labels: Invalid
