### ISSUE TITLE
Open containing folder

### ISSUE THREAD

**Issue by artenax** [DeaDBeeF-Player/deadbeef#3133] opened 2024-09-19 13:09 UTC
Hello.
I am missing this functionality.
When I right click on a track in a playlist.
Other players have it.

For example, if I have not all tracks of an audiobook loaded, I press “Open containing folder” and drag and drop into the playlist.

**Comment by kuba160** [comment] 2024-09-19 13:20
Duplicate of https://github.com/DeaDBeeF-Player/deadbeef/issues/1526

**Closed** 2024-09-19 13:28 UTC

**Comment by Oleksiy-Yakovenko** [comment] 2024-09-19 19:42
@artenax I don't mind if it gets added -- I just don't have time for this. If someone contributes the code -- I'll gladly accept.
