### ISSUE TITLE
Crash When Track Is Finished

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#1970] opened 2018-02-09 20:20 UTC
### Steps to reproduce the problem
Add a song to the playlist, then play it until the end.

### What's going on? Describe the problem in as much detail as possible.
Deadbeef crashes with a segmentation fault.

Deadbeef version: Latest Git (2-9-18)
OS: Arch Linux 64bit

Segmentation Fault
backtrace() returned 6 addresses
deadbeef(+0x3384a) [0x55d5bd77484a]
/usr/lib/libc.so.6(+0x348e0) [0x7ff9217578e0]
deadbeef(+0x4706a) [0x55d5bd78806a]
/usr/lib/deadbeef/alsa.so(+0x2bf5) [0x7ff918b62bf5]
/usr/lib/libpthread.so.0(+0x708c) [0x7ff921ae108c]
/usr/lib/libc.so.6(clone+0x3f) [0x7ff921818e7f]
deadbeef: hb-object-private.hh:154: Type* hb_object_reference(Type*) [with Type = hb_unicode_funcs_t]: Assertion `hb_object_is_valid (obj)' failed.
zsh: abort (core dumped)  deadbeef

**Comment by Alexey-Yakovenko** [comment] 2018-02-09 20:49
More than likely a duplicate of #1968.
We're looking into it.

**Closed by Alexey-Yakovenko** 2018-02-09 20:49 UTC
Labels: duplicate
