### ISSUE TITLE
[feature request] open containing folder in filemanager

### ISSUE THREAD

**Issue by ghost** [DeaDBeeF-Player/deadbeef#2280] opened 2019-12-08 15:46 UTC
via context menu entry on selected song. a quick jump feature.

**Comment by kpcee** [comment] 2019-12-08 16:55
This is already possible, see [Open location from track context menu](https://github.com/DeaDBeeF-Player/deadbeef/issues/1610).

**Comment by ghcatt** [comment] 2019-12-08 17:20
ok, i see. thanks a lot ;)

**Comment by Alexey-Yakovenko** [comment] 2019-12-08 23:17
Will keep this open as an enhancement, since people are asking for this too often, not realizing how to make it work.
Possibly I should come up with some solution for predefined shellexec commands.

**Comment by pinballmachine** [comment] 2022-02-02 19:53
I hope you still consider adding this as a default entry in the context menu. I found the solution by searching the open issues list, so it appears it can be made to work already, but having it by default would make life easier for a lot of people, I think.

**Comment by Alexey-Yakovenko** [comment] 2022-02-03 07:43
Yes, I'm considering. It grew on me that this should be a default option, instead of the user having to configure it every time.

**Comment by mallniya** [comment] 2022-02-22 20:19
Duplicate of https://github.com/DeaDBeeF-Player/deadbeef/issues/1526

**Closed** 2022-02-22 20:48 UTC
Labels: Duplicate
