### ISSUE TITLE
Request: Add covers in media tags for all media types supported

### ISSUE THREAD

**Issue by geplus** [DeaDBeeF-Player/deadbeef#1854] opened 2017-08-16 18:36 UTC
Hi, 
can we have a function to add directly into the files the album cover images as embeded images?
This is a common funcion in players like clementine or gmusicbrowser.

**Comment by Alexey-Yakovenko** [comment] 2017-08-16 20:57
duplicate of #1031

**Closed by Alexey-Yakovenko** 2017-08-16 20:57 UTC

**Comment by geplus** [comment] 2017-08-17 20:02
Sorry for the duplicate (2 years is alot of time)

So, are you planning to add this function in a less long than other 2 years time frame?

**Comment by Alexey-Yakovenko** [comment] 2017-08-17 22:00
https://github.com/DeaDBeeF-Player/deadbeef/wiki/FAQ#can-you-implement-my-favorite-feature-and-when
