### ISSUE TITLE
ALSA playback sample rate only switching after skipping one track

### ISSUE THREAD

**Issue by Sir-Photch** [DeaDBeeF-Player/deadbeef#2894] opened 2022-11-23 07:28 UTC
### Steps to reproduce the problem
- fill playlist with tracks of different sample rate
- use ALSA output plugin
- uncheck everything in the output tab
- in plugins -> alsa -> disable alsa-resampling
- switch between tracks of different sample rate

### What's going on? Describe the problem in as much detail as possible.
When playing e.g. a 48khz track, I can see that my DAC is receiving a 48khz signal. When now switching to a track of different rate, e.g. 96khz, my DAC does not report a 96khz signal; This only happens when I switch to another track with the same 96khz sample rate, _a second time_.

### Information about the software:

Deadbeef version: git build
OS: Arch

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-23 08:21
Which sound server? (pulse/pipewire/none?)

**Comment by Sir-Photch** [comment] 2022-11-23 09:13
```console
$ pipewire --version
pipewire
Compiled with libpipewire 0.3.60
Linked with libpipewire 0.3.60
```

But shouldn't this be bypassed when using ALSA kernel module directly in deadbeef?

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-23 20:28
> But shouldn't this be bypassed when using ALSA kernel module directly in deadbeef?

My understanding can be wrong / out of date, but as far as I understand -- as long as the pulse or pipewire server is configured and active, any calls to ALSA will be handled by those servers.

Regarding your problem:

Deadbeef doesn't (yet) support pipewire natively out of the box, so at the very least you need to install the 3rd party pipewire plugin.
Regardless of what the problem is -- you have the following options to try.
1. don't use pipewire
2. use the 3rd party pipewire plugin for deadbeef, [from here](https://github.com/saivert/ddb_output_pw)
3. wait until deadbeef supports pipewire natively, although this would be the same as [2]
4. If none of the above works -- you should probably consider seeking help with pipewire devs, or the pipewire plugin devs.

If you think the problem is within the ALSA code in deadbeef -- please make sure to reproduce it with pipewire server **stopped**, then I will consider investigating.

(The reason why I'm not spending too much time on investigating every bug which says "ALSA plugin playing via Pipewire is behaving weird" is because it is generally known that this doesn't work all that well, and there's not much I can do)

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-23 20:30
> This is maybe also mentioned in https://github.com/DeaDBeeF-Player/deadbeef/issues/1972.

For a moment I thought that this may be the same problem, but after carefully reading the description doesn't seem like it is the same issue.

**Comment by Sir-Photch** [comment] 2022-11-23 21:31
> 1. don't use pipewire

I doubt that this is a pipewire specific issue. Audacious has no issues using bit-perfect playback on ALSA output while a pipewire server is running.

> 2. use the 3rd party pipewire plugin for deadbeef

This would defeat my intention of bit perfect playback, since the pipewire plugin seems to resample the pcm signal and I can't find an option to turn this off.

Anyway, I can not confirm ALSA playback to work properly when pipewire / wireplumber is stopped. The issue still persists:

```
$ systemctl stop --user pipewire.socket
$ systemctl stop --user wireplumber.service
```
After executing these commands, I cannot playback anything through pipewire / default system output. (As expected.) I can still use ALSA in deadbeef though, but the behaviour I mentioned still occurs.

Can I provide you with any additional information?

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-23 21:46
Thanks for checking with ALSA without pipewire.
I'm reopening the issue. I will have to investigate and see if I can reproduce the same problem.
Before then, I can't provide any additional information.

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-23 21:48
> Can I provide you with any additional information?

Thanks, seems to be enough information for now.

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-24 19:18
I tried to reproduce the problem, and I could not get it -- on my configuration everything works as expected.

Although my configuration is quite different from your's, from the code perspective it should be doing the same thing.

I was running Ubuntu 16.04, resamplers disabled (both in the ALSA plugin, and in the DSP settings)
Output device: direct output without any conversions.
Built-in soundcard on the motherboard.
Pulse audio service was stopped, and wasn't showing up in the process list.

I was playing a bunch of 48K and 96K tracks following after one another, and checking `/proc/asound/snd0p/sub0/hw_params` -- the hardware samplerate was changing when expected, without any extra actions.

I can only imagine that your DAC has some quirk, which prevents it from switching samplerate unless playback is stopped beforehand (which occurs when you start the track manually).

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-24 19:23
I don't own an external DAC, and even if I had -- it's not guaranteed that the same problem would occur.
So experimenting with this bug is quite out of question for me. If you know how to code -- you can try experimenting with it yourself, and add some stop/resume calls in the ALSA plugin?

Aside of that, I recommend to uncomment this line / apply patch, and see what kind of logs you will be getting on track switching.
```
diff --git a/plugins/alsa/alsa.c b/plugins/alsa/alsa.c
index c6e28a57d..7021a571b 100644
--- a/plugins/alsa/alsa.c
+++ b/plugins/alsa/alsa.c
@@ -819,7 +819,7 @@ static DB_output_t plugin = {
     .plugin.version_major = 1,
     .plugin.version_minor = 0,
     .plugin.type = DB_PLUGIN_OUTPUT,
-//    .plugin.flags = DDB_PLUGIN_FLAG_LOGGING,
+    .plugin.flags = DDB_PLUGIN_FLAG_LOGGING,
     .plugin.id = "alsa",
     .plugin.name = "ALSA output plugin",
     .plugin.descr = "plays sound through linux standard alsa library",
```

**Comment by Sir-Photch** [comment] 2022-11-25 19:41
Okay so I more or less have some experience with C, and I'll try to look into it in the future.
In the meantime, this is the log output with the enabled flag:

<details>
<summary>Switching within 96kHz</summary>

```
palsa_free
alsa_soundcard: front:CARD=AUDIO,DEV=0
chosen sample format: 000Ah
chosen samplerate: 96000 Hz
minchan: 2, maxchan: 2
setting chan=2
alsa channels: 2
trying buffer size: 8192 frames
trying period size: 1024 frames
alsa buffer size: 8192 frames
alsa period size: 1024 frames
chosen bps: 32 (int)
alsa avail_min: 1024 frames
```

</details>

<details>
<summary>Switching from 96kHz to 48kHz</summary>

```
palsa_free
alsa_soundcard: front:CARD=AUDIO,DEV=0
chosen sample format: 000Ah
chosen samplerate: 96000 Hz
minchan: 2, maxchan: 2
setting chan=2
alsa channels: 2
trying buffer size: 8192 frames
trying period size: 1024 frames
alsa buffer size: 8192 frames
alsa period size: 1024 frames
chosen bps: 32 (int)
alsa avail_min: 1024 frames
palsa_setformat 24bit int 2ch 48000Hz channelmask=3
switching format to (requsted -> actual):
bps 24 -> 32
is_float 0 -> 0
channels 2 -> 2
samplerate 48000 -> 96000
channelmask 3 -> 3
chosen sample format: 000Ah
chosen samplerate: 96000 Hz
minchan: 2, maxchan: 2
setting chan=2
alsa channels: 2
trying buffer size: 8192 frames
trying period size: 1024 frames
alsa buffer size: 8192 frames
alsa period size: 1024 frames
chosen bps: 32 (int)
new format 32bit int 2ch 96000Hz channelmask=3
```

</details>

> I can only imagine that your DAC has some quirk, which prevents it from switching samplerate unless playback is stopped beforehand (which occurs when you start the track manually).

This also occurs when I manually switch between tracks of different samplerate.

Actually, now, when switching to tracks with a higher sample rate than the current track, the playback is distorted. (48kHz -> 96kHz: DAC still at 48kHz, "playback at 0.5 speed")

**Comment by Sir-Photch** [comment] 2022-11-25 20:13
I tried changing `snd_pcm_hw_params_set_rate_near` to the similar call without `_near`, and now the playback fails on switching between tracks with a different samplerate. Is this somewhat expected?

```c
diff --git a/plugins/alsa/alsa.c b/plugins/alsa/alsa.c
index c6e28a57d..03c90d67f 100644
--- a/plugins/alsa/alsa.c
+++ b/plugins/alsa/alsa.c
@@ -225,11 +225,26 @@ palsa_set_hw_params (ddb_waveformat_t *fmt) {
         goto error;
     }

+
+
+    /*
     if ((err = snd_pcm_hw_params_set_rate_near (audio, hw_params, &val, &ret)) < 0) {
         fprintf (stderr, "cannot set sample rate (%s)\n",
                 snd_strerror (err));
         goto error;
     }
+    */
+
+    trace ("foo\n");
+
+    if ((err = snd_pcm_hw_params_set_rate(audio, hw_params, val, ret)) < 0) {
+        fprintf(stderr, "cannot set sample rate (%s)\n", snd_strerror(err));
+        goto error;
+    }
+
+    trace ("bar\n");
+
+
     plugin.fmt.samplerate = val;
     trace ("chosen samplerate: %d Hz\n", val);
```

**Comment by kuba160** [comment] 2022-11-26 16:32
I tried to use deadbeef with alsa on my amplifier and it detects switching from 44.1kHz to 96kHz and back correctly. As I understand you didn't experience similar issues with Audacious?

Switching sample rates with some amplifiers can be problematic and I sometimes experience it myself. Have you tried to switch audio source back and forth on your amplifier? It usually fixes no audio problems for me. Also are you using SPDIF connection or HDMI?

**Comment by Sir-Photch** [comment] 2022-11-26 18:17
> As I understand you didn't experience similar issues with Audacious?

Exactly, which is a shame, since I really think deadbeef is the superior audio player.

> Have you tried to switch audio source back and forth on your amplifier? It usually fixes no audio problems for me. Also are you using SPDIF connection or HDMI?

No, my DAC is connected via USB and I am using its headphone output. In my case there are only two working options for ALSA-output, "default audio device" and "front headphone output". The former rarely works properly, the latter is the one I'd be using.

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-27 09:25
> I tried changing snd_pcm_hw_params_set_rate_near to the similar call without _near, and now the playback fails on switching between tracks with a different samplerate. Is this somewhat expected?

This indicates that ALSA can't switch to the samplerate that is requested.
Whether it's expected or not depends on specific device, its driver, alsa config and so on.

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-27 09:38
I bet that your DAC simply "dislikes" that hw params do change while playback is active, and it probably prefers that the device is deinitialized / stopped before the change. Maybe it's enough to simply call snd_pcm_drop before the change, and then snd_pcm_prepare and snd_pcm_start after the change (depending on the state of course).

**Comment by Sir-Photch** [comment] 2022-11-27 11:09
> Maybe it's enough to simply call snd_pcm_drop before the change, and then snd_pcm_prepare and snd_pcm_start after the change (depending on the state of course).

Unfortunately does not seem to be the case:

```c
@@ -635,7 +638,10 @@ palsa_thread (void *context) {
         // setformat
         int res = 0;
         if (_setformat_requested) {
-            res = _setformat_apply ();
+            snd_pcm_drop(audio);
+            res = _setformat_apply ();
+            snd_pcm_prepare(audio);
+            snd_pcm_start(audio);
         }
```

Stopping playback and starting it manually, while switching between different rate tracks has not fixed this anyway so I did not expect this to work.

I also had a peek at what the guys over at audacious are doing: [alsa.cc L558](https://github.com/audacious-media-player/audacious-plugins/blob/master/src/alsa/alsa.cc#L558); They apparently use a mixer as well. Why is this not the case for deadbeef? Or is this unrelated? I tried to implement a similar mixer-setup with the `"default"` mixer for the deadbeef-alsa-plugin, but this did not change anything 🥲

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-27 11:18
Ok another thing that audacious seems to be doing -- they are closing / opening the device on every samplerate change, which may be the cause why it works. Regarding the mixer -- it looks like audacious uses it to control hardware volume and balance, which deadbeef doesn't use.

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-27 11:23
You can also try playing with operation order.
Audacious does this order: format, channels, rate
Deadbeef does another order: format, rate, channels

Maybe reordering this would affect something.

**Comment by Sir-Photch** [comment] 2022-11-27 14:07
> Ok another thing that audacious seems to be doing -- they are closing / opening the device on every samplerate change, which may be the cause why it works.

Seems to be likely! I modified the code in `palsa_thread()`:
```c
@@ -694,7 +641,18 @@ palsa_thread (void *context) {
         // setformat
         int res = 0;
         if (_setformat_requested) {
-            res = _setformat_apply ();
+            snd_pcm_drop(audio);
+            snd_pcm_close(audio);
+            int prev_state = state;
+            palsa_init(0);
+            res = _setformat_apply ();
+            trace ("setformat res %d\n", res);
+            snd_pcm_prepare(audio);
+            if (prev_state == DDB_PLAYBACK_STATE_PLAYING) {
+                snd_pcm_start(audio);
+                state = DDB_PLAYBACK_STATE_PLAYING;
+            }
+
         }
```

And now, the sample rate is switched correctly on my DAC when I switch tracks. However, my changes seem to leave deadbeef in a deadlocked state, since I am calling `palsa_init()` from inside the thread itself which is spawning it. (I added a flag to be unset if a thread is not to be spawned. This does not seem to help though.) 

Maybe I open up a draft PR and you have a look?

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-27 15:06
Well, I can make the fix for this.. Probably would be easier this way, than going back and forth with PRs.
Thanks for investigating -- this was super useful.

**Closed** 2022-11-27 18:18 UTC
Labels: Bug

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-27 18:19
I pushed the fix. Please let me know if it causes any new problems. The ALSA plugin code is not particularly easy to work with, so I might have missed something.

**Comment by Sir-Photch** [comment] 2022-11-27 18:51
Yes, this works now! Thank you very much for your responsiveness -- If there is anything else, I will let you know. For the time being, I'll enjoy my DAC's display showing the correct image 😄

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-27 18:54
Great!
