### ISSUE TITLE
DSP settings are lost and not put in effect in macOS

### ISSUE THREAD

**Issue by retrography** [DeaDBeeF-Player/deadbeef#2397] opened 2020-06-04 09:49 UTC
### Steps to reproduce the problem

Change anything in default DSP settings (remove EQ, or switch autodetect on Resampler), and restart DeaDBeef. You will notice your settings are gone. You can as well try to save a preset. The preset will be gone as well. Some times some settings are randomly saved, but I don't know when or why.

### What's going on? Describe the problem in as much detail as possible.

DSP settings and presets are lost after restart.

### Information about the software:

Deadbeef version: Version 1.0 (8b99af1)
OS: macOS Catalina Version 10.15.4 (19E287)

**Comment by Alexey-Yakovenko** [comment] 2020-06-04 17:23
Removing EQ from the "active" dsp chain will always re-add it automatically. This is by design.

**Comment by Alexey-Yakovenko** [comment] 2020-06-04 17:24
Disabling autodetect on resampler -- gets saved every time, I could not make it not save.

**Comment by Alexey-Yakovenko** [comment] 2020-06-04 17:26
Saving and deleting DSP presets also works fine, I could not make it not save.

I'm going to ask some friends on Slack to test this, but it's not very promising -- seems like a local problem of some sort.

**Comment by Alexey-Yakovenko** [comment] 2020-06-21 13:23
I could not reproduce this, and I couldn't get anyone else to try and confirm this issue, so closing until more information pops up.

**Closed by Alexey-Yakovenko** 2020-06-21 13:23 UTC
Labels: Triage
