### ISSUE TITLE
Segmentation fault on quitting with the search window open

### ISSUE THREAD

**Issue by rsekman** [DeaDBeeF-Player/deadbeef#2808] opened 2022-05-31 21:50 UTC
### Steps to reproduce the problem

1. Open the search window
2. Quit DeaDBeeF from File->Quit.
3. Segmentation fault.

### What's going on? Describe the problem in as much detail as possible.

Console log:
```
connecting button tray signals
quitting gtk
gtkui_stop completed
Segmentation Fault
backtrace() returned 2 addresses
deadbeef(+0x51da6) [0x560141430da6]
/usr/lib/libc.so.6(+0x3e8e0) [0x7fceed1c48e0]
```

Valgrind log:
```
==156687== Invalid read of size 8
==156687==    at 0x53F3ADB: ??? (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x5D82B34: UnknownInlinedFun (gobject.c:3678)
==156687==    by 0x5D82B34: g_object_unref (gobject.c:3553)
==156687==    by 0x6002106: g_datalist_clear (gdataset.c:273)
==156687==    by 0x5D82B34: UnknownInlinedFun (gobject.c:3678)
==156687==    by 0x5D82B34: g_object_unref (gobject.c:3553)
==156687==    by 0x6D3AB67: UnknownInlinedFun (canberra-gtk-module.c:184)
==156687==    by 0x6D3AB67: UnknownInlinedFun (canberra-gtk-module.c:840)
==156687==    by 0x6D3AB67: quit_handler (canberra-gtk-module.c:963)
==156687==    by 0x558AB7F: gtk_main (in /usr/lib/libgtk-x11-2.0.so.0.2400.33)
==156687==    by 0x53CA538: ??? (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x15AE85: ??? (in /usr/bin/deadbeef)
==156687==    by 0x4A1428F: (below main) (libc_start_call_main.h:58)
==156687==  Address 0x1f5b82c0 is 224 bytes inside a block of size 296 free'd
==156687==    at 0x484826F: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==156687==    by 0x53D0FD0: search_destroy (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x53CB180: ??? (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x6022162: UnknownInlinedFun (gmain.c:3417)
==156687==    by 0x6022162: g_main_context_dispatch (gmain.c:4135)
==156687==    by 0x60789E8: g_main_context_iterate.constprop.0 (gmain.c:4211)
==156687==    by 0x60216A2: g_main_loop_run (gmain.c:4411)
==156687==    by 0x558A9FD: gtk_main (in /usr/lib/libgtk-x11-2.0.so.0.2400.33)
==156687==    by 0x53CA538: ??? (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x15AE85: ??? (in /usr/bin/deadbeef)
==156687==    by 0x4A1428F: (below main) (libc_start_call_main.h:58)
==156687==  Block was alloc'd at
==156687==    at 0x484AA73: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==156687==    by 0x53FA36C: playlist_controller_new (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x53D1BEC: search_playlist_init (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x53C9688: gtkui_mainwin_init (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x53CA532: ??? (in /usr/lib/deadbeef/ddb_gui_GTK2.so)
==156687==    by 0x15AE85: ??? (in /usr/bin/deadbeef)
==156687==    by 0x4A1428F: (below main) (libc_start_call_main.h:58)
==156687==
```

Could be a race condition regarding which window is destroyed first?

### Information about the software:

Deadbeef version: built from 1079a1420.
OS: 
```
% uname -a
Linux naoetsu 5.17.9-arch1-1 #1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000 x86_64 GNU/Linux
```

**Comment by Alexey-Yakovenko** [comment] 2022-06-01 16:47
Closing since I can't reproduce, tried on mac and linux, both 1.9.1 and latest master.
Will reopen if any new relevant details are provided.

**Closed by Alexey-Yakovenko** 2022-06-01 16:47 UTC
