### ISSUE TITLE
webm not supported

### ISSUE THREAD

**Issue by glowinthedark** [DeaDBeeF-Player/deadbeef#2931] opened 2023-03-20 01:25 UTC
### Steps to reproduce the problem
Play a webm file, for example one downloaded with the following command (uses [yt-dlp](https://github.com/yt-dlp/yt-dlp))

```bash
yt-dlp -F251 Sm3nAugY4Kc
```

### What's going on? Describe the problem in as much detail as possible.
File not recognized. drag-n-drop does nothing

### Information about the software:

Deadbeef version: devel (94a8acb)
OS: macos ventura 13.0.1 (22A400)

### notes

file plays fine with mpv, vlc, ffplay, etc

### file info
```
❯ mediainfo La\ Portugaise\ \[Sm3nAugY4Kc\].webm
General
Complete name                            : La Portugaise [Sm3nAugY4Kc].webm
Format                                   : WebM
Format version                           : Version 4
File size                                : 3.58 MiB
Duration                                 : 3 min 39 s
Overall bit rate                         : 137 kb/s
Writing application                      : google/video-file
Writing library                          : google/video-file

Audio
ID                                       : 1
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 3 min 39 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-20 08:49
duplicate of #2915

**Closed by Oleksiy-Yakovenko** 2023-03-20 08:49 UTC
