### ISSUE TITLE
Cuesheet loads and tracks are playing, but duration of all tracks is 0

### ISSUE THREAD

**Issue by rav242** [DeaDBeeF-Player/deadbeef#2412] opened 2020-07-18 05:55 UTC
### Steps to reproduce the problem
load this cue-sheet https://drive.google.com/file/d/1W7flICLlCmvTKO3cgkLZfY4S2FB5rPSE/view?usp=sharing
### What's going on? Describe the problem in as much detail as possible.
length of all tracks except for the last one is 0
### Information about the software:

Deadbeef version: 1.8.4
OS: Manjaro 20

**Comment by rav242** [comment] 2020-07-18 06:05
OK. I got it. If you remove all 
REM COMPOSER ""
strings and save it, then the cue-sheet is read OK.

**Comment by Alexey-Yakovenko** [comment] 2020-07-18 08:55
This is already fixed on master branch, as part of fixing #2389.
Now I have also added code necessary to load such fields, instead of ignoring it.

**Comment by rav242** [comment] 2020-10-04 07:03
Ok. I downloaded the latest build: deadbeef-static_devel-1_x86_64.tar.bz2 | 2020-10-01 | 8.4 MB.

Now all the tracks has 0 duration and seekbar is not working, but at least I can play these tracks.

Here is an example cue-sheet:
REM GENRE Alternative
REM DATE 2005
REM DISCID E411DE10
REM COMMENT "ExactAudioCopy v0.99pb1"
PERFORMER "Nine Inch Nails"
TITLE "With Teeth"
FILE "Nine Inch Nails - With Teeth.ape" WAVE
  TRACK 01 AUDIO
    TITLE "All Love In The World"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "You Know What You Are?"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 05:15:24
  TRACK 03 AUDIO
    TITLE "The Collector"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 08:57:21
  TRACK 04 AUDIO
    TITLE "The Hands That Feeds"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 12:04:62
  TRACK 05 AUDIO
    TITLE "Love Is Not Enough"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 15:36:43
  TRACK 06 AUDIO
    TITLE "Every Day Is Exactly The Same"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 19:17:72
  TRACK 07 AUDIO
    TITLE "With Teeth"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 24:12:66
  TRACK 08 AUDIO
    TITLE "Only"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 29:50:48
  TRACK 09 AUDIO
    TITLE "Getting Smaller"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 34:13:57
  TRACK 10 AUDIO
    TITLE "Sunspots"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 37:49:24
  TRACK 11 AUDIO
    TITLE "The Line Begins To Blur"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 41:52:40
  TRACK 12 AUDIO
    TITLE "Beside You In Time"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 45:37:00
  TRACK 13 AUDIO
    TITLE "Right Where It Belongs"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 51:01:52
  TRACK 14 AUDIO
    TITLE "Home"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 56:06:44
  TRACK 15 AUDIO
    TITLE "The Hand That Feeds (Photek Straight Remix)"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 60:35:60
  TRACK 16 AUDIO
    TITLE "The Hand That Feeds (Photek Dub Remix)"
    PERFORMER "Nine Inch Nails"
    FLAGS DCP
    INDEX 01 68:28:30

**Comment by lomereiter** [comment] 2020-10-26 09:13
I ran into this regression as well, "FLAGS DCP" appears to be what triggers it.

**Comment by Alexey-Yakovenko** [comment] 2020-11-22 18:04
@rav242 did you re-add the music into playlist after updating deadbeef to the latest build?
It seems like it just used whatever was already loaded from cue.. you need to delete the weird tracks, and re-add the music to fix it.

(Although I'm still having other unrelated weirdness on linux, which I'm not having on mac, so working on fixing this now)

**Comment by Alexey-Yakovenko** [comment] 2020-11-22 20:27
ok. I validated on linux, and everything works as intended. no zero length tracks, everything plays fine.
I still do believe this was a bug in 1.8.4, and it's already been fixed. just make sure to re-add the files to playlist.

**Comment by saivert** [comment] 2020-11-22 20:46
I can confirm this is only an issue on 1.8.4. On build from master it is resolved.

**Comment by Alexey-Yakovenko** [comment] 2020-11-23 07:20
Thanks!

**Closed by Alexey-Yakovenko** 2020-11-23 07:20 UTC
Labels: Bug
