### ISSUE TITLE
cannot open .opus file

### ISSUE THREAD

**Issue by Jee-bit** [DeaDBeeF-Player/deadbeef#2296] opened 2019-12-28 11:09 UTC
### Steps to reproduce the problem
 I downloaded every file again (for Debian
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.2/deadbeef-static_1.8.2-1_x86_64.tar.bz2/download
http://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.2/deadbeef-static_1.8.2-1_amd64.deb/download
and all of them still give the same error ERROR: could not load: .../Exegesis.opus
https://bugs.archlinux.org/task/63484
### What's going on? Describe the problem in as much detail as possible.
and all of them still give the same error ERROR: could not load: .../Exegesis.opus
https://bugs.archlinux.org/task/63484
### Information about the software:

Deadbeef version:1.8.2 also tried 1.8.1
OS:Debian /Bullseye/Sid

**Comment by Alexey-Yakovenko** [comment] 2019-12-28 12:05
duplicate of #2295

**Closed by Alexey-Yakovenko** 2019-12-28 12:05 UTC
