### ISSUE TITLE
ID3v2 tags don't load from WAV files

### ISSUE THREAD

**Issue by usr-mary** [DeaDBeeF-Player/deadbeef#3144] opened 2024-11-29 01:28 UTC
When I load my music library, the metadata is always gone. It annoys me sometimes, since I wanna know some information about the recording I'm listening to, and there is just no metadata, so I always have to open another application to see it.

When this happens on another players, such as Musicolet (the one I use in my phone), I just do a re-scan to my library and done, but here's not the case.

I also wondered if there may be a conflict between a plugin, but it doesn't seems to be the case.

### Information about the software:
Deadbeef version: 1.9.2
OS: EndeavourOS

![image](https://github.com/user-attachments/assets/13713550-7b0a-45ff-b268-e799dd9a8e0c)

**Comment by ts1a** [comment] 2024-11-29 01:50
I'm having this problem too. Are your files using ID3 tags? I noticed deadbeef sometimes don't read ID3v2.4 tags. Converting them to ID3v2.3 solves the problem.

**Comment by usr-mary** [comment] 2024-11-29 06:59
I only use three types of tags: FLAC, ID3v2.3 and RIFF ID3v2.3.

For some reason, only FLAC and RIFF ID3v2.3 load the metadata correctly.
![image](https://github.com/user-attachments/assets/6cd5a198-2e09-4144-915f-07fe907545ad)
![image](https://github.com/user-attachments/assets/c56e275a-a4b9-40aa-975c-0a529a0e7e22)

**Comment by Oleksiy-Yakovenko** [comment] 2024-11-29 07:05
Hi,

Please consider trying latest release - since if this was a known issue after 1.9.2 was released, potentially it got fixed later.
If this doesn't help -- please provide screenshots of track properties dialog of both tabs in any of the files where the tags are not loading.

**Comment by Oleksiy-Yakovenko** [comment] 2024-11-29 07:09
Also I don't know what is "RIFF ID3v2.3" -- this doesn't seem to be anything that my code is doing. It may indicate that you're using some non-default decoder plugin for those files. Like FFMPEG instead of MP3 plugin, or something similar.

**Comment by Oleksiy-Yakovenko** [comment] 2024-11-29 07:14
Just FYI: there were at least 3 important bug fixes in 2022 and 2023, related to ID3v2 loading, that may affect the issue you are seeing.

**Comment by usr-mary** [comment] 2024-11-29 21:43
I have upgraded to 1.9.6, resetting all installed plugins (all of which are the plugins included in my installation, except the Discord RPC one) to their defaults and the error still occurs on exactly the same files.

Here's the metadata tab of one file.
![image](https://github.com/user-attachments/assets/35048252-024c-4b45-8c79-5380f457df51)

Here's the properties tab of the same file.
![image](https://github.com/user-attachments/assets/81cb07c7-1b6b-42fc-b61e-4f541c8731d2)

**Comment by Oleksiy-Yakovenko** [comment] 2024-11-29 21:52
A that's a wav file. Got it. I'll check it out.

**Comment by Oleksiy-Yakovenko** [comment] 2024-11-30 09:47
I checked.. deadbeef relies on the libsndfile to handle this file type (including tags), and from what I understand -- libsndfile doesn't think that ID3v2 tag in a WAV file is a thing.
Can you share which tool did you use to add those tags into those files, and preferrable also which parameters/settings did you use? I would need to re-create such files to be able to figure out whether it's a valid scenario, and how to support it properly.

**Comment by Oleksiy-Yakovenko** [comment] 2024-12-03 20:27
There's actually a duplicate of this issue - #1201, and it has more details (seems like I did some investigation back in 2015).
Therefore closing this.

**Closed by Oleksiy-Yakovenko** 2024-12-03 20:27 UTC
Labels: Enhancement
