### ISSUE TITLE
On Cinnamon, enabling "hide to tray" settings and alike (especially the Close to tray), DeaDBeeF doesn't minimize to the Xapp status tray

### ISSUE THREAD

**Issue by ThoriumTextile** [DeaDBeeF-Player/deadbeef#2500] opened 2021-01-16 15:20 UTC
### Steps to reproduce the problem
Go to Settings > GUI > Select any of the 3 first options in the first tab
### What's going on? Describe the problem in as much detail as possible.
Deadbeef should show up in the XApp system tray. It doesn't yet minimizes anyway, making it so that it can only be re-opened through the Cinnamon Menu
### Information about the software:

Deadbeef version: deadbeef 1.8.4-1
OS: Linux CinnArtix 5.10.6-artix1-1 #1 SMP PREEMPT x86_64 GNU/Linux
DE: Cinnamon 4.8.6

**Comment by ThoriumTextile** [comment] 2021-01-16 15:21
Of note: it doesn't show up in the player menu of Pulseaudio either.

**Comment by Alexey-Yakovenko** [comment] 2021-01-16 15:24
duplicate of #1606

**Closed by Alexey-Yakovenko** 2021-01-16 15:24 UTC

**Comment by Alexey-Yakovenko** [comment] 2021-01-16 15:26
Long story short: new desktop environments don't support the X11 tray anymore, and didn't support it for quite some time.
Deadbeef doesn't support the new status notification systems, used by the new desktop environments, mainly because there's no good universally compatible, documented and appropriately licensed libraries to implement such functionality.

**Comment by saaj** [comment] 2025-05-27 20:26
I've got to the same trap (of digging into system tray implementations' (pro|re)gression in different DEs from some of the issues here) on Linux Mint 22, as I did on 20. But at least then I found https://github.com/DeaDBeeF-Player/deadbeef/issues/1208#issuecomment-626381922 quicker ;-) 

To a future digger into the topic: mind Cinnamon Sound applet's *Hide system tray icons for compatible players*. To clarify, on Linux Mint 22.1 Cinnamon 6.4.8 DeadBeef's tray icon works just fine (with the checkbox unchecked). But because there's [MPRIS integration plugin][1] you probably don't need it anyway. Note, that if you don't use MPRIS and want to have the system tray icon, you still need to uncheck the checkbox.

![Image](https://github.com/user-attachments/assets/7c99e6bb-9618-4d2e-8751-1f09c34eceb0)

![Image](https://github.com/user-attachments/assets/73b89cf1-4cd0-4316-b59f-bfe6e9494df4)

[1]: https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin
