### ISSUE TITLE
Playback stops in some tracks randomly

### ISSUE THREAD

**Issue by rootsandculture** [DeaDBeeF-Player/deadbeef#2625] opened 2021-07-02 04:08 UTC
The player stops randomly in some playlist tracks. Its weird cause it happens in different tracks (I have not selected "stop after current track of course). 
Tried several configurations and nothing seems to fix it. It happens in a fresh install too. 

In the terminal appers this error, is something related?
`(deadbeef:5606): Gtk-CRITICAL **: 01:06:55.346: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
connecting button tray signals`

Deadbeef version: 1.8.7
OS: Fedora 34

**Comment by Alexey-Yakovenko** [comment] 2021-07-03 10:26
The error in terminal is not relevant to your problem.

Could you please describe the behavior in more details?

Does playback get stopped or paused?
Do you have any additional plugins installed?
Does it happen with some specific tracks / the same place in the tracks, or completely random?
Does switching between pulse / alsa output help in any way?

With the amount of information you provided -- it's really impossible to find out what's going on.

**Comment by rootsandculture** [comment] 2021-07-03 14:18
`Do you have any additional plugins installed?`
No

`Does it happen with some specific tracks / the same place in the tracks, or completely random?`
Completly random

`Does switching between pulse / alsa output help in any way?`
Seems to be the problem! I switched to PulseAudio while its hangs and automaticaly started playing. I'll test it with this config.

BTW is the a way to see more info launching from terminal in verbose mode or something? I tried deadbeef -v but shows basic info.

Thanks

**Comment by kpcee** [comment] 2021-07-06 07:43
I had the same problem for months, playback stopped randomly on start playing next track - in the playlist, the play icon changed to three dots. But for me the problem has now completely disappeared. Either because I now use ALSA as output device or because of updates, the last pulseaudio update was at the end of March and I can't remember having such an incident again.

**Comment by rootsandculture** [comment] 2021-07-06 15:12
Finally shitched to Pulseaudio in Output plugin and didn't noticed any issues

**Comment by Alexey-Yakovenko** [comment] 2021-07-06 19:41
Ok it seems like the problem is resolved for now, and without further information about how and why it happens -- there's not much I can do. Closing until further information is provided.

**Closed by Alexey-Yakovenko** 2021-07-06 19:41 UTC
Labels: Triage
