### ISSUE TITLE
Crash when playing any file after updating to 1.8.2

### ISSUE THREAD

**Issue by Kzer-Za** [DeaDBeeF-Player/deadbeef#2221] opened 2019-09-21 17:06 UTC
Previously in Manjaro repositories only 0.7.2 version of DeadBeef was available. Today an update to 1.8.2 became available. After updating DeadBeef crashes when trying to play any file.

### Steps to reproduce the problem

Play any file.

### What's going on? Describe the problem in as much detail as possible.

DeadBeef crashes with messages like this:

```
(deadbeef:17087): Gtk-WARNING **: 19:54:39.668: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

(deadbeef:17087): Gtk-WARNING **: 19:54:39.669: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

(deadbeef:17087): Gtk-WARNING **: 19:54:39.669: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
Segmentation Fault

(deadbeef:17087): Gtk-WARNING **: 19:54:39.670: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
**
Gtk:ERROR:gtktextbtree.c:4703:get_last_line: assertion failed: (n_lines >= 1)
Bail out! Gtk:ERROR:gtktextbtree.c:4703:get_last_line: assertion failed: (n_lines >= 1)
backtrace() returned 13 addresses
Segmentation Fault

(deadbeef:17087): Gtk-WARNING **: 19:54:39.670: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

(deadbeef:17087): Gtk-WARNING **: 19:54:39.671: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
deadbeef(+0x13aaf) [0x43eaaf]
linux-gate.so.1(__kernel_sigreturn+0) [0xb7f8ad44]
/usr/lib/libgtk-x11-2.0.so.0(+0x1b86e9) [0xb739e6e9]
/usr/lib/libgtk-x11-2.0.so.0(+0x1c1f44) [0xb73a7f44]
/usr/lib/libgobject-2.0.so.0(g_closure_invoke+0xc6) [0xb6d0fe26]
/usr/lib/libgobject-2.0.so.0(+0x1fe11) [0xb6cf7e11]
/usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0xf1b) [0xb6cff8bb]
/usr/lib/libgobject-2.0.so.0(g_signal_emit+0x35) [0xb6d00625]
/usr/lib/libgtk-x11-2.0.so.0(+0x1bc3b5) [0xb73a23b5]
/usr/lib/deadbeef/ddb_infobar_gtk2.so(update_lyrics_view+0x87) [0xb5124dd7]
/usr/lib/deadbeef/ddb_infobar_gtk2.so(+0x3925) [0xb5123925]
/usr/lib/libpthread.so.0(+0x85b8) [0xb7e235b8]
/usr/lib/libc.so.6(clone+0x6a) [0xb7d6054a]
zsh: abort (core dumped)  deadbeef
```

### Information about the software:

Deadbeef version: 1.8.2
OS: Linux (Manjaro), 4.19.74-1

**Comment by Alexey-Yakovenko** [comment] 2019-09-26 05:42
duplicate of #2112

**Closed by Alexey-Yakovenko** 2019-09-26 05:42 UTC
Labels: Duplicate
