### ISSUE TITLE
Bug with sorting tracks by number after adding some folders

### ISSUE THREAD

**Issue by TotalCaesar659** [DeaDBeeF-Player/deadbeef#1971] opened 2018-02-12 15:45 UTC
### Steps to reproduce the problem

After adding some folders with track to playlist, tracks are sorting by numbers with bug: 01, **10, 11,** ..., 02, 03, and to 09.
![1](https://user-images.githubusercontent.com/14265316/36105058-b98952c4-1024-11e8-930f-648e5edca50e.png)

### What's going on? Describe the problem in as much detail as possible.

This bugs appears on folders with F1 2010 and F1 2011 OST. I've tried to find a reason and tested many other folders with tracks, but I didn't.

### Information about the software:

Deadbeef version: devel
OS: Lubuntu 16.04.3

**Comment by Alexey-Yakovenko** [comment] 2018-02-12 15:47
duplicate of #1560

**Closed by Alexey-Yakovenko** 2018-02-12 15:47 UTC
Labels: duplicate

**Comment by TotalCaesar659** [comment] 2018-02-12 15:51
Oh, sorry, didn't know about that.
