### ISSUE TITLE
Add option to disable "softvol" in ALSA plugin

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#1908] opened 2017-10-08 15:56 UTC
I'm trying to get the most raw and unprocessed sound out of ALSA. I already put ALSA in exclusive mode by using the "Front Speakers" option, and disable resampling in the ALSA plugin options. I'm sure this is the same as running aplay with the "--disable-resampler" option.

Could you add a option in the ALSA plugin to disable software volume control (--disable-softvol)? I prefer to control my volume by hardware, rather than software, to reduce any sort of sound processing software may be doing to the output.

Deadbeef version: Git Master as of October 7th
OS: Arch Linux 64bit

**Comment by Alexey-Yakovenko** [comment] 2017-10-08 16:00
duplicate of #515

**Closed by Alexey-Yakovenko** 2017-10-08 16:00 UTC
Labels: duplicate

**Comment by Alexey-Yakovenko** [comment] 2017-10-08 16:01
Disabling is simple -- just put the volume on 100% (there's no processing at all when volume is set to 100%), and edit the UI layout to remove the volume control widget, if that's what you want. You're welcome.

**Comment by shoober420** [comment] 2017-10-08 16:14
Ok awesome, thank you.

**Comment by arigit** [comment] 2018-09-15 15:54
I understand this issue has been closed and that there is a workaround / explanation (setting volume to 100) but still wanted to add - it would be nice to have a setting to disable volume control as part of the ALSA plugin, to make it evident that you are NOT getting ANY distortion introduced due to Volume (i.e. one pre-requisite to bit-perfect audio) - and either ignore or grey-out the volume widget setting

If I hadn't landed in this discussion, I wouldn't have any certainty on whether the audio setting was distorting volume or not. Unless I read the code. 

Further, some volume controls in linux allow going beyond 100% (e.g. pavucontrol) and deadbeef's doesn't show the % number that is set (at least the  "headerbar controls" that I use in gtk3), so users can't be totally sure when setting the volume to the max value whether they are introducing distortion or not. Unless they research and land here.

**Comment by cmpute** [comment] 2021-01-22 02:22
> Disabling is simple -- just put the volume on 100% (there's no processing at all when volume is set to 100%), and edit the UI layout to remove the volume control widget, if that's what you want. You're welcome.

@Alexey-Yakovenko  There's a little problem with the volume bar. I turn it to max volume when its size is small, but then I turned the volume bar larger in design mode and just to found that the volume is still not max. Is there a button that instantly turned the volume to max?
