### ISSUE TITLE
search filter mode

### ISSUE THREAD

**Issue by poedyatel** [DeaDBeeF-Player/deadbeef#2923] opened 2023-02-19 10:36 UTC
Please add a mode in which the search will filter the playlist and leave only tracks that have the requested entry in any of the tags or name, as is done by clementine.
This is a very handy tool for some specific sorting tasks, for example, I want to see all the variants of a single song in a large collection at once, or I'm looking for remixes. And in general, such a search is more effective
In fact, I don't use the current search at all, too often it doesn't allow me to find what I want, because I may not remember the exact name of the song, I remember some word, not always the first one, or I remember the artist. I enter the word that I remember, I get to a completely different song where there is also such a word. I introduce an artist, I get either on another song, or even on a cover.
For example, I was looking for the song rammstein of the band of the same name, and I wrote it, I received the following answer:
![изображение](https://user-images.githubusercontent.com/114159416/219942347-4bf84a68-929d-4917-a56e-22a60dcd8fdb.png)

Clementine filters the list and I see what I need:
![изображение](https://user-images.githubusercontent.com/114159416/219942458-a2b9a210-b604-4bfc-802d-14247a48bf62.png)

**Comment by Oleksiy-Yakovenko** [comment] 2023-02-19 10:41
Duplicate of #520

**Closed by Oleksiy-Yakovenko** 2023-02-19 10:41 UTC
Labels: Duplicate
