### ISSUE TITLE
The playback order of tracknumber does not correct.

### ISSUE THREAD

**Issue by laichiaheng** [DeaDBeeF-Player/deadbeef#2216] opened 2019-09-16 07:29 UTC
### Steps to reproduce the problem
My custom playback order:
`%album artist% %album% %discnumber% %tracknumber%`
### What's going on? Describe the problem in as much detail as possible.
When the track number is in 3 digit, the order is incorrect.
![2019-09-16 15-27-02 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/64940526-c39c3880-d896-11e9-85a3-db4454273b70.png)

### Information about the software:

Deadbeef version: deadbeef-git
OS: Manjaro

**Comment by Alexey-Yakovenko** [comment] 2019-09-16 08:08
I'm not sure how to solve that.
I think you need to pad numbers with 0s manually.
For example using `$pad(%track number%,5,0)`, although this is not yet supported or merged, but a pull request that does this is in review.

**Comment by Alexey-Yakovenko** [comment] 2019-09-16 08:10
In any case, what you're seeing is still not a bug, and works as designed.
Numbers within strings are treated literally, there's nothing special about them.

**Closed by Alexey-Yakovenko** 2019-09-16 08:10 UTC
Labels: Invalid

**Comment by laichiaheng** [comment] 2019-09-16 08:33
The result of `$pad(%track number%,5,0)` causes a different fault result
1,10-19,2,20-29...
![2019-09-16 16-31-32 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/64943947-a61f9c80-d89f-11e9-840f-55e6f480878d.png)
