### ISSUE TITLE
Look for album art image that matchs audio file name

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [DeaDBeeF-Player/deadbeef#559] opened 2015-03-12 22:10 UTC
Original [issue 657](https://code.google.com/p/ddb/issues/detail?id=657) created by Alexey-Yakovenko on 2012-04-19T11:50:32.000Z:

submitted by: nobody
Date: 2010-10-16 19:52:02

OS: Ubuntu 10.10, DeadBeef 0.4.2

When DeadBeef search for an album art image, can it first search for image file that match the audio file name?
If loading
    abc.flac &amp; abc.cue
then
    try load abc.jpg
else
    ....

This way, a series of album that each have their own unique album art can live in the same folder
Thank you very much.

**Comment by mallniya** [comment] 2022-02-21 20:25
https://github.com/DeaDBeeF-Player/deadbeef/issues/1131 supersedes this issue if we consider filename as file's metadata.

**Comment by Alexey-Yakovenko** [comment] 2022-02-21 20:27
agreed
duplicate of #1131

**Closed as completed by Alexey-Yakovenko** 2022-02-21 20:27 UTC
Labels: Duplicate
