### ISSUE TITLE
DB Radio Stream @ 1411kbs Flac

### ISSUE THREAD

**Issue by zorefilamrak** [DeaDBeeF-Player/deadbeef#2053] opened 2018-10-09 14:01 UTC
First of all DB 0.7.2 via ALSA, Jack or PulseAudio/Jack sink on AVLinux for audio playback attains one of the highest levels of audio playback for wav, flac etc that I've ever heard.

HighRes radio streams from this site (http://radiobit.50webs.com/) has one issue which is that DB 0.7.2 cannot stream 1411 flac streams which is CD quality uncompressed streaming.

I would be most grateful if DB could be made to handle 1411 flac radio streams.

Apologies if I'm on the wrong site to make such a request and thanks for such a great audio player that is a perfect partner to AVLinux high resolution audio playback capabilities.

**Comment by Alexey-Yakovenko** [comment] 2018-10-09 14:03
duplicate of #1122, deadbeef doesn't support streaming FLAC (yet).

**Closed by Alexey-Yakovenko** 2018-10-09 14:03 UTC
Labels: duplicate
