### ISSUE TITLE
Get rid of Registry Dialog at startup

### ISSUE THREAD

**Issue by erm3nda** [DeaDBeeF-Player/deadbeef#2272] opened 2019-12-01 10:05 UTC
### Steps to reproduce the problem
Open deadbeef player

### What's going on? Describe the problem in as much detail as possible.
Annying box popup that i cannot get rid of.

### Information about the software:
Deadbeef version: deadbeef 1.8.2 (AUR repo)
OS: Linux Manjaro Gnome Edition

**Comment by Alexey-Yakovenko** [comment] 2019-12-01 11:01
what kind of box? how does it look? can you provide a screenshot?

**Comment by erm3nda** [comment] 2019-12-04 10:55
Ok, let me explain a bit more.

what kind of box? 

A Dialog kind of box.

 how does it look? 

Looks exactly like if you go to menu bar and choose "View" -> "Registry", that's why i called it Registry dialog.

can you provide a screenshot?

Of course -> https://postimg.cc/JDCZqhTp/cf656b2e

A little explanation: I know that this box doesn't show up when "there's no error to show". This may explain why i do know about it, but you don't. But, it shows that dialog since i used it, and got really annoyed by it. I had to go to the offending and non working plugin and remove it to get rid of. 
What I really wanted when posting here, was to find a way to "hide" this dialog, while retaining the info when i do manually open it, in order to fix it when I have time for. Because i cannot get rid of yet , I simple deleted the offending plugin (vfs_zip).

Regards.

**Comment by Alexey-Yakovenko** [comment] 2019-12-04 11:31
It's a duplicate of another issue: #2193

**Closed** 2019-12-04 11:31 UTC
Labels: Duplicate
