### ISSUE TITLE
Add additional warning during track removing

### ISSUE THREAD

**Issue by RazrFalcon** [DeaDBeeF-Player/deadbeef#1975] opened 2018-02-16 13:04 UTC
Add a notice, that removing a track from an 'image' album (flac+cue) will lead to the whole image removal.

### Information about the software:

Deadbeef version: 0.7.2-r2
OS: Gentoo Linux

**Comment by mallniya** [comment] 2022-02-22 20:25
Duplicate of https://github.com/DeaDBeeF-Player/deadbeef/issues/1611

**Closed** 2022-02-22 20:49 UTC
Labels: Duplicate
