### ISSUE TITLE
Incorrect sorting

### ISSUE THREAD

**Issue by rvs38** [DeaDBeeF-Player/deadbeef#1866] opened 2017-08-28 15:47 UTC
Explanations in the screenshot. Look at right column: track numbers 9.10.100-109.11.110-etc
https://0x0.st/5LH.png

Deadbeef version: devel with last git 97ffd13
OS: Debian unstable

**Comment by Alexey-Yakovenko** [comment] 2017-08-28 15:50
Deadbeef doesn't sort by track numbers when adding files to playlist. Clicking on column headers should help you.

I suppose it's a duplicate of #1560, #1142, etc.

**Closed by Alexey-Yakovenko** 2017-08-28 15:50 UTC
Labels: duplicate
