### ISSUE TITLE
Latest Windows release, not playing from GUI

### ISSUE THREAD

**Issue by nikkoman** [DeaDBeeF-Player/deadbeef#2947] opened 2023-05-10 10:47 UTC
Deadbeef version: 1.9.5
OS: Windows 10 Pro 22H2

I'm having trouble opening files from windows explorer. Instead, dragging each file works fine.

When opening with DeaDBeeF, I get:

starting deadbeef 1.9.5 [static] [portable]
WinSock init ok, library version 2.2
server_start
searching for GUI plugins in C:\Users\Nicholas/AppData/Roaming/deadbeef/plugins64
searching for GUI plugins in C:\Users\Nicholas/AppData/Roaming/deadbeef/plugins
load_plugin_dir C:\Users\Nicholas/AppData/Roaming/deadbeef/plugins: scandir found 0 files
searching for GUI plugins in C:/PROGRA~1/DeaDBeeF/plugins
load_plugin_dir C:/PROGRA~1/DeaDBeeF/plugins: scandir found 38 files
found gui plugin ddb_gui_GTK2.dll
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.dll
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_gui_GTK3.dll
loading plugins from C:\Users\Nicholas/AppData/Roaming/deadbeef/plugins64
loading plugins from C:\Users\Nicholas/AppData/Roaming/deadbeef/plugins
load_plugin_dir C:\Users\Nicholas/AppData/Roaming/deadbeef/plugins: scandir found 0 files
loading plugins from C:/PROGRA~1/DeaDBeeF/plugins
load_plugin_dir C:/PROGRA~1/DeaDBeeF/plugins: scandir found 38 files
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/aac.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/adplug.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/alac.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/artwork.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/dca.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_dsp_libretro.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_dumb.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_mono2stereo.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_shn.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/dsp_libsrc.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ffap.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/flac.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/hotkeys.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/lastfm.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/m3u.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/mp3.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/musepack.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/nullout.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/opus.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/pltbrowser_gtk2.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/pltbrowser_gtk3.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/portaudio.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/psf.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/rg_scanner.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/shellexec.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/shellexecui_gtk2.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/shellexecui_gtk3.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/sndfile.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/supereq.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/tta.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/vfs_curl.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/vfs_zip.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/vorbis.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/wavpack.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/wma.dll
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin Album Artwork
starting plugin dts decoder
starting plugin Resampler (Libretro)
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Hotkey manager
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin Null output plugin
starting plugin Opus player
starting plugin Playlist Browser
starting plugin Playlist Browser
starting plugin PortAudio output plugin
starting plugin PSF player using Audio Overload SDK
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec UI
starting plugin Shellexec UI
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin WavPack decoder
starting plugin WMA player
starting plugin stdio vfs
selected output plugin: PortAudio output plugin
resume: track -1 pos -1.000000 playlist -1
selected output plugin: PortAudio output plugin
failed to add file or folder C:/Program Files/DeaDBeeF

**Comment by nikkoman** [comment] 2023-05-10 12:41
Apparently it has to do with Greek characters in the directories. Also special characters cause this.

**Comment by Oleksiy-Yakovenko** [comment] 2023-05-10 14:52
duplicate of #2717

**Closed by Oleksiy-Yakovenko** 2023-05-10 14:52 UTC
Labels: Duplicate, Windows
