### ISSUE TITLE
Question/Request - Playlist Tab Layouts?

### ISSUE THREAD

**Issue by 0pLuS0** [DeaDBeeF-Player/deadbeef#2208] opened 2019-09-07 00:48 UTC
### Steps to reproduce the problem
Use Album Art then create a Radio playlist to listen to a online radio station!

### What's going on? Describe the problem in as much detail as possible.
If you use Album Art in deadbeef, then create a new playlist tab as an example and play a online radio station from a playlist .pls or .m3u deadbeef will create in the ~/.cache/deadbeef/covers directories and try and create cover art images for the radio stations.

### Information about the software:

Deadbeef version: Any
OS: Linux

1. Is it possible to have different playlists with different layouts? If this is possible then I'd like to be able to create several radio playlists without an 'Album Art' section since this is pointless, and the problem it creates as I've mentioned above.

2. If this is not possible to do, it would be nice if deadbeef can be coded/created, so that various Playlist Tabs can have different layouts!

THANKS

**Comment by Alexey-Yakovenko** [comment] 2019-10-22 18:38
duplicate of #1931

**Closed by Alexey-Yakovenko** 2019-10-22 18:38 UTC
