### ISSUE TITLE
The linked AAC file doesn't play

### ISSUE THREAD

**Issue by fulalas** [DeaDBeeF-Player/deadbeef#2596] opened 2021-05-03 10:52 UTC
This aac sample throws a floating point exception, while Mpv and Audacious open it normally: https://www.mediafire.com/file/93jd1sirx5ym1a1/11.-Return+of+the+King.aac

**Comment by Alexey-Yakovenko** [comment] 2021-05-16 20:16
duplicate of #2148

**Comment by Alexey-Yakovenko** [comment] 2021-05-16 20:19
The file doesn't cause a crash, but doesn't play either, therefore reopening to investigate.

**Closed** 2021-07-06 20:01 UTC
Labels: Triage
