### ISSUE TITLE
Crash after a random number of songs have been played

### ISSUE THREAD

**Issue by thecookie94** [DeaDBeeF-Player/deadbeef#2928] opened 2023-03-02 15:22 UTC
### Steps to reproduce the problem

Start playing, leave it playing for hours on end till it sigabrts. alternatively just start playing and hold down the next song key for a couple seconds to minutes.

### What's going on? Describe the problem in as much detail as possible.

Deadbeef crashes after playing for a while, as described in the reproduction steps. Probably related to the mpris2 plugin, not quite sure. Stacktrace is attached below

### Information about the software:

Deadbeef 1.9.5, mpris2 plugin tag 1.16; sigabrt happens with both the static official build and `deadbeef` from the AUR
OS: archlinux, updated today. testing repos NOT enabled

[deadbeef_sigabrt.txt](https://github.com/DeaDBeeF-Player/deadbeef/files/10872748/deadbeef_sigabrt.txt)

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-02 17:22
According to the crash log, it seems that mpris plugin is crashing, when trying to send a non-utf8 string via dbus.
This may indicate a bug in deadbeef itself, or a bug in MPRIS plugin, but either way it would be fairly difficult to fix it without having a specific file which causes a crash.
Would it be possible for you to find the specific track which causes this crash?

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-02 17:26
(It's quite possible that non-utf8 string is coming from the file path or file name)

**Comment by thecookie94** [comment] 2023-03-02 18:03
@Oleksiy-Yakovenko Sounds quite likely, yes. The weird part about it is that it seems to only happen with SOME files containing non utf8 characters in their filenames or tags (paths are utf8 only), even when we're talking about the same exact character and tag format only some are affected by the looks of it.  I'll need to pay attention as for what specific file(s) it tries to play the next time it blows up in my face, which might take a while with a playlist containing >1000 files. Thanks for now, will update once I have more information on hand

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-02 18:23
hmm ok can you check whether there are any weird file names in artwork cache?
`~/.cache/deadbeef/artwork2` or something like that

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-02 18:54
Another potential root cause: mpris plugin uses a buffer of 500 bytes to store a string constructed from track metadata.
This 500 bytes buffer is used for storing Comment field as well, which often exceed the size of 500 bytes, and this may cause the string to be cut in the middle of a utf8 character, which may cause this problem. I'll investigate.

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-02 19:48
I investigated and made an additional unit test for that scenario, and didn't find anything -- the (suspected) code on deadbeef side is working as it should.
The next step would be to modify the mpris plugin and add a few extra checks...
Basically, the same checks as the failing assert:
```
(g_utf8_validate (v, -1, &end) && (end == v + len))
```

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-02 19:59
I have made a new build with extra string validation:
https://github.com/DeaDBeeF-Player/deadbeef-mpris2-plugin/suites/11316064801/artifacts/581066703
Could you please try it? Preferrably with logging enabled.

**Comment by thecookie94** [comment] 2023-03-02 20:18
Will do

**Comment by Oleksiy-Yakovenko** [comment] 2023-05-06 09:35
Closing -- should be fixed, but no confirmation from reporter.

**Closed by Oleksiy-Yakovenko** 2023-05-06 09:35 UTC
Labels: Bug
