### ISSUE TITLE
Dash AAC songs won't play

### ISSUE THREAD

**Issue by C0rn3j** [DeaDBeeF-Player/deadbeef#2189] opened 2019-08-15 09:35 UTC
Using deadbeef-git `r8538.878c0f936` on Arch Linux

```
ERROR: could not load: /mnt/3tbRED/Nextcloud2/Public/test.aac
failed to add file or folder /mnt/3tbRED/Nextcloud2/Public/test.aac
ERROR: could not load: /mnt/3tbRED/Nextcloud2/Public/test.aac
plt_load: failed to open file:///mnt/3tbRED/Nextcloud2/Public/test.aac
```

TMB also can't play this file: https://github.com/Taiko2k/TauonMusicBox/issues/162, MPV can play the file correctly.

https://cloud.rys.pw/s/KX8yxjSHYwxJfy5

**Comment by Alexey-Yakovenko** [comment] 2021-11-12 20:51
Sorry, at first I thought it was a bug in my aac/mp4 parser, but then realized that dash is a different spec and it's indeed not supported, and is more of an enhancement.

**Comment by Alexey-Yakovenko** [comment] 2021-11-12 20:54
Also it seems to be a duplicate or related to #1663

**Comment by Alexey-Yakovenko** [comment] 2021-11-12 20:56
Yes, it's definitely the same issue, same sidx atom which is ignored / unsupported.
Closing as duplicate of #1663

**Closed by Alexey-Yakovenko** 2021-11-12 20:56 UTC
Labels: Duplicate
