### ISSUE TITLE
Command to undo sorting or add "unsorted"

### ISSUE THREAD

**Issue by lesliev** [DeaDBeeF-Player/deadbeef#2244] opened 2019-10-20 21:45 UTC
Feature request: could there be some way to undo an accidental playlist sort? Or a way to go back to "unsorted"? Or a playlist autosave with a 2-action history? I slowly but surely sort my list into something great and then one accidental slip and it's all back to square one. The current best workaround is to save the playlist and load it back again, but then that doesn't include a bunch of songs I've dragged in there since, and I don't often remember to save the current view.

### Steps to reproduce the problem
Double-click on one of the column headers.

### What's going on? Describe the problem in as much detail as possible.
The playlist gets sorted and there doesn't seem to be any way to go back to how it was.

### Information about the software:
Deadbeef version: 0.7.2
OS: Ubuntu 18.04

PS: thanks for this awesome software!!

**Comment by Alexey-Yakovenko** [comment] 2019-10-21 05:28
duplicate of #490

**Closed by Alexey-Yakovenko** 2019-10-21 05:28 UTC
