### ISSUE TITLE
Playback does not stop after reaching the end of the last track in the playlist

### ISSUE THREAD

**Issue by Soukyuu** [DeaDBeeF-Player/deadbeef#1733] opened 2017-03-23 19:37 UTC
Running current git master, audio format doesn't seem to matter (noticed with flac, also happens with wavpack and vorbis).

After finishing playing the last track in the playlist, deadbeef doesn't seem to actually stop playback. The CPU usage spikes to ~64% (on a tri-core, so 100% on one core), then there is a notification pop-up shown for the last track again after about 2 seconds, as if it jumps to the beginning of the last track. 

The only plugins installed are waveform seekbar and playback order widget. I have tried removing them and the issue persists.

Console output is silent. CPU usage returns to normal once I press "stop". Was wondering why my PC kept spinning up the fans while idle.

**Comment by IvanDSM** [comment] 2017-03-25 22:40
I've also encountered this issue on git master. One side effect is that the last track in the playlist, due to it apparently "never ending", does not get scrobbled to last.fm/libre.fm/whatever.

**Comment by Soukyuu** [comment] 2017-03-26 12:38
Not sure if it's related, but I noticed that on automatic track transition, sometimes the notifications shows for the song that _just finished playing_ instead the one that starts playing...

**Comment by Alexey-Yakovenko** [comment] 2017-04-20 18:49
I can't reproduce this issue. Can someone please try the latest build?

**Comment by Alexey-Yakovenko** [comment] 2017-04-20 18:51
Closing for now. Will reopen if someone can repro.

**Comment by Soukyuu** [comment] 2017-05-09 20:45
Still happening here on a freshly checked out snapshot. I noticed that the CPU usage increases a few seconds before the end of the track, maybe some caching/preloading code problem?

**Comment by Alexey-Yakovenko** [comment] 2017-05-09 20:52
Will recheck again.

**Comment by Alexey-Yakovenko** [comment] 2017-11-17 13:25
This should be fixed.

**Closed by Alexey-Yakovenko** 2017-11-17 13:25 UTC
Labels: bug
