### ISSUE TITLE
[Feature request] mouse side buttons as hotkeys

### ISSUE THREAD

**Issue by Solarunit** [DeaDBeeF-Player/deadbeef#1989] opened 2018-03-25 00:52 UTC
Please add an option to assign mouse side buttons as hotkeys.
E.g. 
side_button_1 = Play\pause
side_button_2 + scrollweel = volume control

**Comment by Alexey-Yakovenko** [comment] 2018-03-27 11:36
duplicate of #525

**Closed by Alexey-Yakovenko** 2018-03-27 11:36 UTC
