### ISSUE TITLE
Album art not updating on different tracks of same album

### ISSUE THREAD

**Issue by TeaWhyDee** [DeaDBeeF-Player/deadbeef#2695] opened 2021-11-09 18:37 UTC
### Steps to reproduce the problem
Have 2 tracks with different album arts. Go to track properties and change their album to be 'test' for example. 
If you switch from one track to another, the album art won't update.

### What's going on? Describe the problem in as much detail as possible.
Different tracks in an album have different pictures. DeadBeeF Album Artwork plugin doesn't update the artwork if the cover art for the album of the track is already cached.

### Information about the software:
Deadbeef version: 1.8.8 (deadbeef-git r10404.97ef80f0b-1)
Album Artwork plugin version 1.3
OS:  Manjaro Linux x86_64

**Comment by Alexey-Yakovenko** [comment] 2021-11-09 18:46
Marking as enhancement, since this is technically not a bug, and this is just how it works in the linux version. The issue is expected to be resolved when the new album art plugin is finished and ported to linux.

**Comment by ryran** [comment] 2022-01-06 11:13
Could be closed as a duplicate of #2025 (which is probably a dupe of even older issues)

**Comment by Alexey-Yakovenko** [comment] 2022-01-06 13:47
duplicate of #1118

**Closed by Alexey-Yakovenko** 2022-01-06 13:47 UTC
Labels: Enhancement
