### ISSUE TITLE
Track properties: Option to select which tags fields are displayed

### ISSUE THREAD

**Issue by bcoolumbo** [DeaDBeeF-Player/deadbeef#2168] opened 2019-07-15 16:41 UTC
In foobar it is possible to select the standard tag fields, you can find it under Prferences -> Advanced -> Properties dialog -> Standard fields.
Looks like that: Artist Name=ARTIST;Track Title=TITLE;Album Title=ALBUM;Date=DATE;Genre=GENRE;Comment=COMMENT;Rating=RATING and so on. 
Fields not listed here are not displayed in track properties dialog.

Would be fine to have this in deadbeef too. I use "selection properties" in my deadbeef gui and the many unused fields (Composer, Album Artist, Total Tracks, Track Number, Disk Number, Total Discs) hide the important info and produce an otherwise needless scrollbar.

Deadbeef version: Devel, OS: Linux

**Comment by mallniya** [comment] 2022-02-22 20:31
Duplicate of https://github.com/DeaDBeeF-Player/deadbeef/issues/1164

**Closed** 2022-02-22 20:51 UTC
Labels: Enhancement
