### ISSUE TITLE
[MacOS] Columns lost between app sessions / playlist files are corrupt

### ISSUE THREAD

**Issue by Kautenja** [DeaDBeeF-Player/deadbeef#2403] opened 2020-06-18 23:52 UTC
### Steps to reproduce the problem

1. add columns to a playlist
2. restart deadbeef
3. observe playlist with no columns

### What's going on? Describe the problem in as much detail as possible.

I can add columns to a playlist fine, but when I restart the app, the columns are gone. I've tried saving playlists with configured columns and reloading the playlist when this occurs, but the app just crashes...

### Information about the software:

Deadbeef version: devel, literally right out of the box, no mods or plugins or whatever
OS: MacOS 10.15.2

**Comment by Alexey-Yakovenko** [comment] 2020-06-21 11:05
I can't reproduce this on 10.15.5, I'm trying to find a way to reproduce on 10.14.
It's quite unlikely that I will find someone running 10.15.2 specifically.

**Comment by Alexey-Yakovenko** [comment] 2020-07-13 06:10
Closing since there's nothing else I can do with the information you provided.
If you have any other information to share -- please do so.

**Closed by Alexey-Yakovenko** 2020-07-13 06:10 UTC
Labels: Triage
