### ISSUE TITLE
Sorting CD tracks

### ISSUE THREAD

**Issue by eblanca** [DeaDBeeF-Player/deadbeef#2060] opened 2018-10-28 15:08 UTC
### Steps to reproduce the problem
Let Caja (or an other file manager) launch deadbeef once an Audio CD has been inserted.
(or just run deadbeef with cmdline:
$ deadbeef /run/user/1000/gvfs/cdda:host=sr0
with an Audio CD present, with sr0 being the actual optical media device)

### What's going on? Describe the problem in as much detail as possible.
Tracks are sorted in alphabetical order and this should NOT be the case. So they appear as Track 1, Track 10, Track 11, Track 12, Track 2, Track 3, etc.
Due to "dirent_alphasort" in https://github.com/DeaDBeeF-Player/deadbeef/blob/master/playlist.c#L1141 and in https://github.com/DeaDBeeF-Player/deadbeef/blob/master/playlist.c#L1148 , the order is alphabetical. Though, I think this issue should be fixed at a higher level, when the string "cdda:" is detected coming from the command line and the resulting playlist may be well sorted.

### Information about the software:

Deadbeef version: git master branch built with any plugins enabled but gtk3 and ffmpeg.
OS: Linux Mint Debian Edition 3 (aka Cindy) 64 bit on intel i5-6200u

**Comment by Alexey-Yakovenko** [comment] 2018-10-29 14:31
basically a duplicate of #1560 and #1142

**Closed by Alexey-Yakovenko** 2018-10-29 14:31 UTC
Labels: duplicate

**Comment by Alexey-Yakovenko** [comment] 2018-10-29 14:34
I don't think it should be fixed by detecting cdda.. It's a general problem, that playlist is not sorted correctly after adding files. The same issue exists with regular files.
