### ISSUE TITLE
[Feature request] Add option to rescan playlist directories

### ISSUE THREAD

**Issue by gapf2010** [DeaDBeeF-Player/deadbeef#2592] opened 2021-04-26 02:45 UTC
### Steps to reproduce the problem
My playlist is composed of all the MP3 files inside a specific directory on my laptop, all classified in directories by artist, album name, etc. If I add several new albums, I have to remember them all and then add them all manually to deadbeef.

### What's going on? Describe the problem in as much detail as possible.
I'd like to have an option (or button or whatever) which would allow me to rescan all my playlist directories while adding the newly found MP3 files to the playlist, and deleting the non-existent ones. It would work like this (IMO):

- Get the names of all mp3 files inside the directories
- If the MP3 filename is already on the playlist, just skip it (no matter if its tags have changed or not, just look at the filename, to save time)
- If the MP3 filename is not on the playlist, add it (looking at its tags)
- If a filename on the playlist got deleted, remove it from the playlist
- Sort the playlist according to its current sorting order

Thanks!

**Comment by Alexey-Yakovenko** [comment] 2021-04-26 06:22
duplicate of #526

**Closed by Alexey-Yakovenko** 2021-04-26 06:22 UTC

**Comment by kpcee** [comment] 2021-05-02 09:20
You can use my [playlist manager plugin](https://github.com/kpcee/deadbeef-playlist-manager) for this. It can delete duplicate or deleted files from a playlist, but also synchronize playlists with a directory including subdirectories.
