### ISSUE TITLE
1.8.2 Doesn't Work with Infobar

### ISSUE THREAD

**Issue by 0pLuS0** [DeaDBeeF-Player/deadbeef#2206] opened 2019-09-03 06:57 UTC
### Steps to reproduce the problem
Run deadbeef 1.8.2
Install infobar

### What's going on? Describe the problem in as much detail as possible.
Sometimes when starting a song deadbeef crashes and it only says 'segfault' at a terminal, it's all I see at the terminal, no errors.

I'm attaching a screen shot, to show the song that is high lighted in blue when selected, if I go to different songs and click on them to start them this way, at some point deadbeef crashes.

If I disable the Infobar it never crashes.

I've had to revert back to 0.7.2 in order to use the Infobar.

It would really be great if we could get an update to this plugin to work with 1.8.2?

https://bitbucket.org/dsimbiriatin/deadbeef-infobar/wiki/Home

### Information about the software:

Deadbeef version: 1.8.2
OS: Slackware 14.2 x86_64
Infobar 1.4

THANKS

![infoplug_bio](https://user-images.githubusercontent.com/36190223/64150551-fe728b00-ce17-11e9-8a1f-c96a9773ccbe.jpg)

**Comment by Alexey-Yakovenko** [comment] 2019-09-03 07:26
duplicate of #2112

**Closed by Alexey-Yakovenko** 2019-09-03 07:26 UTC

**Comment by 0pLuS0** [comment] 2019-09-04 03:56
Ahh and it looks like no development either... 

Guess I'm sticking to deadbeed 0.7.2 then...

**Comment by 0pLuS0** [comment] 2019-09-04 04:57
@Alexey-Yakovenko

I take back what I said in that this does not work, that was not correct words.

1.8.2 and Infobar work as long as I click on the 'Play' button to play songs.

The screen shot, where it shows the song highlited in blue, if I click on the Title of the songs and try to play them this way instead of using the play button, at some point deadbeed crashes and this is the output I got back at the terminal;

Gtk:ERROR:gtktextview.c:3571:gtk_text_view_validate_onscreen: assertion failed: (text_view->onscreen_validated)

Maybe there is something that can be done so it can work when clicking on the title of the songs to play them?

THANKS

**Comment by Alexey-Yakovenko** [comment] 2019-09-04 05:16
Yeah please read the original bug report -- it has a link to infobar bugtracker, with the info what needs fixing.

**Comment by 0pLuS0** [comment] 2019-09-06 06:09
THANKS!

**Comment by 0pLuS0** [comment] 2021-06-14 01:13
@Alexey-Yakovenko 

Hi sorry to trouble you, I looked around your Github, but I didn't notice anything.

Has there been any new word for an inforbar - Lyrics/Bio plugin working yet for 1.8x deadbeef?

Thanks

**Comment by Alexey-Yakovenko** [comment] 2021-06-14 06:19
@0pLuS0 I haven't heard of any changes in this area

**Comment by 0pLuS0** [comment] 2021-07-12 06:07
Ok, so sad, I have to use 0.7.2 :(

**Comment by Alexey-Yakovenko** [comment] 2021-07-12 06:20
@0pLuS0 I never really used the infobar plugin. Also I'm not using Linux, like ever. Infobar is not really related to me or my interests in any way -- it's just a software that some other developer has created. I don't have to be fixing all software that you want, even if I can. I have other things to do, and they are seemingly more important to me, than spending time on something that I wouldn't even use myself.

You could say that it's my fault that this software doesn't work anymore, but it doesn't work because it was originally written in a wrong way, and it broke because I fixed a bug in the platform on which it is running, and it has to be updated by its developer, or the community.

**Comment by 0pLuS0** [comment] 2021-07-13 02:04
Ahhh, I assumed when deadbeef was originally released it was a Linux app, and developed it on Linux.

I never asked for you to fix all the software I wanted, I'm only asking about this is all, and I was hoping in time someone would pick it up.

Quite sad actually, this has never been picked up. Looking over all the apps out there, Bios & Lyrics seems like a common thing in media apps, if you notice the screen shot I posted above, deadbeef laid out like this looks really nice and quite functional too.

Thanks

**Comment by Alexey-Yakovenko** [comment] 2021-07-13 06:01
> Ahhh, I assumed when deadbeef was originally released it was a Linux app, and you developed it on Linux.

Yes, this is correct. But I fully moved to mac ~6 years ago or so.

> I never asked for you to fix all the software I wanted

I know, sorry. It was an exaggeration. I meant, that when you're asking me to fix Infobar - it's pretty much the same, as asking me to install Haiku and fix firefox on it. I don't really have any relation to it.

**Comment by 0pLuS0** [comment] 2021-07-13 23:34
So let me ask this one last question, and I'd even be willing to pay you something for your time.

If I'm willing to pay you, maybe then you'd consider doing this, and then it can be an Official Plugin from you.

Do you have the skills to code this to work? 

THANKS

**Comment by Alexey-Yakovenko** [comment] 2021-07-14 08:44
Sorry, but I have to say no -- I really have other priorities at this time.
You could try joining discord and asking there, maybe some of the linux devs/users would be interested.

**Comment by 0pLuS0** [comment] 2021-07-20 00:03
Ok, if you get the time later, I am willing to pay as I mentioned, I'd even pay $100-$200 USD.

**Comment by huglovefan** [comment] 2022-02-23 09:44
sorry for the spam, i'm just posting this here so any other plugin developers with free time and gtk knowledge can find it (i have only one of the two)

https://web.archive.org/web/20200622032032/https://bitbucket.org/dsimbiriatin/deadbeef-infobar/issues/38/infobar-causes-deadbeef-180-to-crash

> Alexey Yakovenko created an issue 2019-04-07:
>
> At first I thought it was some broken compatibility on my side, but turned out it's because it's using gdk_thread_enter/leave.
>
> Deadbeef no longer calls this code:
>
> ```
> g_thread_init (NULL);
> gdk_threads_init ();
> gdk_threads_enter ();
> ```
>
> This API is deprecated and caused many issues.
>
> So running gdk_thread_enter etc is no longer valid. To solve this problem, you need to convert your code to run UI stuff on the main thread using g_idle_add.

for a quick workaround, running deadbeef with `taskset -c 0 deadbeef` to restrict it to one core seems to make the crashes go away (not sure how foolproof this is)

**Comment by kpcee** [comment] 2022-02-23 18:25
Why don't you use the deadbeef-lyricbar plugin by Ignat Loskutov? The last commit is only 9 months ago, maybe the author would add the biography function for a donation. If Loskutov's plugin works without problems, it might even be much easier and faster to add the missing functionality there instead of adapting a old plugin to newer DeaDBeeF versions.

**Comment by 0pLuS0** [comment] 2022-03-29 04:44
@kpcee I did post an issue report last month, asking if he can fix the infobar plugin;

https://github.com/loskutov/deadbeef-lyricbar/issues/31

No reply yet...

**Comment by 0pLuS0** [comment] 2022-03-31 00:04
Hey everyone!

Just wanted to share, for those interested, @loskutov is working in updating deadbeef-infobar-ng;

https://github.com/loskutov/deadbeef-infobar-ng
