### ISSUE TITLE
Implementing Cmus UI on top of Deadbeef

### ISSUE THREAD

**Issue by Shellcat-Zero** [DeaDBeeF-Player/deadbeef#2040] opened 2018-08-12 11:40 UTC
I would like to submit a feature request to implement the [Cmus UI](https://github.com/cmus/cmus) on top of Deadbeef, for those of us who don't want to deal with X11 or GTK dependencies.

I would be willing to pay a $500 USD bounty for this feature.

**Comment by Alexey-Yakovenko** [comment] 2018-08-12 11:41
not quite what u need, but similar: https://github.com/kuba160/ddb_gui_prompt

**Comment by Shellcat-Zero** [comment] 2018-08-12 12:02
Very cool, thanks for the resource.

**Comment by Alexey-Yakovenko** [comment] 2018-08-12 18:00
duplicate of #572

**Closed by Alexey-Yakovenko** 2018-08-12 18:00 UTC
Labels: duplicate
