### ISSUE TITLE
Low Volume After Using Spotify

### ISSUE THREAD

**Issue by jasker5183** [DeaDBeeF-Player/deadbeef#3079] opened 2024-04-10 23:41 UTC
### Steps to reproduce the problem

1. Open Spotify (Flatpak) start playing a few tracks.
2. Open Deadbeef start playing a song.
3. Volume will be lower than it should be.
4. Click the File, Edit, View bar, or most of the time I have to go into Preferences.
5. Volume back to normal.

### What's going on? Describe the problem in as much detail as possible.

That's what I've been trying to figure out since version 1.9.6 came out and this issue started. It could be the Pipewire plugin as I've not been able to replicate this while on ALSA. After a while the problem cannot be replicated and I have to reboot in order for it to start doing it again. In my preferences I have the Pipewire output plugin, override sample rate and bit depth disabled, and Replay Gain (apply gain and prevent clipping according to peak).

Using the latest Master from Github also does not solve it.  

### Information about the software:

Deadbeef version: 1.9.6
OS: Fedora 39 (Gnome)

**Comment by saivert** [comment] 2024-04-12 16:31
Did you enable "Use PipeWire volume control" in the PipeWire plugin preferences?

Volume is handled differently depending on this option.

If Use PipeWire volume control is enabled then volume is handled as follows:
Internal Deadbeef volume is always max (100%, 0dB), volume is handled by Pipewire and the volume slider in Deadbeef is basically just a remote control for this volume setting.

If Use PipeWire volume control is disabled then volume is handled as follows:
Whenever plugin is initialized/playback is started it resets the Pipewire volume level for its stream to max volume (100%) and uses Deadbeef's internal volume handling.

This should explain why you notice volume is reset when you open the preferences dialog. This works as intended since the plugin is reloaded when this dialog is opened.

As for why the volume of Deadbeef is lowered in relation to using Spotify at the same time I have no idea. I cannot reproduce this myself.

I also use Fedora 39 with Gnome and a pretty standard Pipewire setup with no customizations.

**Comment by jasker5183** [comment] 2024-04-12 19:23
Usually I have my volume set to -12 to -10 DB.

> When this problem occurs -- can you see whether Deadbeef's own volume regulator changes in appearance? I.e. -- does the volume slider also looks like it has been set to lower volume, or it remains where it was set?

When the issue is happening the volume slider in Deadbeef remains where I set it.

> Also, when the problem occurs -- did you try to adjust the volume in Deadbeef? Like make the volume lower, than back to full? Does it work or it's still lowered, even when set to full volume in Deadbeef?

If I change the volume while it's doing it the volume does not change. I turned it up to 0 DB and went into preferences, temporary deafness and a ringing in my ears occurred.

> Did you enable "Use PipeWire volume control" in the PipeWire plugin preferences?

I did not have this enabled as the last time I played with it, it wanted to turn the system/master volume up and down. As in the Deadbeef and system volume where linked together, which didn't work for me. Now when I enable this option it does not seem to do that any more. I'm still playing around but after a few reboots and this option enabled the volume is what it is supposed to be.

> Do you run any audio processing software like EasyEffects?

I have it installed but leave the effects disabled until I need it, and the program needs to be open to do this which it is not.

> Can you open PulseAudio Volume control (or another mixer) and check if the slider here changes?

Sliders remain the same, I change the volume in Deadbeef from -12 to -10 pavucontrol still says -12.

**Comment by Oleksiy-Yakovenko** [comment] 2024-12-23 20:37
> When the issue is happening the volume slider in Deadbeef remains where I set it.

In this case, I can't see how this is a problem with deadbeef. Seems like Spotify changes system volume. Or some other pipewire bug. As you described, adjusting volume in deadbeef does nothing, but seems like opening preferences window will reset some pipewire state and make it change (which is weird in itself, but still seems like a bug outside of deadbeef's direct control. For this specific situation, as mentioned by Saivert, the pipewire plugin has an option to uncheck this "Use PipeWire volume control". Hope it helps. Closing.

**Closed by Oleksiy-Yakovenko** 2024-12-23 20:37 UTC
Labels: Bug
