### ISSUE TITLE
Freez when launching an certain url radio.

### ISSUE THREAD

**Issue by sushi2503** [DeaDBeeF-Player/deadbeef#2675] opened 2021-09-21 13:10 UTC
### Steps to reproduce the problem
Launch an url web radio @ : 

https://fr1.streamhosting.ch/lounge64.aac

### What's going on? Describe the problem in as much detail as possible.

If I try to listening to the url radio (see url above) it most of the time freezes the player and the only way to close Deadbeef is to force to close it (via panel icon) clicking the panel popup window (XFCE) which says "the program doesn't respond anymore would you like close it?". I have to relaunch Deadbeef and try again till it connect to the radio. They are no logs from Deadbeef nor from journalctl -f. I have also this warning by launching Deadbeef (without starting any file) :

(deadbeef:1358): GLib-CRITICAL **: 13:05:48.912: Source ID 19 was not found when attempting to remove it

### Information about the software:

Deadbeef version: 18.8
OS: Archlinux up to date.
Alsa only (no pulseaudio installed)

### Hardware info:

Internet connection rj45 speed 450 mb/s
Sound card RME HDSP 9632

**Comment by Alexey-Yakovenko** [comment] 2021-09-21 16:28
Could you try the latest build from master branch? I believe this has been fixed already:
https://sourceforge.net/projects/deadbeef/files/travis/linux/master/deadbeef-static_devel-1_x86_64.tar.bz2/download

**Comment by sushi2503** [comment] 2021-09-22 07:28
Thank you but the static version seems to be deadbeef-static_1.8.4-1_x86_64.tar.bz2 on your download page but my distro version is 18.8-2. In the version notes it says : "Fixed: A crash when reading certain AAC files". I'm a bit confused...
Then, I don't know if it's a good idea to install a static version along the distro version ?

**Comment by Alexey-Yakovenko** [comment] 2021-09-22 16:27
I was not asking you to install anything -- I asked you to download the build from my link, run it, and try the same stream, to verify whether the issue is fixed. It doesn't require installation. You can unpack & run it directly from the unpacked folder.

**Comment by sushi2503** [comment] 2021-09-22 18:47
Sorry I didn't know, anyway I did your recommendation and here is the result from Daedbeef log after the first trial :

starting deadbeef devel [static] [portable]
server_start
searching for GUI plugins in /home/pilote/.local/lib64/deadbeef
searching for GUI plugins in /home/pilote/.local/lib/deadbeef
searching for GUI plugins in /home/pilote/deadbeef-devel/plugins
load_plugin_dir /home/pilote/deadbeef-devel/plugins: scandir found 55 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /home/pilote/deadbeef-devel/plugins/ddb_gui_GTK3.so
loading plugins from /home/pilote/.local/lib64/deadbeef
loading plugins from /home/pilote/.local/lib/deadbeef
loading plugins from /home/pilote/deadbeef-devel/plugins
load_plugin_dir /home/pilote/deadbeef-devel/plugins: scandir found 55 files
loading plugin /home/pilote/deadbeef-devel/plugins/aac.so
loading plugin /home/pilote/deadbeef-devel/plugins/adplug.so
loading plugin /home/pilote/deadbeef-devel/plugins/alac.so
loading plugin /home/pilote/deadbeef-devel/plugins/alsa.so
loading plugin /home/pilote/deadbeef-devel/plugins/artwork.so
loading plugin /home/pilote/deadbeef-devel/plugins/cdda.so
loading plugin /home/pilote/deadbeef-devel/plugins/converter.so
loading plugin /home/pilote/deadbeef-devel/plugins/converter_gtk2.so
loading plugin /home/pilote/deadbeef-devel/plugins/converter_gtk3.so
loading plugin /home/pilote/deadbeef-devel/plugins/dca.so
loading plugin /home/pilote/deadbeef-devel/plugins/ddb_dumb.so
loading plugin /home/pilote/deadbeef-devel/plugins/ddb_mono2stereo.so
loading plugin /home/pilote/deadbeef-devel/plugins/ddb_shn.so
loading plugin /home/pilote/deadbeef-devel/plugins/ddb_soundtouch.so
loading plugin /home/pilote/deadbeef-devel/plugins/dsp_libsrc.so
loading plugin /home/pilote/deadbeef-devel/plugins/ffap.so
loading plugin /home/pilote/deadbeef-devel/plugins/ffmpeg.so
dlopen error: /home/pilote/deadbeef-devel/plugins/ffmpeg.so: undefined symbol: avcodec_receive_frame
trying /home/pilote/deadbeef-devel/plugins/ffmpeg.fallback.so...
plugin ffmpeg.so not found or failed to load
loading plugin /home/pilote/deadbeef-devel/plugins/flac.so
loading plugin /home/pilote/deadbeef-devel/plugins/gme.so
loading plugin /home/pilote/deadbeef-devel/plugins/hotkeys.so
loading plugin /home/pilote/deadbeef-devel/plugins/in_sc68.so
loading plugin /home/pilote/deadbeef-devel/plugins/lastfm.so
loading plugin /home/pilote/deadbeef-devel/plugins/m3u.so
loading plugin /home/pilote/deadbeef-devel/plugins/mms.so
loading plugin /home/pilote/deadbeef-devel/plugins/mp3.so
loading plugin /home/pilote/deadbeef-devel/plugins/musepack.so
loading plugin /home/pilote/deadbeef-devel/plugins/notify.so
loading plugin /home/pilote/deadbeef-devel/plugins/nullout.so
loading plugin /home/pilote/deadbeef-devel/plugins/opus.so
loading plugin /home/pilote/deadbeef-devel/plugins/oss.so
loading plugin /home/pilote/deadbeef-devel/plugins/pltbrowser_gtk2.so
loading plugin /home/pilote/deadbeef-devel/plugins/pltbrowser_gtk3.so
loading plugin /home/pilote/deadbeef-devel/plugins/psf.so
loading plugin /home/pilote/deadbeef-devel/plugins/pulse.so
loading plugin /home/pilote/deadbeef-devel/plugins/rg_scanner.so
loading plugin /home/pilote/deadbeef-devel/plugins/shellexec.so
loading plugin /home/pilote/deadbeef-devel/plugins/shellexecui_gtk2.so
loading plugin /home/pilote/deadbeef-devel/plugins/shellexecui_gtk3.so
loading plugin /home/pilote/deadbeef-devel/plugins/sid.so
loading plugin /home/pilote/deadbeef-devel/plugins/sndfile.so
loading plugin /home/pilote/deadbeef-devel/plugins/supereq.so
loading plugin /home/pilote/deadbeef-devel/plugins/tta.so
loading plugin /home/pilote/deadbeef-devel/plugins/vfs_curl.so
loading plugin /home/pilote/deadbeef-devel/plugins/vfs_zip.so
loading plugin /home/pilote/deadbeef-devel/plugins/vorbis.so
loading plugin /home/pilote/deadbeef-devel/plugins/vtx.so
loading plugin /home/pilote/deadbeef-devel/plugins/wavpack.so
loading plugin /home/pilote/deadbeef-devel/plugins/wildmidi.so
loading plugin /home/pilote/deadbeef-devel/plugins/wma.so
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter UI
starting plugin Converter UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin Opus player
starting plugin OSS output plugin
starting plugin Playlist Browser
starting plugin Playlist Browser
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec UI
starting plugin Shellexec UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
selected output plugin: ALSA output plugin
Failed to play track: https://fr1.streamhosting.ch/lounge64.aac

With the static version is even worse, I can't launch the radio at all. It doesn't freez the player but it jump to the next radio in the playlist with :

Failed to play track: https://fr1.streamhosting.ch/lounge64.aac

**Comment by Alexey-Yakovenko** [comment] 2021-09-22 21:12
alright. sorry, I forgot one tiny detail :)
the official linux builds don't support https still (need to remember to fix that).
I'll verify it locally when I have some time. perhaps tomorrow.

**Comment by kuba160** [comment] 2021-09-22 21:21
I tested given stream on windows on newest master build and I noticed that it sometimes skips the track (happened 2/10 times). I am not sure if this time it is related to mp4p since track metadata is being updated and it shows AAC stream in status bar.

**Comment by sushi2503** [comment] 2021-09-22 21:30
@ Alexey-Yakovenko : No problem.

@ kuba : I'm on Archlinux. And here it sometimes skips and quiet often freezes but there is an other radio that freezes too : 

http://ice1.somafm.com/spacestation-128-aac

This one is not an https but the commun detail with the other radio is aac.

They are no problems with mp3 radios.

**Comment by kuba160** [comment] 2021-09-22 21:37
Does it also freeze on official linux build?

**Comment by sushi2503** [comment] 2021-09-22 21:41
Yes I'm speaking about the official repo build 1.8.8-2. 
I haven't tried the second radio on the static build from the link only the first radio which couldn't connect because of https.

**Comment by Alexey-Yakovenko** [comment] 2021-09-22 21:55
@sushi2503 Just FYI, for the sake of using the same terminology: the builds from linux distro repositories are unofficial. The only official builds are the ones available directly from deadbeef website.

**Comment by sushi2503** [comment] 2021-09-22 22:01
Thanks to clarify. I naturally wanted to say the arch repo build.

**Comment by sushi2503** [comment] 2021-09-23 06:30
Just to complete the information, I have tried all http acc radio with deadbeef-devel and no problem so far. As soon as deadbeef-devel will support https I will try the problematic radio.

**Comment by Alexey-Yakovenko** [comment] 2021-09-23 08:59
I checked the stream at https://fr1.streamhosting.ch/lounge64.aac
It works fine, so yes, it's the same problem that was fixed in 149d6c0e88995dbd5e521c6ff81c62479331e1ff

**Closed by Alexey-Yakovenko** 2021-09-23 08:59 UTC
Labels: Triage

**Comment by Alexey-Yakovenko** [comment] 2021-09-23 09:02
@kuba160 
> I tested given stream on windows on newest master build and I noticed that it sometimes skips the track (happened 2/10 times). I am not sure if this time it is related to mp4p since track metadata is being updated and it shows AAC stream in status bar. Apart from that I did not notice any crashes or freezes.

it should be possible to find more information why it skipped, if you turn on vfs_curl logging (in the plugin settings).
It shows a lot of debug information.

**Comment by sushi2503** [comment] 2021-09-23 09:30
Ok thanks for your efforts. So the fix will be in the next release, right ?
If I can take the opportunity... What is that :

(deadbeef:1358): GLib-CRITICAL **: 13:05:48.912: Source ID 19 was not found when attempting to remove it

It spams this line every time I launch it.

**Comment by Alexey-Yakovenko** [comment] 2021-09-23 09:38
@sushi2503 this is not happening to me.
It indicates a bug in some code, but not necessarily in deadbeef itself.
It could be a bug in GTK itself, or a GTK theme, or in some deadbeef plugin.

It could also be that some UI view causes it, but to reproduce I would need to know how you configured deadbeef.
Also I suggest creating a new bug about it.

**Comment by sushi2503** [comment] 2021-09-23 09:45
Ok thanks, I'll do so.

**Comment by kuba160** [comment] 2021-09-23 13:30
I retested it with vfs debugging on linux, same behavior, happens sometimes on https://fr1.streamhosting.ch/lounge64.aac and very rarely on http://ice1.somafm.com/spacestation-128-aac . DeaDBeeF log output with vfs debug info:

<details>
<summary>Deadbeef log output</summary>
<p>

```
vfs_curl: started loading data https://fr1.streamhosting.ch/lounge64.aac
vfs_curl: calling curl_easy_perform (status=0)...
key= value=
key=Server value=Icecast 2.4.4
key= value=
key=Connection value=Close
key= value=
key=Date value=Thu, 23 Sep 2021 12:57:31 GMT
key= value=
key=Content-Type value=audio/aacp
key= value=
key=Cache-Control value=no-cache, no-store
key= value=
key=Expires value=Mon, 26 Jul 1997 05:00:00 GMT
key= value=
key=Pragma value=no-cache
key= value=
key=Access-Control-Allow-Origin value=*
key= value=
key=Access-Control-Allow-Headers value=Origin, Accept, X-Requested-With, Content-Type, If-Modified-Since
key= value=
key=Access-Control-Allow-Methods value=GET, OPTIONS, HEAD
key= value=
key=icy-br value=64
key= value=
key=ice-audio-info value=ice-samplerate=44100;ice-bitrate=64;ice-channels=2
key= value=
key=icy-br value=64
key= value=
key=icy-description value=... this is how we lounge in switzerland
key= value=
key=icy-genre value=Lounge Downtempo Chillout Ambient Easy Listening
key= value=
key=icy-name value=LOUNGE-RADIO.COM - swiss made
key= value=
key=icy-pub value=1
key= value=
key=icy-url value=https://lounge-radio.com
key= value=
key=icy-metaint value=16000
key= value=
key= value=
found metadata block at pos 16000, size: 48 (avail=48)
metadata fetch mode, avail: 48, metadata_size: 48, metadata_have_size: 0)
fetching 48 bytes of metadata (out of 48)
StreamTitle='DJ Fuma - Coming Down';
got stream title: DJ Fuma - Coming Down
http_close 0x7fffd8013b90
abort vfs_curl stream: 17
added file to abort list: 17
need to abort: 17
vfs_curl STATUS_ABORTED in progress callback
vfs_curl: curl_easy_perform retval=42
curl error:
Callback aborted
vfs_curl: break loop
vfs_curl: thread ended due to abort signal
http_close done
```

</p>
</details>


Not sure if useful, but I also made backtrace on `http_close`:

<details>
<summary>Deadbeef backtrace on http_close</summary>

```
Thread 17 "deadbeef-stream" hit Breakpoint 1, http_close (
    stream=0x7fffd8013b90) at vfs_curl.c:810
810	    trace ("http_close %p\n", stream);
(gdb) bt
#0  http_close (stream=0x7fffd8013b90) at vfs_curl.c:810
#1  0x0000000000435490 in vfs_fclose (stream=0x7fffd8013b90) at vfs.c:107
#2  0x00007ffff47cc49f in aac_free (_info=0x7fffd8012210) at aac.c:411
#3  0x000000000041d6de in fileinfo_free (fileinfo=0x7fffd8012210)
    at streamer.c:835
#4  0x000000000041c3ce in stream_track (it=0x15633e0, startpaused=0)
    at streamer.c:845
#5  0x000000000041d687 in streamer_next
    (shuffle=DDB_SHUFFLE_OFF, repeat=DDB_REPEAT_OFF, next=0x15633e0)
    at streamer.c:1306
#6  0x000000000041b468 in streamer_thread (unused=0x0) at streamer.c:1676
#7  0x00007ffff7e2c450 in start_thread (arg=0x7fffe1ffb640)
    at pthread_create.c:473
#8  0x00007ffff7d4ed53 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) f 6
#6  0x000000000041b468 in streamer_thread (unused=0x0) at streamer.c:1676
1676	                streamer_next (shuffle, repeat, next);
```

</details>


I recompiled aac with logging and this was the output on failing stream:

<details>
<summary>Deadbeef output with aac trace</summary>

```
vfs_curl: started loading data https://fr1.streamhosting.ch/lounge64.aac
vfs_curl: calling curl_easy_perform (status=0)...
key= value=
key=Server value=Icecast 2.4.4
key= value=
key=Connection value=Close
key= value=
key=Date value=Thu, 23 Sep 2021 13:20:00 GMT
key= value=
key=Content-Type value=audio/aacp
key= value=
key=Cache-Control value=no-cache, no-store
key= value=
key=Expires value=Mon, 26 Jul 1997 05:00:00 GMT
key= value=
key=Pragma value=no-cache
key= value=
key=Access-Control-Allow-Origin value=*
key= value=
key=Access-Control-Allow-Headers value=Origin, Accept, X-Requested-With, Content-Type, If-Modified-Since
key= value=
key=Access-Control-Allow-Methods value=GET, OPTIONS, HEAD
key= value=
key=icy-br value=64
key= value=
key=ice-audio-info value=ice-samplerate=44100;ice-bitrate=64;ice-channels=2
key= value=
key=icy-br value=64
key= value=
key=icy-description value=... this is how we lounge in switzerland
key= value=
key=icy-genre value=Lounge Downtempo Chillout Ambient Easy Listening
key= value=
key=icy-name value=LOUNGE-RADIO.COM - swiss made
key= value=
key=icy-pub value=1
key= value=
key=icy-url value=https://lounge-radio.com
key= value=
key=icy-metaint value=16000
key= value=
key= value=
totalsamples: -1, endsample: 0, samples-from-duration: -44100, samplerate 44100, channels 2
fread from offs 2605
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 8749
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 14893
found metadata block at pos 16000, size: 48 (avail=48)
metadata fetch mode, avail: 48, metadata_size: 48, metadata_have_size: 0)
fetching 48 bytes of metadata (out of 48)
StreamTitle='Cpen - Formalahyde Ride';
got stream title: Cpen - Formalahyde Ride
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 21037
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 27181
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 33325
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 39469
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 45613
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 51757
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 57901
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 64045
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
fread from offs 70189
remain: 6144
NeAACDecDecode 6144 bytes
samples =(nil)
NeAACDecDecode failed 11 times, interrupting
http_close 0x7fffd0011500
abort vfs_curl stream: 18
added file to abort list: 18
need to abort: 18
vfs_curl STATUS_ABORTED in progress callback
vfs_curl: curl_easy_perform retval=42
curl error:
Callback aborted
vfs_curl: break loop
vfs_curl: thread ended due to abort signal
http_close done
```

</details>

**Comment by sushi2503** [comment] 2022-01-05 20:52
Hello,

After yesterday's Deadbeef update (1.8.8-2 -> 1.8.8-3) on Archlinux with the "fix" about those .acc radios problems I let you know that the problem is still there with the radio https://fr1.streamhosting.ch/lounge64.aac.

I have to kill Deadbeef 2-3 times because it freezes and after the 3-4th it connects to the radio. It doesn't show any error in the xsession-errors logs.

I would really like to know what is happening there. In the past Deadbeef just went to next radio without freezing but since few months not.

Let me know what you need to investigate.

Thank you.

**Comment by Alexey-Yakovenko** [comment] 2022-01-05 20:59
@sushi2503 release 1.8.8 doesn't contain this fix, it will be part of the next release.
Alternatively, you can use a nightly build from here: https://sourceforge.net/projects/deadbeef/files/travis/linux/master/

**Comment by sushi2503** [comment] 2022-01-05 21:12
Sorry ! I was so happy that this release was the fixed one and then no luck...
I was beginning to report a new issue but fortunately you were faster to answer !

Thank you very much. :-)

P.S. With the nightly build is now ok with https radio under linux ?

**Comment by Alexey-Yakovenko** [comment] 2022-01-05 21:12
Yes, the nightly build has https support.

**Comment by sushi2503** [comment] 2022-01-05 21:14
Thanks and sorry for the disturbance.
