### ISSUE TITLE
Cancellation of accidental sorting of playlist

### ISSUE THREAD

**Issue by raparperi** [DeaDBeeF-Player/deadbeef#2658] opened 2021-08-19 14:30 UTC
### Steps to reproduce the problem
Click for example Artist column and it sorts the playlist.
### What's going on? Describe the problem in as much detail as possible.
The problem is that i have one playlist ordered by when songs are being added to this playlist. I like them in this way. I don't want the playlist to be sorted in any way. Sometimes i how ever by accident click some column which then sorts the playlist and it's impossible to get it in original order. Or is there some way? 

What i do now is that i have added %last_modified% column and it helps so that at least i get it almost in original order. Not quite, because if i change the title of song or some other column it updates the %last_modified% setting. 

Solution, i think could be if there is %file_created_timestamp% field or if there would be possibility to lock the particuler playlist so that it's columns cannot be sorted.
### Information about the software:

Deadbeef version:
OS:1.8.7

**Comment by kpcee** [comment] 2021-08-19 15:09
I think this could be problematic to implement for all platforms and all file systems. Not all file systems under Linux support the crtime flag, according to this [website](https://linuxreviews.org/File_timestamps) only xfs and ext4 support it, all others do not. 

To avoid such accidents in the future, regular backups could prevent this. I use BorgBackup for this kind of thing on daily basis.

**Comment by raparperi** [comment] 2021-08-19 15:52
> I think this could be problematic to implement for all platforms and all file systems. Not all file systems under Linux support the crtime flag, according to this [website](https://linuxreviews.org/File_timestamps) only xfs and ext4 support it, all others do not.
> 
> To avoid such accidents in the future, regular backups could prevent this. I use BorgBackup for this kind of thing on daily basis.

Yes,  the backups! I just remembered after i posted the issue that i have a weekly backups and then i remembered that last time it happened i made a script that backups .config/playlists/* every time i login into xfce. So playlist restored and all well! Now i'm editing that script so that it sends a message  telling that playlists are backed so i don't need to remember it. 

Would be nice if it would be possible to lock a playlist so that it cannot be sorted, a check mark on right click menu on playlist tab perhaps? Or that if it asks do you really want to sort, but that would be annoying since other playlists i sort sometimes. I have 4927 tracks on it so it's a big mess if it gets sorted acidentially.

Difficult word that remembered btw, i typed it wrongly a number of times. How many times there is remememeberered. Our word is easier to remember "muistin". ;-)

**Comment by jonpatterns** [comment] 2021-09-02 18:32
I too have suffered from this problem. Also, accidentally opening audio file also wipes playlist as I have deadbeef as my default audio player.

An alternative solution would be to have one (or more) levels of undo for any change to the playlist.

I also support lock playlist feature for extra idiot proofing.

**Comment by Mango2000** [comment] 2021-09-30 09:24
I'm also doing regular backups because of this and accidental sorting of playlists by name in the playlist browser plugin(a horror if you have many playlists carefully sorted by hand in the browser panel). But also when I accidentally drag & drop a lot of files from the desktop to the wrong playlist in the playlist browser plugin(I don't use playlist tabs) the backup is useful.

**Comment by lesliev** [comment] 2022-01-08 01:48
I too have many times accidentally sorted my carefully ordered playlist. I try to save it and reload it but that means I need to always remember to save it every time I add songs. And undo or "no sorting" option would be great.

**Comment by kpcee** [comment] 2022-01-11 17:57
Does anyone know how this is solved in foobar2000?

**Comment by huglovefan** [comment] 2022-03-13 20:16
just an idea but it could be solved if the headers only did visual sorting

- deadbeef would always store the list in the original order (without sorting)
- clicking a sort header in the gui would only change the order they're displayed in
- clicking the sort header a third time would remove the sort and restore the items to the original order
- adding or moving items while sorted would save the current sort as the original order

one program that has undo-able sort like this is the task manager in google chrome, there are probably others

**Comment by Alexey-Yakovenko** [comment] 2022-06-15 10:50
duplicate of #490

**Closed by Alexey-Yakovenko** 2022-06-15 10:50 UTC
Labels: Duplicate
