### ISSUE TITLE
Deadbeef 1.8.2 crashes when switching track

### ISSUE THREAD

**Issue by ben-singlet** [DeaDBeeF-Player/deadbeef#2220] opened 2019-09-18 09:38 UTC
### OS/HW Infos
OS: Arch Linux
Kernel: x86_64 Linux 4.19.73-1-lts
Shell: bash 5.0.9
DE: KDE 5.62.0 / Plasma 5.16.5
WM: KWin
GTK Theme: Breeze [GTK2/3]
Icon Theme: breeze
Font: Noto Sans Regular
CPU: Intel Core i7-6700HQ @ 8x 3.5GHz
GPU: GeForce GTX 960M
RAM: 15914MiB

### Deadbeef version
1.8.2 (via arch repo, not aur)

### Steps to reproduce the problem
Launch Deadbeef, switch tracks.

### What's going on? Describe the problem in as much detail as possible.
When switching tracks, sometimes DB crashes, sometimes not.

### Official plugins
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alac.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk2.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/ffmpeg.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/in_sc68.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mp3.so
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib/deadbeef/psf.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/rg_scanner.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
loading plugin /usr/lib/deadbeef/wma.so

### Plugins manually added
loading plugin /home/user/.local/lib/deadbeef/ddb_archive_reader.so
loading plugin /home/user/.local/lib/deadbeef/ddb_copy_info_gtk3.so
loading plugin /home/user/.local/lib/deadbeef/ddb_infobar_gtk3.so
loading plugin /home/user/.local/lib/deadbeef/ddb_misc_filebrowser_GTK3.so
loading plugin /home/user/.local/lib/deadbeef/ddb_misc_playback_status_GTK3.so
loading plugin /home/user/.local/lib/deadbeef/ddb_misc_quick_search_GTK3.so
loading plugin /home/user/.local/lib/deadbeef/ddb_misc_waveform_GTK3.so
loading plugin /home/user/.local/lib/deadbeef/ddb_vis_musical_spectrum_GTK3.so
loading plugin /home/user/.local/lib/deadbeef/ddb_vis_spectrogram_GTK3.so
loading plugin /home/user/.local/lib/deadbeef/ddb_vis_vu_meter_GTK3.so
loading plugin /home/user/.local/lib/deadbeef/vfs_rar.so

### Crash report
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
gtkui plugin compiled for gtk version: 3.24.10
**
Gtk:ERROR:../gtk/gtk/gtktextview.c:4451:gtk_text_view_validate_onscreen: assertion failed: (priv->onscreen_validated)
streamer_set_output
fb api2
connecting button tray signals
Bail out! Gtk:ERROR:../gtk/gtk/gtktextview.c:4451:gtk_text_view_validate_onscreen: assertion failed: (priv->onscreen_validated)

### + attached file
[deadbeef.log](https://github.com/DeaDBeeF-Player/deadbeef/files/3625586/deadbeef.log)

**Comment by Alexey-Yakovenko** [comment] 2019-09-18 10:47
duplicate of #2112

**Closed by Alexey-Yakovenko** 2019-09-18 10:47 UTC
Labels: Duplicate
