### ISSUE TITLE
Deadbeef 1.8.8 for Windows10 does not start normally

### ISSUE THREAD

**Issue by dtantono** [DeaDBeeF-Player/deadbeef#2726] opened 2022-01-03 06:10 UTC
### Steps to reproduce the problem
I double click the mp3 file .But, the music does not start and deadbeef shows me this log instead:

failed to add file or folder C:/Program Files/DeaDBeeF
starting deadbeef 1.8.8 [static] [portable]
WinSock init ok, library version 2.2
server_start
searching for GUI plugins in C:\Users\dtant/AppData/Roaming/deadbeef/plugins64
searching for GUI plugins in C:\Users\dtant/AppData/Roaming/deadbeef/plugins
load_plugin_dir C:\Users\dtant/AppData/Roaming/deadbeef/plugins: scandir found 0 files
searching for GUI plugins in C:/PROGRA~1/DeaDBeeF/plugins
load_plugin_dir C:/PROGRA~1/DeaDBeeF/plugins: scandir found 37 files
found gui plugin ddb_gui_GTK2.dll
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.dll
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_gui_GTK3.dll
loading plugins from C:\Users\dtant/AppData/Roaming/deadbeef/plugins64
loading plugins from C:\Users\dtant/AppData/Roaming/deadbeef/plugins
load_plugin_dir C:\Users\dtant/AppData/Roaming/deadbeef/plugins: scandir found 0 files
loading plugins from C:/PROGRA~1/DeaDBeeF/plugins
load_plugin_dir C:/PROGRA~1/DeaDBeeF/plugins: scandir found 37 files
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/aac.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/adplug.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/alac.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/artwork.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/dca.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_dumb.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_mono2stereo.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ddb_shn.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/dsp_libsrc.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/ffap.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/flac.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/hotkeys.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/lastfm.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/m3u.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/mp3.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/musepack.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/nullout.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/opus.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/pltbrowser_gtk2.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/pltbrowser_gtk3.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/portaudio.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/psf.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/rg_scanner.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/shellexec.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/shellexecui_gtk2.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/shellexecui_gtk3.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/sndfile.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/supereq.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/tta.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/vfs_curl.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/vfs_zip.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/vorbis.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/wavpack.dll
loading plugin C:/PROGRA~1/DeaDBeeF/plugins/wma.dll
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin Album Artwork
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Hotkey manager
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin Null output plugin
starting plugin Opus player
starting plugin Playlist browser GTK2
starting plugin Playlist browser GTK3
starting plugin PortAudio output plugin
starting plugin PSF player using Audio Overload SDK
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK2 UI
starting plugin Shellexec GTK3 UI
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin WavPack decoder
starting plugin WMA player
starting plugin stdio vfs
selected output plugin: PortAudio output plugin
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
selected output plugin: PortAudio output plugin
 
### What's going on? Describe the problem in as much detail as possible.
Deadbeef does not start normally and I have to click file -> open file -> and select the mp3 file as a workaround
### Information about the software:

Deadbeef version: 1.8.8
OS: Windows 10 Pro Build 19044

**Comment by Alexey-Yakovenko** [comment] 2022-01-04 08:25
Seems like an exact duplicate of #2717

**Closed by Alexey-Yakovenko** 2022-01-04 08:25 UTC
Labels: Triage, Windows
