### ISSUE TITLE
Convert 24bit audio to S32_LE option

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#1907] opened 2017-10-06 20:05 UTC
The ASUS Xonar Essence STX, and all CMI8788-based cards require that 24-bit samples are aligned in 32-bit words in memory. So I can't play 24bit audio files with bit perfect playback, but something close to it. I'm already looking into purchasing a new DAC for my machine. In the meantime, is there an option you could add that converts 24bit audio to 32bit so my card can play back 24bit files? I see there's options for 8 to 16, and 16 to 24. Could you by chance do 24 to 32? All the information about this can be found here.

http://ossnext.trueinstruments.com/forum/viewtopic.php?t=4710#p18380

Deadbeef version: Git Master as of October 4th
OS: Arch Linux 64bit

**Comment by Alexey-Yakovenko** [comment] 2017-10-07 08:06
duplicate of #1895

**Closed by Alexey-Yakovenko** 2017-10-07 08:06 UTC
Labels: duplicate
