### ISSUE TITLE
Feature Request: Lock Playlists, or Undo and Redo function

### ISSUE THREAD

**Issue by Mango2000** [DeaDBeeF-Player/deadbeef#2199] opened 2019-08-26 12:28 UTC
This is more a problem of the file eplorer plugin. But sometimes I screw up a playlist (thankfully backed up) by accidently double click a folder or song in the file explorer. Happens mostly when I select an item and try to drag & drop it to the playlist. When I do it too fast it counts as a double click. The content of the active playlist is then gone. There is no 'undo ' or 'redo' action in deadbeef? Or maybe a feature where you can lock playlists and the content of it can't be changed until you unlock it. For now this is my last request. I know there are more importent things like such feature, but maybe at least 'undo' could be added at some point.

**Comment by Alexey-Yakovenko** [comment] 2019-08-26 12:41
duplicate of #949 and #490

**Closed by Alexey-Yakovenko** 2019-08-26 12:41 UTC
Labels: Duplicate
