### ISSUE TITLE
Audio Appears to Lag the Spectrum Visualization when using ALSA Output Pugin

### ISSUE THREAD

**Issue by jensenr30** [DeaDBeeF-Player/deadbeef#2986] opened 2023-08-25 03:18 UTC
### Steps to reproduce the problem
- Start DeaDBeeF
- Enable the Spectrum visualization
- Open Edit -> Preferences -> Plugins -> ALSO output plugin
- change the preferred buffer size to 80,000
- start playing an audio file

### What's going on? Describe the problem in as much detail as possible.
Notice how the Spectrum is animated approximately 1 second before the music starts playing.  This demonstrates that the spectrum animation is not being played in sync with the music.  When using the default buffer size of 8192, the audio is fairly close to in-sync with the spectrum visualization, but you can still tell the audio appears to lag.

### Possible Solutions

The audio playback is being delayed by the buffer, and nothing can be done about that.  I think the solution is to delay the animation of the spectrum visualization by the same amount so that it appears to be in sync with the music.

Or maybe a better solution would be to create a buffer of FFT calculations that has the same length (in seconds) as the audio buffer.

**Does anyone know where the code for the spectrum visualization lives in this code base?  I'm interested in looking at it to see how daunting a task this would be...**

### Information about the software:
Deadbeef version: 1.9.5
OS: Arch Linux  6.1.46-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 16 Aug 2023 19:25:35 +0000 x86_64 GNU/Linux

**Comment by jensenr30** [comment] 2023-08-25 03:46
I just compiled deadbeef from source - no issues first try.  Thanks for making the compilation process painless!

I guess another solution would be to change the default buffer size to 1024, because that seems like a fairly reasonable buffer size, and with a buffer that short the delay between the video and audio is imperceptible.  That would be easier than creating a new buffer for FFT samples...  The downside is that this solution doesn't work for people who need a long buffer.

**Comment by Oleksiy-Yakovenko** [comment] 2023-08-25 14:57
I have already tried to establish a different sync source for visualizations when playing via large audio buffer, but it didn't work out at all, and actually made things worse. So in the time being, this is not going to be resolved, and you should assume that if you want to see visualizations in sync with audio -- you need small enough audio buffer.

Also, it's a duplicate of #1183

**Closed by Oleksiy-Yakovenko** 2023-08-25 14:57 UTC
