### ISSUE TITLE
MP3 seeking extremely slow

### ISSUE THREAD

**Issue by fenugrec** [DeaDBeeF-Player/deadbeef#2140] opened 2019-05-07 00:53 UTC
### Steps to reproduce the problem
1. Load "long" MP3 file (at least 30-40 minutes). My test files are mostly CBR, but I think I've had some VBR files and it made no difference.
1. Click in the seek bar, forward or back, far from the current position.

### What's going on? Describe the problem in as much detail as possible.
On my machine, it takes about 15 seconds to seek to a position 60 minutes forward. Seems to be exclusively an MP3 problem; the following formats seek instantly to any position :

- mp4 files with AAC audio stream
- flac
- wav
- wavpack

### Information about the software:

Deadbeef version: fairly recent git build, 479a64127
OS: artix / arch linux x86-64
libmad : 0.15.1b

Not sure if this is a problem in the library or in deadbeef's use of the library - any ideas on isolating the problem ?

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 05:48
Yeah, unlike mp3 - most other formats have seek tables, which make seeking fast.
However, it should not be 15 seconds. What kind of storage media do you use?
You don't really need to be isolating the problem, if it's reproducible - I'll look into fixing it.

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 06:19
Just tried seeking a long mp3 file stored on a 5400rpm external HDD.
Seeking takes approximately 3 seconds per mp3 hour.
Not anywhere close to 15 seconds per hour.

I suppose you're not telling us that your file is located on a network share, which would explain the slowness.

The current performance is pretty good, considering that deadbeef is staying sample-accurate when seeking MP3s - which is important for many use cases.

**Comment by fenugrec** [comment] 2019-05-07 14:18
Hi, thanks for checking this out!
files are on an SSD drive, so IO speed is not an issue. Just to be sure I tried also on a tmpfs; no change. CPU stays pegged for the whole time.

I still think the 3 seconds per mp3 hour you saw is slow - other players (VLC, foobar inside wine) take no more than a few 100 ms even on my aging CPU.
I'm not sure what you mean by sample-accuracy in this case ? Unless playing extremely short files, the seek bar isn't going to be a lot finer resolution than 1 second per pixel ?

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 14:26
It's not about seekbar. The player needs to know exactly which sample of the file it's playing, to guarantee gapless playback, proper cuesheet support, and so on.

I don't know what exactly foobar is doing, but most players just do approximate position calculation, running out of sync every time by a pretty large margin.. which means that after seeking those players don't have the knowledge about the actual sample position which is playing in the stream.

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 14:50
So what kind of CPU do you have then? Is it something very ancient? MP3 seeking is not particularly CPU-intensive, and should be entirely IO-bound, but who knows...

**Comment by fenugrec** [comment] 2019-05-07 14:57
Thanks for the clarification.

CPU: sorry, should've mentioned it - T9300 core 2 duo, 2.4GHz, not painfully slow, just old.

I just noticed that seeking (whether via the seekbar or with "seek 5s forward" hotkey) seems to take longer, the farther from 0:00 I am. In other words, if I'm at 50:00 in the file, trying to seek anywhere close to that position takes as long as seeking from 0 to ~ 50:00, if that makes sense. Kind of indicates it's reparsing the file from the start ? for seeking back, this would be understandable, but seeking forward (sample-accurately) should be easy ?

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 14:59
my CPU is about the same as yours, and media is slower. so I don't really know why it's so slow for you.

> Kind of indicates it's reparsing the file from the start ? for seeking back, this would be understandable, but seeking forward (sample-accurately) should be easy ?

Yes, this is correct, on both points.
The only reason it's not implemented is because there are many significantly more pressing issues which need solving.

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 15:02
is there any chance that you built deadbeef yourself, and didn't enable optimisation? so you're basically running a debug build.. - this would explain why it's 5 times slower than my computer.

**Comment by fenugrec** [comment] 2019-05-07 15:07
Haha, good to know I'm not the only one running old(er) hardware !

I think you may be onto something vs the build. I tried my distro's 0.7.2, and seeking is lightning-fast.
Trying again from git. CFLAGS should be
CFLAGS="-march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -fno-plt"
so it should be reasonably optimized... I'll try a different -mtune just for fun.

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 15:09
tbh I'm not running older hardware - it's a last year's iMac with i5 3.0GHz, but the numbers don't seem to be far off, and mp3 seeking is single-threaded.

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 15:10
> I tried my distro's 0.7.2, and seeking is lightning-fast.

that doesn't indicate anything. version 1.8 uses a new mp3 parser, which is more accurate and fast, but doesn't handle some edge cases. the older mp3 parser used in 0.7.2 did some shortcuts do make seeking fast, but there were many complaints about accuracy, which is why I changed the approach.

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 16:41
Btw, I forgot to perform the same test on SSD.. it's still taking the same time - so it's CPU-bound indeed. In any case, it's kind of a known problem, and will be resolved at some point.

**Comment by fenugrec** [comment] 2019-05-07 17:08
I'm still surprised that your machine is that much faster on single-core performance, but maybe. I should try a profiling run to see what's taking so much CPU time...

**Comment by saivert** [comment] 2019-05-13 13:37
Not much you can do about this. mp3 decoding is single-threaded and it is saturating a core close to 100% here in my slower test VMs. The mp3 parsing isn't the issue. The decoding during sample skip is. This is very noticable when handling cuesheets. Would it be possible to cache the offsets for cuesheets?

**Comment by Alexey-Yakovenko** [comment] 2019-05-13 13:39
@saivert this should not be a problem. sample skip step is supposed to decode only a single mpeg frame.

**Comment by saivert** [comment] 2019-05-13 13:47
During perf trace I saw it spending a lot of time in avx code in mpg123 lib. I may be reading that wrong of course. Why is that do you think?
The whole file takes ~8 seconds to decode and if I play track 3 (in cue) that is about 3 seconds so makes sense that each track takes progressively longer to seek to.

**Comment by Alexey-Yakovenko** [comment] 2019-05-13 13:49
This would indicate a bug in either the parser, or the mp3 plugin.
It's not supposed to decode the whole file until seek point. It should parse / skip mpeg frames until the mpeg frame which contains the requested position, and then decode a single frame and skip a few samples.

**Comment by stefson** [comment] 2019-05-28 05:58
I can confirm, it's sort of laggy compared to the older 0.7.2 - seeking eats a whole core for maybe five or six seconds on a ryzen5. 

/usr/bin/file shows: `MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, JntStereo`

**Comment by NigelWinterbottom** [comment] 2019-08-28 08:44
Confirmed here also: Comparing the "deadbeef-static_0.7.2-2_x86_64.tar.bz2" with "deadbeef-static_1.8.2-1_x86_64.tar.bz2" I find the functions: seek by 5s and seek by 1% both take about 2.5s in 1.8.2, as does clicking the playbar. 

VLC player also delays by about this time when seeking which is why I have switched back to deadbeef 0.7.2 which seeks without noticeable delay. If the actual seek point is only approximate then I don't care about that. The fast seek is "the killer feature".

Can both parsers co-exist and the user be offered a selection if he wants fast or accurate seeking ?

{Now I've written that I recollect trying a player that does offer that choice but forget which}

**Comment by Alexey-Yakovenko** [comment] 2019-08-28 08:51
> The fast seek is "the killer feature".
> Can both parsers co-exist and the user be offered a selection if he wants fast or accurate seeking ?

No, because the users enable the fast inaccurate seeking, and send tons of bug reports / emails asking to fix it. The only way forward is to have fast *and* accurate seeking, without any compromises which would cause me to have to dig through hundreds of emails.

**Comment by Alexey-Yakovenko** [comment] 2019-08-28 13:08
>  Is there a way to confirm what you (@Alexey-Yakovenko ) said earlier,

What exactly do you need to confirm and why?

**Comment by Alexey-Yakovenko** [comment] 2019-08-28 13:22
Yeah, you can debug this using any debugger.

**Comment by Alexey-Yakovenko** [comment] 2019-08-28 19:41
It's unlikely an upstream bug. Deadbeef has its own mp3 parser, not using any 3rd party library. There must be a bug in there.

**Comment by unclebrr** [comment] 2019-10-11 07:39
Just upgraded to 1.8.2 from 0.7.2 and can confirm that seek became A LOT slower... cannot and don't want to measure it in (mili)seconds, but it became really uncomfortable - the response is very long, slow. Well it could be more accurate but me personnaly don't need such accuracy - more in need of speed. Could something be done? (I've read the above)  Maybe move seach (parser) to plugin, make two different plugins (fast, accurate)? When you're dealing with 30-50-100Mb files it's pain in the ass, really ;)

**Comment by Alexey-Yakovenko** [comment] 2019-10-11 08:17
It's a code bug, not an accurate vs inaccurate problem.
The issue is a bit lower priority than it should be, since very few users are affected, but it will get fixed eventually.

**Comment by kpcee** [comment] 2019-11-06 09:26
Seeking MP3 files seems to have a bigger problem, even with normal MP3 files. If you press the shortcut for e.g. seeking +5 seconds permanently, the playback stops more and more after a few seconds until it stops completely.

**Comment by Alexey-Yakovenko** [comment] 2019-11-06 11:13
@kpcee you described exactly the same problem though.
The entire file gets decoded or scanned or whatever, up to seek point, which is slow.
It gets slower towards the end of file.

**Comment by Alexey-Yakovenko** [comment] 2019-11-06 20:29
I just did a little bit of testing on mp3 parser.

Seeking to the end of a whole mp3 file on a spinning 5400rpm HDD (320kbps, 3:44 duration) gives the following statistics:

```
Seeks: 201
Reads: 202
Bytes: 1848
Time: 0.000315 sec
```

Performance is ok -- that's 0.4ms, nothing to worry about really.

But it's also true that no matter which position I seek to -- the whole file seems to be scanned.
This is totally not intended, and makes it completely unclear how seeking even works..
And possibly this is what causes slowdown later on.

I think the solution is near.

**Comment by Alexey-Yakovenko** [comment] 2019-11-06 20:35
More investigation.. I think I nailed it.
Actually, the file contains much more than 200 packets, but scanning always stops at 202.
It means that anything after the first 200 packets gets decoded, and this is where the slow comes from.

**Comment by Alexey-Yakovenko** [comment] 2019-11-06 20:42
A fix has been submitted. Please let me know how it feels now.

**Closed** 2019-11-06 20:41 UTC
Labels: Bug

**Comment by fenugrec** [comment] 2019-11-06 21:04
Hi, thanks for working on this!

I just tested 0407215c5 and it is better than 1.8.2, but :
- 3 seconds seek time per hour of mp3 still "feels slow" (this is on a newer ryzen 2700 machine)
- if current position is at 1:00:00, seeking +5 sec still takes 3 seconds (still decoding the whole file ?)

**Comment by Alexey-Yakovenko** [comment] 2019-11-06 21:16
@fenugrec I don't think that "decoding whole file" ever happens anymore.
The whole file gets scanned though, up to the packet to begin playing from.

I think the only way to solve the "3 seconds per hour" problem is to generate seek tables in background and then reuse them while the file is playing.

**Comment by Alexey-Yakovenko** [comment] 2019-11-06 21:17
@fenugrec thanks for the feedback anyway! that's 5x speedup, so looks like the fix worked.

**Comment by Alexey-Yakovenko** [comment] 2019-11-06 21:19
> if current position is at 1:00:00, seeking +5 sec still takes 3 seconds (still decoding the whole file ?)

This particular edge case can be improved without a seek table, but it's not really solving the problem. People would still report issues like "seeking backward is 1000x slower than seeking forward" etc.

**Comment by kpcee** [comment] 2019-11-07 09:04
It's definitely much better but not as good as other music players like Audacious or cmus.

**Comment by Alexey-Yakovenko** [comment] 2019-11-07 09:42
As it was pointed out before, it's a trade-off between precision and speed.
Without taking both factors into account, the comparison would not be fair.
Although I know one example which is both precise and fast, and that's what I'm aiming for.
One step at a time.

**Comment by unclebrr** [comment] 2019-11-08 15:20
Well, just tried new developement version.
2 files, CBR 256k, ~55 mins each (intel quad, 16Gb, linux leap, ext4, SDD)
seeking from start to end is ~8-10 SECONDS!
I think it's early to close this issue :(

**Comment by Alexey-Yakovenko** [comment] 2019-11-08 16:32
@unclebrr it sounds like you're still running an unfixed version.
I created a 1 hr long mp3, and seeking from start to end is 0.1 sec on SSD, 1.84 sec on HDD.
my hardware: 3 GHz quad-core i5, APFS / macOS

**Comment by unclebrr** [comment] 2019-11-10 08:17
No, I tried 0407215.

**Comment by Alexey-Yakovenko** [comment] 2019-11-10 10:56
@unclebrr well this case was about fixing a particular issue, where almost the whole file was decoded up to seek point. This is now fixed, and if you're dissatisfied with the current performance -- it's best to create a new case. I'll update the title to reflect this.
