### ISSUE TITLE
Blur Album Art (version 1.9.0 and version 1.9.1)

### ISSUE THREAD

**Issue by wise9uy** [DeaDBeeF-Player/deadbeef#2820] opened 2022-06-16 06:37 UTC
### Steps to reproduce the problem
1. Download deadbeef from:
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.8/deadbeef-static_1.8.8-1_x86_64.tar.bz2/download
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.0/deadbeef-static_1.9.0-1_x86_64.tar.bz2/download
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9.1/deadbeef-static_1.9.1-1_x86_64.tar.bz2/download

2. Unpack.
3. Run “deadbeef” version 1.8.8 from unpacked folder.
4. Add music file with album art enabled.
5. Look at album art quality.
6. Back to step 3 for version 1.9.0 and 1.9.1

### What's going on? Describe the problem in as much detail as possible.

- Album art on version 1.8.8 is **clear**.
![Screenshot at 2022-06-16 12-57-47](https://user-images.githubusercontent.com/107605657/174009582-04ebb700-22ad-4910-8359-018382424d5e.png)

- Album art on version 1.9.0 is **blur**.
![Screenshot at 2022-06-16 12-58-22](https://user-images.githubusercontent.com/107605657/174009626-f642a11d-907e-4e51-9227-edf47abf3de5.png)

- Album art on version 1.9.1 is **blur**.
![Screenshot at 2022-06-16 12-58-45](https://user-images.githubusercontent.com/107605657/174009666-7756e1eb-6a2b-4766-8207-c4c797eec138.png)

### Information about the software:

Deadbeef version: 1.8.8 , 1.9.0, 1.9.1 (tar.bz2 & rpmfusion).
OS: Fedora Linux 36.

**Comment by Alexey-Yakovenko** [comment] 2022-06-16 07:14
There can be 2 reasons for that (that I know):
1. The album has multiple album arts, and the one that deadbeef uses is lower res - you should check which one is used, and how large it is. Deadbeef (1.9.x) prefers the album art from a file (cover.jpg etc), and then it looks for embedded, online, etc.
2. In the artwork plugin preferences, album art resolution is set too low.

**Comment by Alexey-Yakovenko** [comment] 2022-06-16 07:16
Closing, since I'm pretty sure you can solve this by rearranging album art files or changing preferences.
I understand this looks like a regression, but it is probably not.

**Closed by Alexey-Yakovenko** 2022-06-16 07:16 UTC

**Comment by wise9uy** [comment] 2022-06-16 07:42
The only album art i have is embedded using musicbrainz picard (1000x1000 px)
And, you're right!
Change image size from 256 to 1000 from album artwork plugin fix quality.
Thank you for hint.
