### ISSUE TITLE
2 issues with REM directives contained in cue sheets

### ISSUE THREAD

**Issue by granric** [DeaDBeeF-Player/deadbeef#2492] opened 2020-12-18 18:10 UTC
### Steps to reproduce the problem
A: segfault when a REM COMPILATION TRUE directive is present in header data

1. insert a REM COMPILATION TRUE directive in the header of the .cue file with a text editor
2. save + doubleclick the .cue file (or open via the File dialog)
3. program dies with a segmentation fault (see attachment)
[segfault.txt](https://github.com/DeaDBeeF-Player/deadbeef/files/5717192/segfault.txt)

B: presence of the REM COMPOSER "whatever" in track data miscalculates duration of subsequent tracks 

1. insert a REM COMPOSER "whatever" directive within track data of the .cue file with a text editor
2. save + doubleclick the .cue file (or open via the File dialog)
3. durations are miscalculated - either zero or cumulates (see screenshot)
![screenshot](https://user-images.githubusercontent.com/12915527/102644784-ad4bef00-4161-11eb-9237-396de9a45ae3.png)

### What's going on? Describe the problem in as much detail as possible.
Cuesheets, when prepared by ExactAudioCopy, oftentimes contain REM directives, for the most part ignored by other programs. 
Unfortunately, they're not completely ignored here, leading to unexpected behaviour: either a segfault or the impossibility to select specific tracks during reproduction.

Issue A should be self-explanatory. 
Issue B has as consequences:
- zero-duration tracks cannot be selected for reproduction
- the first subsequent track with either a pre-gap or ultimate-in-list, displays cumulated duration of the tracks above

Editing the .cue file as text and removing the offending lines is a workaround to both of these issues.

### Information about the software:

Deadbeef version: 1.8.4 
OS: Ubuntu Mate 18.04.5

**Comment by Alexey-Yakovenko** [comment] 2020-12-18 18:19
duplicate of #2389

**Closed by Alexey-Yakovenko** 2020-12-18 18:19 UTC

**Comment by granric** [comment] 2020-12-18 22:40
True: got deadbeef-static_1.8.5~beta1-1_amd64.deb and this solved both issues. Thanks!
