### ISSUE TITLE
UI freezes after attempting to play audio on device without valid configuration (e.g. 2.1 surround output)

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#1898] opened 2017-09-28 20:08 UTC
### Steps to reproduce the problem

Try to play a song

### What's going on? Describe the problem in as much detail as possible.

No playback, it doesn't start the timer for the length of the track.

more details: with virtualbox+2.1, with or without pulseaudio, sound plays severely distorted. Needs a test on real hw.

### Information about the software:

Deadbeef version: Git from September 28
OS: Arch Linux 64bit

This has been going on for a while now, I just thought I would mention it. I have a set of Bose speakers with a subwoofer on a ASUS Xonar Essence STX. I should be able to use this option without issue.

**Comment by shoober420** [comment] 2017-09-29 01:10
I thought I would mention that I'm currently using the "Front Speakers" option, which works. Maybe it's my driver settings. I'll see if it's an configuration issue on my end.

**Comment by shoober420** [comment] 2017-09-29 01:22
Are those other settings Pulseaudio specific? I refuse to use or install Pulseaudio. If it's some upmix trickery, I'll stick with the "Front Speakers" option.

**Comment by Alexey-Yakovenko** [comment] 2017-09-29 09:16
There should not be any PulseAudio-specific options when ALSA plugin is active, unless PulseAudio server is running and proxying to ALSA behind the scenes.

**Comment by Lithopsian** [comment] 2017-09-29 09:38
I see Pulse-specific options in the Output Device dropdown even when the PulseAudio plugin is completely removed.  Selecting one of them causes playback to stop. Attempting to start playback causes a permanent buffering state.  Things don't go well after that.

With "front speakers", Alsa will play, but it seems to be a fallback setting.  The message "cannot set sample format (Invalid argument), trying all supported formats" appears.

**Comment by Alexey-Yakovenko** [comment] 2017-09-29 09:40
@Lithopsian pulse plugin does not in any way affect how ALSA plugin works in conjunction with running PulseAudio server.

**Comment by Alexey-Yakovenko** [comment] 2017-09-29 09:44
> With "front speakers", Alsa will play, but it seems to be a fallback setting. The message "cannot set sample format (Invalid argument), trying all supported formats" appears.

What is the input format?

**Comment by Alexey-Yakovenko** [comment] 2017-09-29 09:50
It looks like ALSA 2.1 device refuses to accept any other formats but 16 bps. That's why there are those messages. I found a couple of wrong printfs in there, but fixing them don't change the result.

The real problem is that I'm getting static for any input streams when trying to play to 2.1 device. It might be virtualbox audio driver's fault though. I will need to try on real hardware later.

**Comment by Alexey-Yakovenko** [comment] 2017-09-29 09:58
I fixed the error messages, but that doesn't fix playback (for me at least).

**Comment by Lithopsian** [comment] 2017-09-29 10:11
How about: "I see all the PulseAudio options even when PulseAudio server isn't running"?

I was passing 2.0 (plain stereo) to ALSA, 16/48.  The output from the decoder plugin would have been floats.

**Comment by Alexey-Yakovenko** [comment] 2017-09-29 10:47
> How about: "I see all the PulseAudio options even when PulseAudio server isn't running"?

I don't have an answer to that, but running aplay -L will give you the same stuff as what you see in deadbeef. The point is, deadbeef is just displaying what ALSA enumerates. How it gets there is another question.

> I was passing 2.0 (plain stereo) to ALSA, 16/48. The output from the decoder plugin would have been floats.

Decoders give the same format regardless of output format. Streamer is asking the output plugin to the format which decoder wants. If it can't get it -- conversion happens into whatever format is possible.

**Comment by shoober420** [comment] 2017-09-29 15:53
I don't have Pulseaudio installed, and have those options under ALSA. Even 7.1 surround is present. When I use "Front Speakers" option, bass still comes out of my subwoofer. I thought maybe the 2.1 surround option might separate the bass better to my subwoofer.

**Comment by shoober420** [comment] 2017-09-29 16:32
From all the googling I've done, these seem like Pulseaudio options.

**Comment by Alexey-Yakovenko** [comment] 2017-10-02 11:12
> I don't have Pulseaudio installed, and have those options under ALSA. Even 7.1 surround is present. 

It seems like you and @Lithopsian are talking about some different options.. Or confusing/mixing them up in some other way.

**Comment by Alexey-Yakovenko** [comment] 2017-10-02 11:21
@Lithopsian I killed and removed pulseaudio, and can confirm that aplay -L still lists the pulseaudio devices. Apparently pulse hardcodes them to some system configs, and not cleaning up.

**Comment by shoober420** [comment] 2017-10-05 02:24
I believe we are talking about the same thing. Heres my output of "aplay -L"

null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default:CARD=STX
    Xonar STX, Multichannel
    Default Audio Device
sysdefault:CARD=STX
    Xonar STX, Multichannel
    Default Audio Device
front:CARD=STX,DEV=0
    Xonar STX, Multichannel
    Front speakers
surround21:CARD=STX,DEV=0
    Xonar STX, Multichannel
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=STX,DEV=0
    Xonar STX, Multichannel
    4.0 Surround output to Front and Rear speakers
surround41:CARD=STX,DEV=0
    Xonar STX, Multichannel
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=STX,DEV=0
    Xonar STX, Multichannel
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=STX,DEV=0
    Xonar STX, Multichannel
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=STX,DEV=0
    Xonar STX, Multichannel
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=STX,DEV=0
    Xonar STX, Multichannel
    IEC958 (S/PDIF) Digital Audio Output
hdmi:CARD=NVidia,DEV=0
    HDA NVidia, HDMI 0
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=1
    HDA NVidia, HDMI 1
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=2
    HDA NVidia, HDMI 2
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=3
    HDA NVidia, HDMI 3
    HDMI Audio Output



"surround21" should work for me, unless this is pulseaudio related, which I don't have installed.

**Comment by Alexey-Yakovenko** [comment] 2017-10-05 07:09
ok. then "PulseAudio Sound Server" device config is part of ALSA now. I didn't realize about that.

**Comment by shoober420** [comment] 2017-10-05 07:33
Then I'll just close this, since those options are just pulseaudio upmixing settings. I'm glad we all got that figured out lol

**Comment by Alexey-Yakovenko** [comment] 2017-10-05 08:44
This issue is valid, please don't close. It's an issue with pulseaudio too (plays static with any audio format)

**Comment by Alexey-Yakovenko** [comment] 2017-10-05 08:45
btw, what happens if you try to play a file using `aplay` using the same device? does it play?

**Comment by Alexey-Yakovenko** [comment] 2017-10-05 08:55
I just tried that.. aplay also has issues with playing into that device, sound plays at wrong samplerate, and it's a bit distorted, but deadbeef plays it differently, so that needs to be looked at

**Comment by Alexey-Yakovenko** [comment] 2017-10-05 10:57
so.. let's start collecting some findings.

## virtualbox + IHC AC97

* can only play 16 bit / 48KHz
* default and 2.0 devices play fine
* 2.1 + aplay: plays at wrong speed
* 2.1 + deadbeef: plays only first frame, then stops accepting data, and keeps playing garbage
* all other multichannel devices: don't play anything, "no configurations available".

**Comment by shoober420** [comment] 2017-10-05 18:36
Ok, when I tried the following command:

aplay -D "surround21:CARD=STX,DEV=0" ~/Downloads/ThirdEyeRapists/The\ Third\ Eye\ Rapists\ -\ Deathtrip\ Transcendence\ -\ 01\ Endless\ Funeral\ Rapture.wav

I got the following error.

aplay: set_params:1289: Broken configuration for this PCM: no configurations available

I'm assuming my ALSA configuration is not correct.

**Comment by Alexey-Yakovenko** [comment] 2017-10-05 18:38
same here, it means that this device doesn't have valid configurations, and no sound would be played.

However, deadbeef should not be freezing on that error -- it's a regression which needs fixing.

**Comment by Alexey-Yakovenko** [comment] 2017-11-17 13:22
This should be fixed now

**Closed by Alexey-Yakovenko** 2017-11-17 13:22 UTC
Labels: bug
