### ISSUE TITLE
DeaDBeeF 1.9.2-1 cannot play certain .aac and .opus files

### ISSUE THREAD

**Issue by Zen997** [DeaDBeeF-Player/deadbeef#2880] opened 2022-10-27 01:57 UTC
### Describe the problem in as much detail as possible:
![Plugins](https://user-images.githubusercontent.com/93111284/198172986-2184c44f-33ca-4df8-93d0-f3c4ec31b3a9.png)
![Sound](https://user-images.githubusercontent.com/93111284/198173006-b03ec6f5-dacd-4310-bd56-9a490e0c29ac.png)
![aac-file](https://user-images.githubusercontent.com/93111284/198173021-11182430-22b6-4a13-b6a6-4e26c0c26ede.png)

DeaDBeeF cannot load into playlist nor play certain .aac files in .m4a or .mp4 containers and .opus files in .webm container. For Opus files the error pops up when loading the files into playlist (ERROR: could not load: /home/zen/Music/Rainbow.opus). AAC files load into playlist with no errors, but display zero length playtime (Duration 0:00) and negative bitrate with nonexistent value of -2147483648 (the actual value is 128 kbps), so DeaDBeeF skips to the next playable file. All of these files play properly in Audacious and SMPlayer (the files are reported as Opus and AAC accordingly regardless of the file extension in both players). Changing the file extension from .webm to .opus and .mp4 to .m4a or .aac makes no difference for DeaDBeeF. Same problem on both distros: Debian 11 Bullseye and Ubuntu 22.04.1 LTS.
### Information about the software:
Deadbeef version: 1.9.2-1
OS: Ubuntu 22.04.1 LTS

**Comment by Oleksiy-Yakovenko** [comment] 2022-10-27 10:09
Hello,
I would not be able to reproduce the problem unless sample files are provided, or precise instructions are provided how to create such files.

**Comment by JakeSFR** [comment] 2022-10-31 14:29
Maybe it's similar, maybe it's completely different, but all I could reproduce was an unplayable AAC in an M4A container, if bitrate >= 265K:

`ffmpeg -f lavfi -i "sine=frequency=1000:duration=5" -acodec libfdk_aac -b:a 265K bad_aac.m4a`

The bitrate in DB's Properties is _not_ negative, though.
The file plays in ffplay and VLC. 
Encoding with '.aac' extension instead of '.m4a' makes it work in DB, regardless of bitrate.

It's Linux/ALSA, but it doesn't work also with the NULL plugin.

**Comment by Zen997** [comment] 2022-11-03 02:35
Hello and thank you for reply.

I noticed that the problem only happens with files downloaded from
YouTube using the "YouTube Video and Audio Downloader (WebEx) by
feller". I choose .opus 160 kbps audio files and without using ffmpeg
they have the .webm extension and do not play in DeaDBeeF, but play
perfectly in Audacious and SMPlayer. When the .opus content is
extracted using ffmpeg:   ffmpeg -i "input.webm" -vn -acodec copy
"output.opus"   the files play perfectly in DeaDBeeF. The problem is
that it is time consuming to extract the audio files one by one.

**Comment by Zen997** [comment] 2022-11-03 05:10
> Hello, I would not be able to reproduce the problem unless sample files are provided, or precise instructions are provided how to create such files.

Hello Oleksiy and thank you for reply.

I really like the DeaDBeeF and want to thank you for creating and maintaining it. I noticed that the problem only happens with files downloaded from YouTube using the "YouTube Video and Audio Downloader (WebEx) by feller". I choose .opus 160 kbps audio only files to download and without using ffmpeg they have the .webm extension and do not play in DeaDBeeF, but play perfectly in Audacious and SMPlayer. When the .opus content is extracted using ffmpeg:   ffmpeg -i "input.webm" -vn -acodec copy "output.opus"   the files play perfectly in DeaDBeeF. The problem is that it is time consuming to extract the audio files one by one. I attach two files. The file "Coralie Clément - Salle des pas perdus.webm" is the original download and does not play in DeaDBeeF. The file "Coralie Clément - Salle des pas perdus.opus" was extracted with ffmpeg and plays perfectly in DeaDBeeF. If there is a fix that would allow DeaDBeeF to recognize the original .webm file the same way as Audacious does, it would be great. Thanks again.

P. S. I couldn't upload .opus file because it is not supported by github, so I upload both .webm and .opus files in .zip format as "sample_files.zip".
[sample_files.zip](https://github.com/DeaDBeeF-Player/deadbeef/files/9925766/sample_files.zip)

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-05 18:59
The opus file that you sent works fine for me (only tried on mac so far).
Webm file doesn't play, but it's not really supposed to -- deadbeef doesn't support webm natively, and ffmpeg plugin in my build doesn't include it.

**Comment by Oleksiy-Yakovenko** [comment] 2022-11-06 14:15
Tested on linux, the opus file plays fine. Closing the bug, since there's nothing to action on.
Webm container format is not supported by deadbeef. Please feel free to post a feature request.

**Closed by Oleksiy-Yakovenko** 2022-11-06 14:15 UTC
