### ISSUE TITLE
When deleting all tracks in a folder, do not leave an empty folder

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [DeaDBeeF-Player/deadbeef#892] opened 2015-03-12 22:58 UTC
Original [issue 990](https://code.google.com/p/ddb/issues/detail?id=990) created by Alexey-Yakovenko on 2013-10-16T13:22:50.000Z:

(Priority - MINOR , may be postponed)

<b>What steps will reproduce the problem?</b>

*\* WARNING (to users _reading_ this testcase) **
For the following, NEVER operate on your original files or you will lose them  

[!!] 0. Make a BACKUP copy of one of your album folders
(preferably on a file tree with ONE album PER folder)
2. Load just the backup copy (and nothing else) of one of your albums, i. e. one folder, into an empty playlist on deadbeef
3. Select all tracks, right click them and select 'Remove from disk'
(Make sure you're doing (3.) on a backup, since you will physically remove your files! You've been warned.)

<b>What is the expected output? What do you see instead?</b>

There shouldn't be left an empty folder (no need to be there anymore, since its contents are removed)

<b>What version of the product are you using? On what operating system and CPU</b>
<b>architecture?</b>

ddb trunk, lubuntu saucy beta, x86
- NOTE to the developer(s) \* 
  I am aware that when attempting to remove that folder, it might happen that only the TRACKS were removed, but there may be some pictures (*.jpg ? ) left in there.
  This is why this task may not be as easy as it looks at first.

**Comment by mallniya** [comment] 2022-02-21 23:24
Duplicate of https://github.com/DeaDBeeF-Player/deadbeef/issues/674

**Closed** 2022-02-22 07:08 UTC
Labels: Duplicate
