### ISSUE TITLE
Invalid UTF-8 from Zip archive audio

### ISSUE THREAD

**Issue by 64542426** [DeaDBeeF-Player/deadbeef#2307] opened 2020-01-11 14:03 UTC
### Steps to reproduce the problem
Create a column with format: "**%filename_ext%**"
Add on playlist a Zip Archive audio file with UTF-8 fonts or tags in Japanese
[You can test it right here](https://mega.nz/#!LrxXCQQA!oyBst1CeDYw-aTjxuXxDvpwedl2sIW69xugRIEOIxo0) "without extracting it, just play from zip".

### What's going on? Describe the problem in as much detail as possible.
After i create a column "%filename_ext%" i noted squares on Japanese text (see image-below) from "%filename_ext%".
Since i'd like to play audios from Zip Archives i'd like aswell to have this column readable enough if it's possible.

**Note**: If the audio-file is extracted from zip archive, everything is clearly readable, also errors disappears from console.
I got this issue only from ZIP's Audio, mostly i tested with Japanese fonts/formats/audio.
Perhaps it's a archive issue or not, i don't know?

### Console Error + Playlist Image:
`(deadbeef:951): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()`

[Playlist-image](https://live.staticflickr.com/65535/49367025661_2e96994281_o.png)

### Information about the software:

Deadbeef version: [Devel-latest](https://sourceforge.net/projects/deadbeef/rss?path=/travis/linux/master)
OS: [Devuan](https://files.devuan.org/)

**Comment by Alexey-Yakovenko** [comment] 2020-01-14 17:46
Can't reproduce on either mac or linux, no pango errors, and the text is rendered correctly.
![image](https://user-images.githubusercontent.com/1895698/72368354-3363e800-36fe-11ea-84c3-937d2f1bc4cd.png)

**Comment by JakeSFR** [comment] 2020-01-14 20:17
I can reproduce it (Fatdog64 Linux, GTK2/3).
To double-check, just tried also in Mint 18.3 in VBox:

![db_mint_vfs_zip_pango](https://user-images.githubusercontent.com/6226504/72378966-ba22c000-3712-11ea-812a-5f767cd760f2.png)

**But**, repacking that ZIP's contents, either using Zip (3.0) of p7zip (16.02), fixed it for me.

**Comment by Alexey-Yakovenko** [comment] 2020-01-14 20:38
Thanks. I guess i need to try more builds and maybe another linux distro.

**Comment by 64542426** [comment] 2020-01-15 08:38
The audio files that i tested are from .zip archive, squares are noted mostly on this format. 
@Alexey-Yakovenko I see you've extracted FLAC from ZIP, please play directly from archive without extracting, See my Note above: If it is extracted it play and display OK, but i the issue lies on Archive ZIP.

**Comment by Alexey-Yakovenko** [comment] 2020-01-16 06:41
@64542426 I didn't unpack, I guess it depends on the version of unzip library or something like that.

**Comment by LisandraBrave** [comment] 2020-01-17 04:47
This is a problem with the zip file format itself. Historically, Zip has had no built in way to specify filename encoding, and older zip encoders will happily just use whatever system encoding is used. The only thing Deadbeef could hope to do is to support the most commonly used zip file standard and mark the rest as not a Deadbeef bug.

**Comment by 64542426** [comment] 2020-01-17 12:57
@LisandraBrave 
I too had some doubt about Zip concern. Your explanation seems correct. I have no more to add, if the author sees it properly like this, well let close this ticket if he has done his checks.

**Comment by Alexey-Yakovenko** [comment] 2020-01-17 13:09
Well I want to understand why it works on my machines, and doesn't work on others. I think this issue is fixable.

**Comment by 64542426** [comment] 2020-01-18 07:42
I can't test it with virtualization to different OS'es to provide more data. Sorry!

The issue may hide on the fact that I'm on the old system Devuan 1 (jessie) / Debian 8 (jessie) and the packages "zip/unzip/gtk2/fonts" are outdated?

If you can test it on [Debian 8](https://www.debian.org/releases/jessie/debian-installer/) it could probably tell more specifically.
Or test it to Mint 18.3 like JakeSFR above.

**Comment by Alexey-Yakovenko** [comment] 2020-01-18 10:31
I reproduced the bug. It happens on static builds. I think libzip is due for an update in there.

**Comment by 64542426** [comment] 2020-01-18 14:39
That's awesome to hear master, thanks for successful fishing.

**Comment by Alexey-Yakovenko** [comment] 2020-01-26 12:28
This is now fixed in static builds on master branch, and will be included in 1.8.3 later.

**Closed by Alexey-Yakovenko** 2020-01-26 12:28 UTC
Labels: Bug
