### ISSUE TITLE
Scan Selection As Albums (By Tags) doesn't work like it says.

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1891] opened 2017-09-26 01:58 UTC
The same album title:
![deepinscreenshot_20170926112719](https://user-images.githubusercontent.com/20014762/30841184-b1b29efa-a2ad-11e7-988c-2202ea3d9c2b.png)
How I did it (gif):
![deepin-screen-recorder_deadbeef_20170926095417](https://user-images.githubusercontent.com/20014762/30838968-58cf1036-a2a1-11e7-8c4e-e5cf8246e864.gif)

### Steps to reproduce the problem
Just like the gif above.
ReplayGain -> Scan Selection As Albums (By Tags)
### What's going on? Describe the problem in as much detail as possible.
It doesn't select them as an album by tags, they should be in the same album.
### Information about the software:
```
Name            : deadbeef-git
Version         : r7392.6a0a9b9a-1
Description     : Music player based on GTK2 (devel branch)
Architecture    : x86_64
URL             : http://deadbeef.sourceforge.net
Licenses        : GPL2
Groups          : None
Provides        : deadbeef
Depends On      : alsa-lib  desktop-file-utils  gtk2  gtk3  hicolor-icon-theme  gtkglext  jansson
Optional Deps   : libsamplerate: for dsp_libsrc plugin (resampler) [installed]
                  libsm: optional dependency for gtkui session client support [installed]
                  libice: optional dependency for gtkui session client support [installed]
                  alsa-lib: ALSA support [installed]
                  alsa-oss: for OSS output plugin
                  libvorbis: for ogg vorbis plugin [installed]
                  libogg: for ogg vorbis plugin [installed]
                  libmad: for mp3 plugin (mpeg1,2 layers1,2,3) [installed]
                  flac: for flac plugin [installed]
                  curl: for last.fm, vfs_curl (shoutcast/icecast), artwork plugins [installed]
                  imlib2: for artwork plugin [installed]
                  wavpack: for wavpack plugin [installed]
                  libsndfile: for sndfile plugin [installed]
                  libcdio: for cd audio plugin [installed]
                  libcddb: for cd audio plugin [installed]
                  faad2: for AAC plugin [installed]
                  dbus: for notification daemon support (OSD current song notifications) [installed]
                  pulseaudio: for PulseAudio output plugin [installed]
                  libx11: for global hotkeys plugin [installed]
                  zlib: for Audio Overload plugin (psf, psf2, etc), GME (for vgz) [installed]
                  libsidplay: for SID player plugin
                  yasm: required to build assembly portions of ffap plugin [installed]
                  libzip: for vfs_zip plugin [installed]
Required By     : deadbeef-jack-git  deadbeef-mpris2-plugin
Optional For    : None
Conflicts With  : deadbeef
Replaces        : None
Installed Size  : 10.72 MiB
Packager        : Unknown Packager
Build Date      : Tue Sep 26 02:05:40 2017
Install Date    : Tue Sep 26 02:06:04 2017
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

Deadbeef version: r7392.6a0a9b9a-1
OS: Antergos

**Comment by Lithopsian** [comment] 2017-09-26 12:14
Looks like a duplicate of issue #1874.

**Comment by Alexey-Yakovenko** [comment] 2017-09-26 12:23
Right, thanks for spotting.

**Closed by Alexey-Yakovenko** 2017-09-26 12:23 UTC
Labels: duplicate
