### ISSUE TITLE
Double album in the play-list after dragging the directory containg *.cue and *.flac files using the file-browser plugin (x86_64 GNU/Linux)

### ISSUE THREAD

**Issue by eshchenko** [DeaDBeeF-Player/deadbeef#2000] opened 2018-04-05 21:45 UTC
### Steps to reproduce the problem
Compile fresh deadbeef from git plus the file browser plugin.
In the file browser drug a directory containing two files:
*.cue
*.flac
into the play-list area. 
### What's going on? Describe the problem in as much detail as possible.
The play-list will consist of two albums - 
First with tracks according to the *.cue file
Second - the whole album as a single track (if the flac has no meta-data).

Please look into attachment.
![deadbeef](https://user-images.githubusercontent.com/36866934/38392016-54046a76-3926-11e8-9c91-4dbd5698f8dd.png)

The *.flac information:
ffmpeg -i cdimage.flac 
gives
...
...
Input #0, flac, from 'cdimage.flac':
  Metadata:
    ENCODER         : Lavf55.22.100
  Duration: 00:52:34.00, start: 0.000000, bitrate: 873 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16

The *.cue file is a standard one produced by the ExactAudioCopy rwith the reference file chaned to flac like:  
FILE "cdimage.flac" WAVE

It looks like deadbeef takes the track data from *.cue (what is expected), 
but also scans the *.flac for the meta-data,
does not find it but adds the same album second time with the minimum information.

What is expected:
Album with tracks only (no additional track from the flac itself).

This is how the file browser works with for example 0.7.2  but not with the git-version.
And actually it is the key feature of the deadbeef player!

### Information about the software:
Please find here two files:
The output of ./configure
[configure_log.txt](https://github.com/DeaDBeeF-Player/deadbeef/files/1881866/configure_log.txt)
and the deadbeef terminal:
[deadbeef.log](https://github.com/DeaDBeeF-Player/deadbeef/files/1881867/deadbeef.log)

Deadbeef version: fresh git-version
OS: Linux Mint 17.3 64bit on Intel:
Linux HP-EliteBook-8530p 4.4.0-040400-generic #201601101930 SMP Mon Jan 11 00:32:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Dmitry

**Comment by Alexey-Yakovenko** [comment] 2018-04-06 08:28
What happens if you drag&drop the files NOT using the file browser plugin, e.g. using Finder or Nautilus?

**Comment by Alexey-Yakovenko** [comment] 2018-04-06 08:29
I think the problem is that deadbeef has changed in how it works with cuesheets, in order to support tracks+cue / multiple images+cue, and other use cases. I suppose that this has affected compatibility with file browser. Unless it's also broken when you drag&drop from external FM -- I'm afraid there's not much I can do.

**Comment by eshchenko** [comment] 2018-04-06 09:45
I can not check the external FM now as I am not at home but I did not get -
*Have you succeeded to reproduce the problem*?
Please also note that in 0.7.2  + browser plugin combination works like
expected (and I can use the same file manager libraries  for git and 0.7.2
-
this is strange as in compiling the plugin I need deadbeef.h which (I
suspect) is  version dependent - but the libraries compiled with the
git-version of deadbeef.h work with 0.7.2 if I just copy then to the proper
directory).
So I am sure that it is not a file browser plugin
problem - and from your comment I can conclude - it is the ideology change
to support this modern versions of the meta-data contents inside the
*.flac.
*That why it seems to me rather a backward compatibility issue.*
The workaround might be to proceed with the meta-data inside the *flac only
if the *.cue file is missed...  but it is too much coding...
Additional flag in the settings like read the metadata inside the *.flac
would be perfect.... but it is my dream...
As I remember the original deadbeef ideology was to look into the *.cue
only (or have I missed it).
--------------
The original 0.7.2 + file browser plugin is very convenient (for me)
combination as I can use the deadbeef in the full screen mode and I can
drag directories with no problem...
It would be a pity to lose it...
I have 2T of music archives and there was no need so far to play with all
this zoo of the the *.cue or meta-data -
the deadbeef was the only player for Unix (at least to my knowledge) which
is portable to Raspberry and is able (0.7.2 and below) to open *.wv *.flac
and *.ape albums from directory trees, playing them gap-less without any
problems!
You must be proud of this...

--------------

I do not know if it helps - but simultaneously there is a problem with
Raspberry Pi where the *.cue related procedure to add the tracks fails
unless in cue file there is a wrong reference
(*.flac extension must be change to *.wav) to the uncompressed file which
does not exist physically on the disk.
Unfortunately still there is a mystery - why at Raspberry there is no
additional album!

From this I can guess that this new scanning ideology of the *.flac has the
main priority - for some reason at Raspberry it fails and this track is not
added (OK at least total time of the album is always available), but the
file is already converted from flac to wav somewhere in the cash and the
the *cue can not find it...

But it is another story...

Best, Dmitry

**Comment by Alexey-Yakovenko** [comment] 2018-04-06 10:04
> *Have you succeeded to reproduce the problem*?

I'm not using any 3rd party plugins, so the answer is no -- I have not tried reproducing it.

> and from your comment I can conclude - it is the ideology change
to support this modern versions of the meta-data contents inside the *.flac.

This conclusion is wrong. 

> That why it seems to me rather a backward compatibility issue.

Yes, it is a backwards compat issue in a way, but it seems to also be improper deadbeef API usage issue on file browser side.

> The workaround might be to proceed with the meta-data inside the *flac only
if the *.cue file is missed...  but it is too much coding...

Deadbeef does that when you add folders to it using "Add folder" menu, etc. So apparently filebrowser does something weird, and needs a fix.

> Additional flag in the settings like read the metadata inside the *.flac
would be perfect....

Indeed, that's one use case that's not implemented yet. It's easy to add, but hard to make the right UX for it.

> As I remember the original deadbeef ideology was to look into the *.cue
only (or have I missed it).

The original implementation was that deadbeef was finding cue files automatically.
However, that turned out to be a somewhat limiting solution, as it prohibits loading individual files skipping cuesheet even if it's present, etc.

Current version allows loading cue directly, loading cue+image together, loading image without cue, and loading whole folders with autodetecting cuesheets, as well as supporting more complicated cases like handling multiple cuesheets for one album, handling tracks+cue rips, etc.

> It would be a pity to lose it...

I'm sure it's easy enough to fix it on filebrowser plugin side. We'll figure something out.

> You must be proud of this...

Thanks, I'm glad that this is useful to someone.

**Comment by Alexey-Yakovenko** [comment] 2018-04-06 21:55
Well, since it doesn't work the way it was intended -- it just indicates a bug on a specific combination of files.
I have one similar bug on my backlog, which I'm going to fix before the next release, but it seems that you're having another issue, since on your machine it's happening with **any** combination of flac+cue, is that so?

**Comment by eshchenko** [comment] 2018-04-06 23:11
By the way, have you managed to reproduce the problem?

I think, the combination of *.cue and *.flac is not a specific combination
- at least for those why is using ExactAudioCopy (it is running perfect not
only on Windows but also on Intel Linux under WINE) to backup the CD
collection it is kind of default combination.
OK, the default *.cue from ExactAudioCopy must be corrected to point to
*.flac not to to *.wav...
I am not sure about Foobar2000, I did not use it for a while, but I have
feeling it can play *.cue even if there is a reference to non-existing
*.wav, so Windows users they do not care.
I think the Foobar2000 can guess the file name just ignoring file
extensions... at list I would do like this...

As for your question - in my case* any nameofsong.flac* file in the dragged
directory (some people do cut the albums into separate tracks) is converted *as
a track nameofsong* with duration taken from flac meta-data.
Plus, if the *.cue points to the *.flac, at the top of this flac list there
is a cue generated list.

If people do not edit the original ExectAudioCopy *.cue, the deadbeef (at
Intel) return the error (cannot find or guess the file) and the *.cue based
list is not generated.
In the standard case (one CD -> one flac) it will result to a single track
with duration of the whole album taken from flac meta-data.

Hope I had explained the problem in details.

Best, Dmitry

**Comment by eshchenko** [comment] 2018-04-07 22:17
Dear Alexey

Just by chance I had found very interesting feature!
*To reproduce the problem the directory must be at the network drive*!


*If I copy the directory containing *.cue and *flac to the local drive -
everything works as expected - the tracks are taken from *.cue only.*
My network drive configuration:
External HDD is inserted into usb port of Raspberry Pi and auto-mounted
into
/media/pi/SEAGATE_3TB
on a standard way:
pi@raspberrypi:~ $ mount | grep fuse
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse
(rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/sda1 on /media/pi/SEAGATE_3TB type fuseblk
(rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)

At my Intel PC I use fuse sshfs and autofs:
more /etc/auto.sshfs
/mnt/d
-fstype=fuse,rw,nodev,nonempty,noatime,allow_other,max_read=65536,compression=no
:sshfs\#pi@192.168.0.17\:/media/pi/SEAGATE_3TB

This combination works fine with 0.7.2

At Raspberry Pi I can also start the samba server (standard way, no special
tricks).
It is interesting to note that if I mount this samba network drive on
Ubuntu PC using a standard file browser Thunar 1.6.10 (now-days modern
browsers use fuse for samba) and try to drag the directory -
only one unnumbered track without time appears named "Unknown Artist", and
this track does not start...

So at least sshfs works with all these additional tracks and standard smb
does not work.

I did not try other ways to mount (NFS etc)

Hope this information is not late and I am sorry that I did not pay
attention on the network location of my directories!
That was a great surprise to me...

Best, Dmitry

**Comment by Alexey-Yakovenko** [comment] 2018-04-08 07:25
Ah that's an interesting detail. Probably something is going on with file / directory attributes when they are on a network drive. I'll take a look. However it's still suspicious on your RPi, cause external hdd usb is not something I'd call a network drive. But in your case it seems to be a FUSE mount, which is different from normal USB external drive mounting.

**Comment by eshchenko** [comment] 2018-04-08 21:59
I am talking now about Intel client network problem. 
For this client the usb hdd connected to raspberry pi "server" is a network drive.
But you are right - the hdd is mounted to Raspberry via fuse (this is a "standard" or out-of-box way now-days).

Today I continued my studies - how sensitive this drugging problem is to the different types of network mounting.

All the network mounts are with rw permissions.
The primary mount at the raspberry was not changed, so the HDD is mounted to raspberry via fuse.

I am glad to report the the native Linux NFS 
mount
192.168.0.17:/media/pi/SEAGATE_3TB on /mnt/nfs type nfs (rw,vers=4,addr=192.168.0.17,clientaddr=192.168.0.24)
 works like a charm.
There are no double albums and no error messages.

To conclude:
1) Native UNIX  **NFS works as expected**
2) CIFS (fuse) does not work as I reported in previous comment
3) SSHFS (fuse) produces additional flac track (as in original issue) 

OK, CIFS is for Windows, DeadBeeF is for UNIX so CIFS is not relevant.
SSHFS is a very good secure and fast mount.
I had spent lot of time on SSHFS to solve the issue but no result so far...
For a local network NFS is OK, so we can consider the SSHFS via fuse like my personal problem.
In any case, I am using Raspberry as a music center, so this SSHFS problem is interesting but not critical. 
Sorry for all these troubles and misleading discussions triggered by your question - why I am still using 0.7.2 on Intel. 

Are you still interesting in git-version tracks problems on Raspberry?  

Best, Dmitry

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 08:12
I'm not really interested in RPi problems specifically, unless they are different from problems on regular PC.

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 08:13
> Sorry for all these troubles and misleading discussions triggered by your question - why I am still using 0.7.2 on Intel.

I think it is great when people stick to the stable release, and can still find time to help with testing the development version. Thanks for this find, it's an important issue to fix.

**Comment by eshchenko** [comment] 2018-04-09 11:42
OK, people usually use for NAS something like Synology or other brands
which to my knowledge are running under Linux both ARM and Intel.
I do note have commercial NAS, but can in principal play with another Intel
Linux PC ... (say arm based raspberry is already tested)

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 11:43
it shouldn't matter whether it's arm, powerpc, mips or anything else.

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 11:44
(I'm trying to get samba/cifs working on linux)

**Comment by eshchenko** [comment] 2018-04-09 11:49
How do you connect to Mac, is it also fuse?

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 11:53
> How do you connect to Mac, is it also fuse?

Finder -> Go -> Connect to server

I don't think apple is using Fuse.

I just connected to a SMB share using cifs mount, and deadbeef works correctly, no issues with cuesheet.

Then I edited the cue file to point to .wav file instead of cue -- still works fine.

Can you share a command which you're using to connect to an smb share using fuse? I'd try this too.

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 11:54
> How do you connect to Mac, is it also fuse?

To clarify a bit: I didn't connect **to** mac. I connected **from** mac.

**Comment by eshchenko** [comment] 2018-04-09 12:14
I had tried a standard way one has expect for a user:
On PC running modern Linux use your favorite file browser (Thunar in my
case), go to network, samba share must be visible in this network tree (I
am not at home so I can mix details).
All modern Linux use gvfs (fuse) for CIFS.
The mount point is hidden somewhere in /run/user/userid/gvfs/....  (as fuse
does)

Please note that the NFS which the only working for me was mounted via
classical way (sudo mount .....)

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 12:44
> On PC running modern Linux use your favorite file browser (Thunar in my
case), go to network, samba share must be visible in this network tree (I
am not at home so I can mix details).

That was the first thing I tried, but I couldn't get Nautilus to open a password protected samba share. And I could not get it to **mount** anything at all. It was just displaying the contents of public network share.

**Comment by eshchenko** [comment] 2018-04-09 13:19
This is how I do it from the terminal (RedHat) at my work:

Be sure gvfsd and gvfsd-fuse are running:
[nmrsu@CZC7378Y6G ~]$ ps aux | grep gvfsd-fuse
nmrsu     57172  0.0  0.0 489796  6236 ?        Sl   10:31   0:04
/usr/libexec/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes

If there is no gvfsd-fuse entry run:
/usr/libexec/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes

To mount samba in terminal as a normal user run:
gvfs-mount smb://windows_domain\\windows_user@ip_of_windows_PC/share

Press enter when you are asked the domain
Password: use your windows password

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 13:53
Ok, that works, the problem gets reproduced. Trying to investigate.

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 13:55
Ok. The reason it doesn't work is because GVFS is using the `:` (colon) symbol in the file share paths.
In deadbeef, this symbol is explicitly reserved for detecting network URLs and compressed folders (such as zip files). I will take some work to fix this.

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 14:39
I added a workaround for this issue. Not sure if it works for you, but works for me here.

**Comment by eshchenko** [comment] 2018-04-09 14:51
I am glad that finally you are able to reproduce and even identify the
problem!

Me personal - I hate this mount to nowhere approach! This is the modern
world... we can do nothing...

With sshfs, although it is implemented via fuse, at the top I use autofs
which mounts (links) the share to the particular directory like /mnt/d in
my case,
or the programs should see the networked directory with the normal path
(that is the idea behind autofs).
That is why I am surprised that the sshfs under autofs works partially
(original issue).
It must de identical to the local directory, that is why I found this local
vs network feature just by chance!
There is one feature with autofs - the share is disconnected after some
time (and reconnected with some delay after you try to open the
directory)...
But it should not affect...

As for the samba.
In principal, one can connect to samba the same way (after installation of
autofs there is even one template file in /etc/auto*)  and in this case the
: symbol problem is gone,
but it is too much for a normal user nowdays....

I am curious if the samba connected via autofs will behave similar to
sshfs.... so ...

**Comment by eshchenko** [comment] 2018-04-09 20:50
On Intel

uname -a
Linux HP-EliteBook-8530p 4.4.0-040400-generic #201601101930 SMP Mon Jan 11
00:32:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"

I had just made a fresh compile::

git pull
remote: Counting objects: 3, done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/DeaDBeeF-Player/deadbeef
   e0f03a6..2bc00ef  master     -> origin/master
Updating e0f03a6..2bc00ef
Fast-forward
 cueutil.c | 27 ++++++++++++++++++++++-----
 1 file changed, 22 insertions(+), 5 deletions(-)

./configure --prefix=/home/eshchenko/development/
make -j4
make install
cd ~/development/bin
./deadbeef

Plugins are loaded as usual:
...
selected output plugin: ALSA output plugin
INFO: from file /home/eshchenko/.config/deadbeef/playlists/0.dbpl
convgui: gtkui plugin not found
plugin Converter GTK3 UI failed to connect to dependencies, deactivated.
fb api2
plugin Playlist browser GTK3 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK3 UI failed to connect to dependencies, deactivated.
resume: track -1 pos -1.000000 playlist 0
gtkui plugin compiled for gtk version: 2.24.23
connecting button tray signals
gtk style:
style "deadbeef-filebrowser" {
}
widget "*.deadbeef_filebrowser_treeview" style "deadbeef-filebrowser"

The samba share is seem in Thunar 1.6.10 like:
smb://raspberrypi/d/MUSIC/Aquarium Diskografy/БГ-Аудиофилия/

In terminal the share is seen like:
dir
/run/user/1000/gvfs/smb-share\:server\=raspberrypi\,share\=d/MUSIC/Aquarium\
Diskografy/БГ-Аудиофилия/1981\ -\ Треугольник\ \[Аудиофилия\ -\ 2007\]/
cdimage.ap  cdimage.cue  cdimage.flac  cdimage_wav.cue

Drugging this directory from Thunar still results to "Unknown Artist"


​
There are no errors, log window is empty

Best, Dmitry

**Comment by Alexey-Yakovenko** [comment] 2018-04-09 21:05
I'll try a similar path tomorrow

**Comment by Alexey-Yakovenko** [comment] 2018-04-10 09:44
I can't reproduce the issue with the information you provided.
Please share your cdimage.cue file, this might help.

**Comment by eshchenko** [comment] 2018-04-10 09:57
Unfortunately I can do it only in the evening.... but as I told you, local
directory is fine, nfs is also fine.... so *.cue works like expected for
local directory and for "classical" NFS mount.
Also 0.7.2 is fine even for networked SSHFS location. Samba always fails.
Also the art work is OK, and the *.cue was made by ExactAudioCopy 0.9? .
So please wait until evening...

On Tue, Apr 10, 2018 at 11:44 AM, Alexey Yakovenko <notifications@github.com

**Comment by Alexey-Yakovenko** [comment] 2018-04-10 10:38
well, the only difference between the local directory and the remote share is the path, and it's supposed to work. I created the path using `mkdir -p 'run/user/1000/gvfs/smb-share:server=raspberrypi,share=d/MUSIC/Aquarium Diskografy/БГ-Аудиофилия/1981 - Треугольник [Аудиофилия - 2007]'`, and dragging&dropping this folder, or using Add Folder(s) menu, both work fine with my files, so I suppose the issue may be something else, and may be related to the contents of the cue file.

**Comment by eshchenko** [comment] 2018-04-10 11:11
OK, let me do similar in the evening (I do not have remote access to my
home network) as well as sending you the cue, but what you say is exactly
what I also was sure...
The real NFS path also works without problem... so basically both NFS (for
me) and Samba (for you, with the dir -p parent mapping trick or also direct
drugging?) are working as expected from a general knowledge... So 99.9% if
I do similar dir -p trick it will work for me too.
Please also note that the original issue (under SSHFS) is reproducible for
me with any *.cue (not only with this particular one I will send you in ~ 6
hours) and also with *.cue + *.ape combination.


On Tue, Apr 10, 2018 at 12:38 PM, Alexey Yakovenko <notifications@github.com

**Comment by eshchenko** [comment] 2018-04-10 16:46
Please find here attached cue plus cue and flac at
https://polybox.ethz.ch/index.php/s/aBogvqNTuImcgeR
Let me know to delete the link

On Tue, Apr 10, 2018 at 12:38 PM, Alexey Yakovenko <notifications@github.com

**Comment by Alexey-Yakovenko** [comment] 2018-04-10 17:39
got the file, thanks

**Comment by Alexey-Yakovenko** [comment] 2018-04-10 17:42
I still don't have any problems with this cue, even with the path similar to fuse mount point. I guess I'll need to make a real fuse mount. Stay tuned.

**Comment by Alexey-Yakovenko** [comment] 2018-04-10 17:55
I can't make gvfs-mount or nautilus to mount a SMB share located on a mac, so will need to try on another computer tomorrow.

**Comment by Alexey-Yakovenko** [comment] 2018-04-11 08:26
I was able to reproduce the problem on ubuntu.
Dragging directly from smb:// path from Thunar - doesn't really work correctly, and this is fine (not expected to work).
Dragging from /run/user/... folder: works, but can't detect that cue and flac are related.

**Comment by Alexey-Yakovenko** [comment] 2018-04-11 09:13
So the 2nd issue, in addition to colons and other "special" characters in folder names, turned out to be caused by GVFS not setting file type correctly for any files, so they are all DT_UNKNOWN, and deadbeef was not able to find them. Seems to work ok now.

**Comment by eshchenko** [comment] 2018-04-11 20:42
Let me summarize what is working on my Linux Mint 17.3 (clone of Ubuntu
14.04) Intel 64:
NFS is and was fine
Fuse related:
1) sshfs (fuse) what was the original issue works now as expected in all
possible combinations to add the directory to the play-list (file-browser
plugin, dragging from the Thunar or Nautilus, native deadbeef menu:
File/Add Folder(s))
So my original problem solved.
2) gvfs cifs (fuse) ones the share was mounted using Thunar or Nautilus
works as expected with you native menu File -> Add Folders, but does not
work with dragging from Thunar/Nautilus or from the file-browser plugin.
In last two cases there is "Unknown Artist" unplayable track only.


On Wed, Apr 11, 2018 at 11:13 AM, Alexey Yakovenko <notifications@github.com

**Comment by Alexey-Yakovenko** [comment] 2018-04-11 20:49
> 2) gvfs cifs (fuse) ones the share was mounted using Thunar or Nautilus
works as expected with you native menu File -> Add Folders, but does not
work with dragging from Thunar/Nautilus or from the file-browser plugin.
In last two cases there is "Unknown Artist" unplayable track only.

Hmm.. it works for me though, with your files, with Thunar, and mounting using fuse.
Are you sure you're running the latest build?

**Comment by Alexey-Yakovenko** [comment] 2018-04-11 20:50
And please, to keep the conversation on point -- please DON'T post about what is working.
It is confusing this way. Please only post relevant information about what ISN'T working.

**Comment by eshchenko** [comment] 2018-04-11 21:09
I did the fresh built:
git status
On branch master
git pull
Already up-to-date.


On Wed, Apr 11, 2018 at 10:50 PM, Alexey Yakovenko <notifications@github.com

**Comment by eshchenko** [comment] 2018-04-11 21:11
OK, I thought it is useful to write what was changed or new.
sshfs is new

On Wed, Apr 11, 2018 at 10:50 PM, Alexey Yakovenko <notifications@github.com

**Comment by Alexey-Yakovenko** [comment] 2018-04-11 22:00
It is useful, but it is not clear from your posts what is new and what's not.
I don't fully understand - did the fix change anything for you or not?

**Comment by Alexey-Yakovenko** [comment] 2018-04-11 22:02
So if I understand correctly what you're saying:

dragndrop still broken, but adding folders using menu is working. I will recheck this case tomorrow.

**Comment by eshchenko** [comment] 2018-04-11 22:10
What was changed:
sshfs - now as expected

As for the CIFS, unfortunately I did not try before the native File/Add
Folder(s) menu in version just before the last fix,
but the *dragging* *with* *fb-plugin*, *Thunar* and Nautilus (actually
before I did not try Nautilus)* did not change (not working)*


On Thu, Apr 12, 2018 at 12:01 AM, Alexey Yakovenko <notifications@github.com

**Comment by eshchenko** [comment] 2018-04-11 22:12
For CIFS dragndrop still broken, but adding folders using menu is working
For SSHFS everything is working

On Thu, Apr 12, 2018 at 12:02 AM, Alexey Yakovenko <notifications@github.com

**Comment by eshchenko** [comment] 2018-04-11 23:04
If you follow the thread, *the original issue was about sshfs* (I am using
and found this double album issue).

Actually I included the CIFS because after I found the reason - *network* I
realized that this is *fuse *and made study - what exactly works and what
doesn't.
So this thread is basically about the fuse and how it is implemented.
Moreover, following you comment that you are not interesting in Raspberry
unless the problem is related to PC, I always try default situations and
configurations to make this work useful for an ordinary PC user...
and CIFS is more common (to my knowledge) in PC world...
For example, at home network I have to support CIFS for the rest of my
family (Windows).

Sorry for all these misleadings...

Dmitry

So better to say other way around - why I still keep testing CIFS...

And sshfs is nice, I am so glad you solved the sshfs problem, also it was a
side effect of your fight with CIFS, many thanks!


On Thu, Apr 12, 2018 at 12:18 AM, Alexey Yakovenko <notifications@github.com

**Comment by Alexey-Yakovenko** [comment] 2018-04-12 09:16
I just tried again to drag-drop the folder from a cifs volume mounted using GVFS, in Thunar.
Everything works fine, no duplicate entries, just the tracks defined in the cuesheet.

Writing the steps in more detail, in case we're doing something differently:

1. mount the volume: gvfs-mount smb://username@server/share
2. open deadbeef and thunar
3. in thunar, go to the root `/`
4. drag-n-drop the /run folder onto deadbeef window

The result is on the screenshot
![image](https://user-images.githubusercontent.com/1895698/38667889-f844571a-3e42-11e8-9a9c-7e658f5fab76.png)

**Comment by Alexey-Yakovenko** [comment] 2018-04-12 09:18
Closing the issue since I can't reproduce the problem anymore.
Will reopen if you can find a new way to cause it.

**Closed by Alexey-Yakovenko** 2018-04-12 09:18 UTC

**Comment by eshchenko** [comment] 2018-04-12 22:35
Sorry for late response, I just appeared at home.

Thanks for sending me the screen-short and *explanation how you open the
share*.

I can confirm that *the way you are doing works also for me* - click inside
the  /run/ then follow the tree to /run..../top_of_directory_of_interest
and then dragging the directory
In my case the working address or path to the directory (top string in
Thunar) is

*/run/user/1000/gvfs/smb-share:server=192.168.0.17,share=d,user=pi/MUSIC/Aquarium
Diskografy/БГ-Аудиофилия/1982 - Табу [Аудиофилия - 2007]*

But a general user does not know about the location of the gvfs share (as
well as about the terminal way to mount).

Please note that at the very bottom left of the screen-shot you sent is a
network drive (*just below NETWORK*, name is cut but I can see the "Inject"
or "Disconnect" symbol).
This share is the result of your
gvfs-mount
action in terminal.

This presentation of a network drive is similar to a Windows Explorrer.
Most users  (and me too)  will click on this (cut on your screen-shot)
network drive and follow the tree.
The path to the directory is different from /run/....:

*smb://pi@192.168.0.17/d/MUSIC/Aquarium%20Diskografy/БГ-Аудиофилия/1981%20-%20
<http://pi@192.168.0.17/d/MUSIC/Aquarium%20Diskografy/%D0%91%D0%93-%D0%90%D1%83%D0%B4%D0%B8%D0%BE%D1%84%D0%B8%D0%BB%D0%B8%D1%8F/1981%20-%20>Треугольник%20%5BАудиофилия%20-%202007%5D*

If I drag this way - it *does not work *and the tracks are not shown.
Please try and you will see the difference.

Best, Dmitry
____
OK, imagine you do not know secret gvfs-mount command

*Similar not-working mount you can get by clicking on NETWORK*
As you ones mentioned, for some reason, the non-public shares are not
visible, in my case only server path is seen like:

smb://raspberrypi/

but if you know the name of the share you can continue this path by typing
(in my case)

smb://raspberrypi/d

by pressing enter a dialog window about user,workgroup and password appear
and the directory of interest will be presented like:



*smb://raspberrypi/d/MUSIC/Aquarium Diskografy/БГ-Аудиофилия/1981 -
Треугольник [Аудиофилия - 2007]/*
Hope now we understand the problem....



On Thu, Apr 12, 2018 at 11:16 AM, Alexey Yakovenko <notifications@github.com

**Comment by Alexey-Yakovenko** [comment] 2018-04-13 07:02
smb:// paths and other paths visible in linux file managers are not supported in deadbeef without plugins, and not supposed to work.

there's this plugin for gvfs support https://github.com/asv/deadbeef-gvfs
but I don't know whether it works at all.

**Comment by eshchenko** [comment] 2018-04-14 20:01
OK, I can confirm that at least everything works using your File, Add
Folders(s) and dragging from "classical" mounts.
Also, I solved the Raspberry Pi cue problem (by changing the default
startup automount by the classical fstab approach), so one issue was solved
by itself without opening it...
So, I can use development version with network drivers at all my systems.
Thanks.
