### ISSUE TITLE
Slow FPS update of application window with intermittent fast bursts

### ISSUE THREAD

**Issue by Logicwax** [DeaDBeeF-Player/deadbeef#2838] opened 2022-08-03 02:19 UTC
### What's going on? Describe the problem in as much detail as possible.
 
Using the VU meter, spectrum, or even music spectrum all produce a slow choppy experience of window updates of those plugins.  This is even after tweaking all the FFT settings in spectrum and changing intervals.    It seems the application is almost throttled by something that won't let it draw updates faster than 10 or so frames per second.    I'm assuming this might be related to the big changes in gnome with how fast updates are managed with mouse input and such?  Just an idea, but I heard there was some big changes with respect to the frame rate of updates with windows.

The thing is, I know it's not a limitation of my hardware keeping up, because it will have sometime intermittent bursts of running really fast (animating the spectrum fft really fast, drawing the vu meters at a rate that matches the music, etc) that can last for almost 10 seconds or so.    To cause these bursts is a little tricky.   I first noticed it If I minimize the application for some time and then restore it.   but that isn't 100% every time.   also sometimes while also moving it to another desktop display it will cause these bursts to happen.   When it does happen, it feels just like deadbeef on windows (or foobar2000 for that matter).    Otherwise, deadbeef just runs at this really slow rate where the spectrum/vu meters can barely track the music.

### Information about the software:

Deadbeef version: 1.9.1
OS: Ubuntu 22.04 / Jammy.   GNOME 42.2 + wayland

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-03 07:22
Could you please try checking whether the same problem occurs when running 1.9.2 beta 1?
It's likely that nothing will change, but there were quite a few changes to the visualization code, so there's a chance.

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-03 07:23
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.9/deadbeef-static_1.9.2-beta1-1_x86_64.tar.bz2/download

**Comment by Logicwax** [comment] 2022-08-03 11:04
No difference, runs the same.

**Comment by Logicwax** [comment] 2022-08-03 11:58
Here's another datapoint:   I booted into X11 on the same machine and it made no difference.

Then I went over to my older laptop, which has ubuntu 20.04.4 LTS, with GNOME 3.36.8, and deadbeef runs fast!  (no slow framerate.....spectrum is high FPS!).     I tested it on both wayland and X11, and they are both the same (Fast)


so it would seem its either something having to do with the new ubuntu version, or GNOME 42, or both.

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-03 12:34
Did you check CPU/GPU load on ubuntu 22.04, when deadbeef is running with visualizations?
It sounds like it could have been a performance regression in GTK, or maybe a graphics driver, or maybe some kind of a rendering synchronization bug got introduced, and caused everything to glitch..

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-03 14:45
another reason for such behavior could be that ubuntu22.04 introduced a change in the audio system.
Try changing between alsa / pulse, and maybe try the pipewire plugin.
https://github.com/saivert/ddb_output_pw

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-03 19:45
Found this issue already filed to ubuntu devs:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1973434

It promises to resolve the problem in the next update, and there's a proposed solution.
Basically, it says this:

> Edit /etc/default/grub, and append "intel_iommu=off" to GRUB_CMDLINE_LINUX_DEFAULT. Then save, and run "sudo update-grub" and reboot.

**Comment by Logicwax** [comment] 2022-08-04 01:09
> another reason for such behavior could be that ubuntu22.04 introduced a change in the audio system. Try changing between alsa / pulse, and maybe try the pipewire plugin. https://github.com/saivert/ddb_output_pw

Switching to ALSA (as an output plugin) fixed the problem completely!    Thank you!    I wonder why pulse audio has that issue?   I want to clarify that when using pulseaudio as the plugin, the audio sounds fine.   There's no lagging or audio effects (and no CPU spikes or anything).   It seems that selecting pulseaudio just has the side effect of slowing down the animations of VU/spectrum plugins.   I was under the impression that Ubuntu wasn't using pipewire yet.

**Comment by Logicwax** [comment] 2022-08-04 01:39
it would be nice to get pulseaudio output plugin fixed though, since using ALSA causes a skip/cut-out when unpausing a track.   It's not as graceful as a resume of audio.

**Comment by Logicwax** [comment] 2022-08-04 01:40
@Oleksiy-Yakovenko do you have a binary release of the pipewire plugin?

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-04 05:31
I don't know exactly why pulse audio behaves this way on your machine, but I can presume that it uses a very large sound buffer.
See the issue #1183 for more information.

Sorry, I don't have a binary of the pipewire plugin.

**Comment by Logicwax** [comment] 2022-08-04 10:08
yup, changing pulseaudio buffer to something like 128 fixes the problem.    Anything high up in the 100s it starts to lag.

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-04 10:23
duplicate of #1183

**Closed by Oleksiy-Yakovenko** 2022-08-04 10:23 UTC
Labels: GTKUI

**Comment by Logicwax** [comment] 2022-08-04 10:34
actually, something weird just happened.   I went to return pulse audio buffer back to its original high settings (4096 or 8192) and now its still updating at a fast rate.    

then I realized, that I switched to my airpods that are connected via bluetooth.    Turns out, that this problem only exists when I'm using my normal audio output.   but switching to bluetooth airpods the issue goes away.

**Comment by Logicwax** [comment] 2022-08-04 10:38
I would have no problem keeping pulseaudio buffer to 128, but it makes track switching stall the entire OS (mouse cursor and all) for a 2 seconds when changing to the next track and doing gapless playback.      In order to counter-act that, I need to increase the buffer, which makes the UI lag.    I guess trade one thing for the other.

It also doesn't make much sense that switching to airpods fixes the issue.   It still is routing through pulseaudio....

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-04 10:47
You should be able to set the pulseaudio buffer size to something larger than 128, but lower than 4096. Setting it too low will negatively affect performance. values around 1000-2000 should work fine.

**Comment by Logicwax** [comment] 2022-08-04 10:50
1000-2000 causes the slow update problem though (unless im listening on my airpods).    I need to have it around 128 for fast update.

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-04 10:57
The buffer needs to be 2940 bytes in size to make visualization very smooth at 60 fps.
Deadbeef runs visualizations at 30 fps, and this means the buffer can be twice as large --  5880 bytes.
(Numbers are given for 44100 16 bit stereo stream).

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-04 10:59
It is quite likely that pulseaudio itself decides to override the values specified by deadbeef, and this causes problems.
I don't know how to solve this, but you could try running [another version of pulse audio plugin](http://sourceforge.net/projects/deadbeef/files/plugins/x86_64/ddb_output_pulse2-v1.2-linux-x86_64.zip/download) -- maybe it'll work better

**Comment by Logicwax** [comment] 2022-08-04 11:07
v2 of that plugin is even worse, much worse (extremely slow updating).

It sounds like pulseaudio is blocking on the thread (but for some reason doesnt do this for bluetooth audio).

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-04 11:11
You could try to add this to `/etc/pulse/daemon.conf`

```
default-fragment-size-msec = 33
```

But honestly I've no idea whether it would work. It's a known issue with pulse audio, and I'm not really an expert with it.

**Comment by Logicwax** [comment] 2022-08-18 23:51
something weird happened 2 weeks ago.    I was listening on my airpods, via pulseaudio output, and my airpods finally ran their battery down.    This caused a disconnect, and from that point forward the pulseaudio output worked perfectly with my normal speakers.   It worked for 1.5 weeks, and I didn't touch any settings, hoping it would stay like that.     

Yesterday, it finally broke again.  and I can't seem to reproduce it again (well, I haven't ran my batteries down again, but I have intentionally tried to bring them out of bluetooth range).   So now I'm back to where I started.

I also noticed that using the ALSA output doesn't result in as nice as performance as the pulseaudio + airpords/bluetooth audio (it still doesn't get me the frame rate that I get when using pulseaudio and the airpods).   I also noticed that using the NULL output plugin results in speeding through the whole song rapidly and updating the interface (oscilliscope, vu meters, spectrum) at extremely fast framerate.    This leads me to think that deadbeaf's GUI system is tightly coupled to the audio output system.

It's unfortunate that I can't get as good UI performance with my speakers that I can get with bluetooth audio / airpods.

**Comment by Logicwax** [comment] 2022-08-18 23:58
actually, i just uncovered something!

with pulseaudio enabled, deadbeef open and updating slowly, if I simultaneously open up the gnome sound setttings panel then deadbeef will update really fast!    As long as I keep the dialog window open and even minimizing it still works.   I just have to have the gnome sound settings dialog window open and pulseaudio will behave nicely.

so what could that mean?

**Comment by Oleksiy-Yakovenko** [comment] 2022-08-19 06:03
> so what could that mean?

This means, that you found exactly the same thing, that was found by another user in 2015, as reported in the #1183:

```
animation will stutter, unless pavucontrol is launched/running in the background
```

**Comment by Logicwax** [comment] 2022-08-19 23:34
true, although it eventually starts going back to a stutter.   closing and re-opening pavucontrol only works a handful more times before being completely ineffective.   This makes deadbeef not that useful with pulseaudio.

Is there a way to switch from synchronous writes to PA (pa_simple_write()) to async?

**Comment by Logicwax** [comment] 2022-08-20 00:33
my hunch is that it's related to the output device signal meter shown in pavucontrol.   When pavucontrol is open, there is code that is looking at the current audio levels and displaying it on a bar that moves left to right under the select "output device" in pavucontrol dialog.   Maybe looking at what that code does may be what deadbeef needs to do.

**Comment by Logicwax** [comment] 2022-10-04 23:46
due to some recent ubuntu update (I'm assuming), `ddb_output_pulse2` plugin is working wonderfully (make sure to set buffer to 1 - 5ms or so).
