### ISSUE TITLE
"Auto-resize columns to fit the window" is broken

### ISSUE THREAD

**Issue by Hasshu** [DeaDBeeF-Player/deadbeef#2414] opened 2020-07-20 11:04 UTC
Alright, [it](https://github.com/DeaDBeeF-Player/deadbeef/issues/1464#issuecomment-638849237) turned out to be reproducible.

### Steps to reproduce the problem

1. Run deadbeef with a clean config, with GTK3 UI
1. Maximize the window
1. Enable column autoresizing
1. Restart deadbeef
1. Observe columns become larger on every restart

### What's going on? Describe the problem in as much detail as possible.

The "Auto-resize columns to fit the window" function behaves erratically, which makes it unusable.

### Information about the software:

Deadbeef version: 1.8.4 (portable build)
OS: Fedora 32 (KDE Plasma 5.18.5)

**Comment by Hasshu** [comment] 2020-08-07 10:46
One more reason to revive the [Qt plugin](/DeaDBeeF-Player/deadbeef/issues/1035), methinks.

**Comment by Alexey-Yakovenko** [comment] 2020-08-07 15:49
This is not a GTK issue though

**Comment by Hasshu** [comment] 2020-08-07 17:53
Just an aside.

**Comment by Alexey-Yakovenko** [comment] 2020-08-07 17:58
Not sure why is it relevant to this bug report.

**Comment by Alexey-Yakovenko** [comment] 2020-08-07 18:22
FYI: investigation of this bug report is delayed, since I'm currently running macOS Big Sur, which doesn't yet support virtualbox, and GTK3 doesn't work on it either, so I temporarily can't run deadbeef with GTK UI. It will probably take a couple of months till I can get this reproduced and fixed.

**Comment by Hasshu** [comment] 2020-08-07 19:16
> Not sure why is it relevant to this bug report.

I thought the issue is directly related to GTK, at first. And I'm just not fond of this toolkit in general.

> It will probably take a couple of months till I can get this reproduced and fixed.

I see.

**Comment by Alexey-Yakovenko** [comment] 2020-08-07 19:40
> I thought the issue is directly related to GTK, at first.

Playlist (and its columns) is a custom view, not implemented by GTK.
Although, it seems that GTK update managed to break my code smh.
This is not uncommon. **ALL** toolkit do this, and it's not uncommon at all.

> And I'm just not fond of this toolkit in general.

There's a 3rd party Qt plugin in development, which you're welcome to use, if it suits you.

**Comment by Alexey-Yakovenko** [comment] 2020-08-07 19:43
https://github.com/kuba160/ddb_gui_qt5

**Comment by Hasshu** [comment] 2020-08-08 07:31
> This is not uncommon. **ALL** toolkits do this, and it's not uncommon at all.

Fair enough.

And thanks for the link.

**Comment by kuba160** [comment] 2020-08-09 11:17
> https://github.com/kuba160/ddb_gui_qt5

I might return to that project soon. Currently, `master` branch is just a port of original qt gui with fixes to make it work with qt5. After that I created new branch `qmake` and started modifying code. I wanted to have dynamic widgets similar to gtk one, but this required many changes. Having no prior experience with C++/Qt makes it a bit harder :D

**Comment by Alexey-Yakovenko** [comment] 2020-09-18 19:03
Not reproducible on mac + gtk3.24.21

**Comment by Hasshu** [comment] 2020-09-19 09:49
Just tested both the latest nightly build from SourceForge (dated 2020-09-13) and the packaged version from RPM Fusion (v1.8.4) — nothing has changed. GTK3 is at v3.24.23.

**Comment by Alexey-Yakovenko** [comment] 2020-11-25 21:28
Confirmed: reproducible as described, ubuntu 20.04.1, gtk 3.24.20

**Comment by Alexey-Yakovenko** [comment] 2020-11-25 21:51
Good news, this bug should be relatively easy to fix, and it seems to have a workaround.

The workaround:

1. Delete the columns configuration from deadbeef config
2. Start deadbeef, don't maximize the window
3. Enable column autoresizing
4. resize the window once. maximizing is also ok

After this, the config will be in sync with the real window geometry, and the problem won't be happening anymore.

It only happens if:

1. it's the first run, and the config wasn't initialized yet
2. the window is maximized and autoresize mode is enabled

**Comment by Alexey-Yakovenko** [comment] 2020-11-26 22:16
So what I found:

When the window is created and resized or maximized, but it's not visible yet: the widgets in the window will get one or more "configure" calls, and this is where column autoresize is performed. But we don't know if that's some intermediate/default size, or the final one which we need.

Then the widgets get "realize" call (gtk term) and another configure call. This is the first configure call where we are getting the correct final widget size (after maximizing etc).

When I added the code to take this into account, everything worked.
Going to test on the older GTK and GTK2 in a moment. Hopefully it will work the same.

**Comment by Alexey-Yakovenko** [comment] 2020-11-26 22:23
Now it doesn't quite work correctly in previous gtk version. So needs a bit more work. But at least the problem is better understood.

**Comment by Alexey-Yakovenko** [comment] 2020-11-26 22:58
Added more hacks to make it work on older GTK, still need to verify on the newer one again, but I'm out of time for today.

**Closed** 2020-11-26 22:57 UTC
Labels: Bug, GTKUI

**Comment by Hasshu** [comment] 2020-11-27 08:37
@Alexey-Yakovenko Take your time. And thank you for your hard work.

**Comment by Alexey-Yakovenko** [comment] 2020-11-27 18:57
Confirmed that the bug has been fixed, and autoresizing + maximized window now works correctly on both older and newer GTK versions.
