### ISSUE TITLE
UI keeps getting broken

### ISSUE THREAD

**Issue by AcarBurak** [DeaDBeeF-Player/deadbeef#2417] opened 2020-07-28 08:57 UTC
Because of the below part in my config file deadbeef UI gets broken (see the screenshot) seemingly by inflated object sizes though I don't know what causes this.

`gtkui.columns.playlist [{"title":"Album Art","id":"8","format":"","sort_format":"","size":"39591","align":"0","color_override":"0","color":"#ff2f2f2f"},{"title":"Pl","id":"1","format":"","sort_format":"","size":"13597","align":"0","color_override":"0","color":"#ffffffff"},{"title":"Track No.","id":"-1","format":"%track number%","sort_format":"","size":"13197","align":"1","color_override":"0","color":"#ff000000"},{"title":"Title","id":"-1","format":"%title%","sort_format":"","size":"113413","align":"0","color_override":"0","color":"#ff000000"},{"title":"Duration","id":"-1","format":"%length%","sort_format":"","size":"23508","align":"0","color_override":"0","color":"#ff000000"}]
`

This has been happening for quite some time, perhaps after a GTK3 update, I'm not sure. Then I would use another app and some time later come back to deadbeef and it would work again. This time it has persisted.

Just removing the above part has solved the issue (for the time being). My new version of that part is auto-generated by deadbeef and I've just added the Album Art column which is the only reason I've got deadbeef in the first place (as the only GTK related package in my system):

`gtkui.columns.playlist [{"title":"Album Art","id":"8","format":"","sort_format":"","size":"100","align":"0","color_override":"0","color":"#ffeeeeec"},{"title":"♫","id":"1","format":"%playstatus%","sort_format":"","size":"49","align":"0","color_override":"0","color":"#ff000000"},{"title":"Artist / Album","id":"-1","format":"$if(%artist%,%artist%,Unknown Artist)[ - %album%]","sort_format":"","size":"146","align":"0","color_override":"0","color":"#ff000000"},{"title":"Track No.","id":"-1","format":"%tracknumber%","sort_format":"","size":"49","align":"1","color_override":"0","color":"#ff000000"},{"title":"Title","id":"-1","format":"%title%","sort_format":"","size":"146","align":"0","color_override":"0","color":"#ff000000"},{"title":"Duration","id":"-1","format":"%length%","sort_format":"","size":"49","align":"0","color_override":"0","color":"#ff000000"}]
`

Deadbeef version: 1.8.4
OS: Arch/Fluxbox

![deadbeef](https://user-images.githubusercontent.com/47071810/88642377-15256e80-d0c9-11ea-8e1c-2aa3a4404b4d.jpg)

And this is the terminal output:

> starting deadbeef 1.8.4
server_start
searching for GUI plugins in /home/burak/.local/lib64/deadbeef
searching for GUI plugins in /home/burak/.local/lib/deadbeef
searching for GUI plugins in /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 54 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/burak/.local/lib64/deadbeef
loading plugins from /home/burak/.local/lib/deadbeef
loading plugins from /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 54 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alac.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk2.so
dlopen error: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
trying /usr/lib/deadbeef/converter_gtk2.fallback.so...
plugin converter_gtk2.so not found or failed to load
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/ddb_soundtouch.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/ffmpeg.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/in_sc68.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mp3.so
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
dlopen error: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
trying /usr/lib/deadbeef/pltbrowser_gtk2.fallback.so...
plugin pltbrowser_gtk2.so not found or failed to load
loading plugin /usr/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib/deadbeef/psf.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/rg_scanner.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
dlopen error: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
trying /usr/lib/deadbeef/shellexecui_gtk2.fallback.so...
plugin shellexecui_gtk2.so not found or failed to load
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
loading plugin /usr/lib/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Soundtouch
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin OSS output plugin
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
selected output plugin: ALSA output plugin
INFO: from file /home/burak/.config/deadbeef/playlists/0.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/1.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/2.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/3.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/4.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/5.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/6.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/7.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/8.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/9.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/10.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/11.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/12.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/13.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/14.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/15.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/16.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/17.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/18.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/19.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/20.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/21.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/22.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/23.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/24.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/25.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/26.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/27.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/28.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/29.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/30.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/31.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/32.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/33.dbpl
INFO: from file /home/burak/.config/deadbeef/playlists/34.dbpl
resume: track 42 pos 28.235556 playlist 7
gtkui plugin compiled for gtk version: 3.24.21
quitting gtk
gtkui_stop completed
gui plugin has quit; waiting for mainloop thread to finish
plug_disconnect_all
plug_unload_all
stopping GTK3 user interface...
quitting gtk
stopping Adplug player...
stopping ALSA output plugin...
stopping Album Artwork...
stopping Converter...
stopping dts decoder...
stopping DUMB module player...
stopping Game-Music-Emu player...
stopping Hotkey manager...
stopping SC68 player (Atari ST SNDH YM2149)...
stopping last.fm scrobbler...
stopping MusePack decoder...
stopping OSD Notify...
stopping Null output plugin...
stopping OSS output plugin...
stopping PSF player using Audio Overload SDK...
stopping PulseAudio output plugin...
stopping Shell commands...
stopping SID player...
stopping WAV/PCM player...
stopping SuperEQ...
stopping tta decoder...
stopping cURL vfs...
stopping Ogg Vorbis decoder...
stopping VTX player...
stopping WildMidi player...
stopping FFMPEG audio player...
stopped all plugins
all plugins had been unloaded
messagepump_free
plug_cleanup
logger_free
hej-hej!

**Comment by Alexey-Yakovenko** [comment] 2020-07-28 09:05
This seems related to another report #2414
Try disabling column autoresizing.

**Comment by AcarBurak** [comment] 2020-07-28 09:07
All right, thanks.

**Comment by AcarBurak** [comment] 2020-07-28 09:16
No, that doesn't work.

**Comment by Alexey-Yakovenko** [comment] 2020-07-28 09:25
Doesn't work how? it's the only thing that changes column width, which is clearly what's happening for you.
You need to disable column autoresizing, and manually resize the columns to the right size. Then they will stay at the size you set.

If this really doesn't help -- I don't have any other bright ideas what's going on, and you'll need to wait until I investigate.
Are you also using KDE, like the person from the other issue?

**Comment by AcarBurak** [comment] 2020-07-28 09:29
Sorry, I've forgot to manually adjust and now was doing it. It works, seemingly. I'm on Fluxbox, not KDE.

**Comment by Alexey-Yakovenko** [comment] 2020-07-28 10:01
Duplicate of #2414

**Closed by Alexey-Yakovenko** 2020-07-28 10:01 UTC
Labels: Triage
