### ISSUE TITLE
Icy streams randomly skipped or deadlocking inside of vfs_curl

### ISSUE THREAD

**Issue by ptkovsky** [DeaDBeeF-Player/deadbeef#2235] opened 2019-10-08 17:27 UTC
### Steps to reproduce the problem
1. Add some tracks to the playlist. The test playlist consists of online radio stations' addresses:
```
#
http://192.111.140.6:9686/stream
http://185.80.220.12:8154/stream
http://ice4.somafm.com/spacestation-128-aac
http://ice4.somafm.com/deepspaceone-128-aac
http://ice4.somafm.com/dronezone-128-aac
http://ice4.somafm.com/groovesalad-256-mp3
http://ice4.somafm.com/gsclassic-128-aac
http://ice4.somafm.com/cliqhop-256-mp3
http://185.72.246.9:8000/stream.mp3
http://147.175.61.100:8000/
http://147.175.61.55:8000/
http://ice4.somafm.com/fluid-128-aac
http://ice4.somafm.com/thetrip-128-aac
```
2. Now just try to play them one by one.

### What's going on? Describe the problem in as much detail as possible.
So there is an issue with the specific playlist of online radio stations, where the player constantly skips tracks. It looks like this: when you start playing one, it instantly skips to the second one. Other player was tested too and it doesn't have this problem.

### Information about the software:
Deadbeef version: b0cdeb0.
OS: macOS 10.15.

**Comment by Alexey-Yakovenko** [comment] 2019-10-09 11:32
I could not reproduce the issue in the same manner as you described.
There was no constantly skipping tracks.
One stream got skipped once after trying to reproduce the issue for several minutes.
Although this may be sensitive to internet connection.

However, while trying to reproduce this, the player deadlocked twice.

**Comment by ptkovsky** [comment] 2019-10-09 18:47
Alexey, hi and thank you so much for acknowledging the issue and trying to reproduce it. I agree with you, let's say that it is not constant but rather regular behavior, especially in longer periods of listening.

Player also sometimes skips playlist entries when track automatically cycles to the next one, when listening to the same station.

Deadlocking, sure, the term sounds legit. As you already noticed, I also described similar behavior in https://github.com/DeaDBeeF-Player/deadbeef/issues/2237.

**Comment by Alexey-Yakovenko** [comment] 2019-10-09 19:00
Yes, it deadlocked on the same URL as written in #2237
I will be debugging it some time in the future. Can't give any timeline yet, since I'll be away from computer for at least a week, and then I'm also super busy at work.

**Comment by ptkovsky** [comment] 2019-10-09 19:13
Alexey, no worries, this is rather old bug, at least from my perspective. I am willing to wait just a little bit more if needed. Thanks again for your efforts.

**Comment by Alexey-Yakovenko** [comment] 2019-11-11 19:56
I think this is fixed now.

**Closed by Alexey-Yakovenko** 2019-11-11 19:56 UTC
Labels: Bug

**Comment by ptkovsky** [comment] 2019-11-11 20:50
Thanks, I observed few skips still in place here and there when constantly spamming channel switching, but nothing serious. This issue really needs more testing, will report later. For me, this issue was previously most annoying in the long run where you sticked to listening one channel and then it skiped to the next just after playing few tracks and particularly in the moment when a new track starts playing. So in the end, after some time you realize that you are listening to the next playlist entry (channel) instead of the original one.

**Comment by Alexey-Yakovenko** [comment] 2019-11-11 20:52
Hmm.. that is not how you originally described the issue, or at least not how I understood it, and not what I was fixing.

I think what you experienced is a network timeout, or any other network error really, which would cause switch to the next track. This is by design.

**Comment by ptkovsky** [comment] 2019-11-11 21:29
Sorry if my poor description lead to a little bit of misunderstanding, just trying to remember and explain different use cases in all details. Also as you said, I tried tracing some timeouts, was testing on home Wi-Fi and the connection here seems quite reliable, but latency to the server is not that great though, about 180 ms, some packet loss happens here and there. But other players seems fine with this. Here is the result:
```
--- xstream2.somafm.com ping statistics ---
50 packets transmitted, 44 packets received, 12.0% packet loss
round-trip min/avg/max/stddev = 177.035/179.919/194.491/2.851 ms
```

**Comment by Alexey-Yakovenko** [comment] 2019-11-13 06:33
It will be best to report a new issue describing just that -- a specific radio, which interrupts after a few tracks.
