### ISSUE TITLE
Deadbeef doesn't write tag edits to file?

### ISSUE THREAD

**Issue by Gooberpatrol66** [DeaDBeeF-Player/deadbeef#3135] opened 2024-09-24 21:28 UTC
### Steps to reproduce the problem
Click flac file
Track properties
Edit field, like Artist Name
Enter
Apply
(tag is updated)
Right click, remove
File, add file
(change to tag is gone)

### What's going on? Describe the problem in as much detail as possible.
Deadbeef "saves" edits to file tags, but the saves are gone once the file is removed from playlist and readded

### Information about the software:

Deadbeef version:v1.9.6
OS:Guix

**Comment by Oleksiy-Yakovenko** [comment] 2024-10-31 17:00
I believe this problem was reported some years ago, but I could never reproduce it on my machine.
Can you see whether there are any errors logged in either log window or terminal?

**Comment by Oleksiy-Yakovenko** [comment] 2024-10-31 17:01
#3006 seems to be identical. Any chance that your flac file is split by cuesheet? In this case, deadbeef would not write tags back into the file. You can check by looking in track properties.

**Comment by Gooberpatrol66** [comment] 2024-11-08 22:29
There's a cuesheet in the folder but the tracks are separate files. "embedded cuesheet" says no.

**Comment by Oleksiy-Yakovenko** [comment] 2024-11-09 08:49
Can you try the same album and files without cuesheet present at all? Copy them to another folder, delete cuesheet, add to deadbeef, and try editing tags -- does it work then?

**Comment by Gooberpatrol66** [comment] 2024-11-14 22:56
Yes, when I delete the cue sheet, my tag edits show up.

**Comment by Oleksiy-Yakovenko** [comment] 2024-12-23 20:30
Closing as duplicate of #3306

**Closed by Oleksiy-Yakovenko** 2024-12-23 20:30 UTC
Labels: Bug, Duplicate
