### ISSUE TITLE
 Allow undo clear playlist

### ISSUE THREAD

**Issue by xgdgsc** [DeaDBeeF-Player/deadbeef#2019] opened 2018-05-25 13:57 UTC
### Steps to reproduce the problem
People sometimes click the menu items and click the edit->clear unintentionally (as clear is on top of the menu). It could take a lot of effort to construct one playlist, but just one false click using touchpad could clear that effort. An option to undo clear playlist would help in such a rare but critical use case.
 
### Information about the software:

Deadbeef version: 0.7.2
 
OS:manjaro

**Comment by Alexey-Yakovenko** [comment] 2018-05-28 10:14
Seems to be a subset of #490
Deadbeef doesn't have an undo system unfortunately.

**Comment by mrnom** [comment] 2018-11-25 10:51
Maybe it will be easier to implement confirmation messages e.g. for _Edit -> Clear_ and _Remove Playlist_ actions to make them less unintentional as a result, this may solve part of the problem.

**Comment by mrnom** [comment] 2018-11-25 11:02
Confirmation dialogs may partially solve the problem.

**Comment by Alexey-Yakovenko** [comment] 2019-10-21 05:28
duplicate of #490

**Closed by Alexey-Yakovenko** 2019-10-21 05:28 UTC
Labels: Enhancement
