### ISSUE TITLE
ffmpeg 5.0 support

### ISSUE THREAD

**Issue by MountainX** [DeaDBeeF-Player/deadbeef#2758] opened 2022-02-25 05:06 UTC
### Steps to reproduce the problem

sudo pacman -Syu
yay -S deadbeef

### What's going on? Describe the problem in as much detail as possible.

    ==> ERROR: A failure occurred in build(). 
    ffmpeg.c:956:33: error: no member named 'codec' in 'struct AVStream'
        ctx = fctx->streams[i]->codec;
           ~~~~~~~~~~~~~~~~  ^

### Information about the software:

Deadbeef version:
attempting to upgrade to deadbeef 1.8.8-3 using:
[AUR (en) - deadbeef](https://aur.archlinux.org/packages/deadbeef "AUR (en) - deadbeef")
As part of my troubleshooting I removed the prior installed version - it was not opening/running. I encounter this same bug whether upgrading or installing deadbeef 1.8.8-3

I also reproduced this on a second computer, which had never previously had deadbeef installed. Both run Arch Linux.

OS:
Arch Linux, fully updated.
ffmpeg Version: 2:5.0-4

Maybe this is related to the ffmpeg version? Does deadbeef 1.8.8-3 have dependencies that are not specified correctly in the AUR package, maybe?

**Comment by stefson** [comment] 2022-02-26 13:48
you need to post the whole config and build log files, including the Plugin Summary

**Comment by Alexey-Yakovenko** [comment] 2022-02-26 16:05
there's no need for logs, it's known that deadbeef has not been updated to support ffmpeg 5.0 yet.

**Comment by stefson** [comment] 2022-02-26 16:08
hmm ok, I asked since its not reproduceable for me. But if you already acknowledged there is indeed a problem, I'm fine with it (:

**Comment by Alexey-Yakovenko** [comment] 2022-02-26 16:12
@stefson are you sure that you are using ffmpeg 5.0?

**Comment by Alexey-Yakovenko** [comment] 2022-02-26 16:40
ok.. then it seems it can be some other problem unrelated to ffmpeg version.
sorry for the confusion -- I was kind of expecting that ffmpeg 5.0 had major API changes, just like it happened with all previous major updates.

**Comment by stefson** [comment] 2022-02-27 15:07
possibly, but maybe I got away due to my setup. 

I just wait for the config and build logs to see what went wrong.

**Comment by RiedleroD** [comment] 2022-03-01 21:06
on my machine it says:
```
loading plugin /usr/lib/deadbeef/ffmpeg.so
dlopen error: /usr/lib/deadbeef/ffmpeg.so: undefined symbol: av_register_all
trying /usr/lib/deadbeef/ffmpeg.fallback.so...
plugin ffmpeg.so not found or failed to load
```

I have arch linux with deadbeef-git from AUR. It does seem to build without issue, but can't load the ffmpeg plugin. The issue popped up around the time ffmpeg-5.0 released, but I can't say for sure since I only just now noticed, because some opus tracks are failing to play.

The build logs seem to build the ffmpeg plugin without problem:
```
checking for ffmpeg/avformat.h... no
config.status: creating plugins/ffmpeg/Makefile
    ffmpeg: yes - ffmpeg codecs
Making all in plugins/ffmpeg
make[2]: Entering directory '/data/makepkg/deadbeef-git/src/deadbeef/plugins/ffmpeg'
  CC       ffmpeg.lo
ffmpeg.c:115:14: warning: initializing 'AVCodec *' (aka 'struct AVCodec *') with an expression of type 'const AVCodec *' (aka 'const struct AVCodec *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ffmpeg.c:708:42: warning: format specifies type 'long long' but the argument has type 'int64_t' (aka 'long') [-Wformat]
ffmpeg.c:805:24: warning: implicit declaration of function 'av_iformat_next' is invalid in C99 [-Wimplicit-function-declaration]
ffmpeg.c:805:22: warning: incompatible integer to pointer conversion assigning to 'AVInputFormat *' (aka 'struct AVInputFormat *') from 'int' [-Wint-conversion]
ffmpeg.c:852:5: warning: implicit declaration of function 'av_register_all' is invalid in C99 [-Wimplicit-function-declaration]
  CCLD     ffmpeg.la
make[2]: Leaving directory '/data/makepkg/deadbeef-git/src/deadbeef/plugins/ffmpeg'
  CC       libwma/fft-ffmpeg.lo
  CC       libwma/ffmpeg_bitstream.lo
Making install in plugins/ffmpeg
make[1]: Entering directory '/data/makepkg/deadbeef-git/src/deadbeef/plugins/ffmpeg'
make[2]: Entering directory '/data/makepkg/deadbeef-git/src/deadbeef/plugins/ffmpeg'
 /bin/sh ../../libtool   --mode=install /usr/bin/install -c   ffmpeg.la '/data/makepkg/deadbeef-git/pkg/deadbeef-git/usr/lib/deadbeef'
libtool: install: /usr/bin/install -c .libs/ffmpeg.so /data/makepkg/deadbeef-git/pkg/deadbeef-git/usr/lib/deadbeef/ffmpeg.so
libtool: install: /usr/bin/install -c .libs/ffmpeg.lai /data/makepkg/deadbeef-git/pkg/deadbeef-git/usr/lib/deadbeef/ffmpeg.la
make[2]: Leaving directory '/data/makepkg/deadbeef-git/src/deadbeef/plugins/ffmpeg'
make[1]: Leaving directory '/data/makepkg/deadbeef-git/src/deadbeef/plugins/ffmpeg'
```
(grepped for ffmpeg)

**Comment by ToadKing** [comment] 2022-03-02 02:43
@RiedleroD deadbeef-git on AUR should be fixed. It now uses the ffmpeg4.4 package until this is fixed in deadbeef.

**Comment by stefson** [comment] 2022-03-06 15:34
So I can confirm the findings, the compile of ffmpeg-plugin against ffmpeg-5.0 is working but it won't load at runtime.

**Comment by Oleksiy-Yakovenko** [comment] 2022-10-02 08:11
Closed in https://github.com/DeaDBeeF-Player/deadbeef/pull/2861

**Comment by stefson** [comment] 2022-10-02 08:15
is it confirmed to work at runtime now?

**Comment by nieder** [comment] 2023-03-19 11:41
I've built 1.9.5 against ffmpeg-6.0 and the ffmpeg.so plugin loaded. However, I don't know how to test it because all the files that I have I think are being read by their 'native' plugin (mp3.so, flac.so, etc).

**Comment by Oleksiy-Yakovenko** [comment] 2023-03-19 11:56
@nieder to test it, you should play some files which are normally played via ffmpeg plugin in deadbeef -- such as DSF, TAK, 3GP, ARM, AC3.

**Comment by nieder** [comment] 2023-03-19 22:48
Thanks for the pointer. I was able to test a 3gp and a dsf file. Both sounded fine with 1.9.5 built against ffmpeg-6.0.

**Closed** 2023-03-20 08:50 UTC
Labels: Enhancement
