### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by dikonov** [DeaDBeeF-Player/deadbeef#2143] opened 2019-05-07 05:52 UTC
### Steps to reproduce the problem
Run deadbeef 1.8.0 and start listening to some files.

### What's going on? Describe the problem in as much detail as possible.
The player suddenly quits in the middle of a song. The same song can play well to the end and crash the next time. Happens more often with longer playlists. All previous versions were rock-stable. I don't know how to collect any debug data when deabeef crashes. There are no error messages or logs even in console. 

### Information about the software:
Deadbeef version: 1.8.0
OS: Linux (ALT)

**Comment by Bfgeshka** [comment] 2019-05-07 05:55
Information about how to get crash data: https://github.com/DeaDBeeF-Player/deadbeef/wiki/GDB-HOWTO

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 05:56
The instructions how to collect the debug data is provided in the [wiki](https://github.com/DeaDBeeF-Player/deadbeef/wiki/GDB-HOWTO). I can't help you at all without getting any information how to reproduce the crash.

**Comment by dikonov** [comment] 2019-05-07 06:21
This is a stripped build. GDB is clueless.
```
Reading symbols from deadbeef...
Missing separate debuginfo for /usr/bin/deadbeef
Try to install the hash file /usr/lib/debug/.build-id/4b/1564f0ade36d284e1b92cbb3ef180b461cf400.debug
(No debugging symbols found in deadbeef)

```
This time I got some console output.
```
$ deadbeef
starting deadbeef 1.8.0
server_start
searching for GUI plugins in /home/slava/.local/lib64/deadbeef
load_plugin_dir /home/slava/.local/lib64/deadbeef: scandir found 8 files
searching for GUI plugins in /home/slava/.local/lib/deadbeef
searching for GUI plugins in /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 49 files
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK3
selected GUI plugin not found or failed to load, trying to find another GUI plugin
the plugin not found or failed to load
the plugin not found or failed to load
loading plugin /usr/lib64/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/slava/.local/lib64/deadbeef
load_plugin_dir /home/slava/.local/lib64/deadbeef: scandir found 8 files
loading plugin /home/slava/.local/lib64/deadbeef/ddb_bs2b.so
loading plugin /home/slava/.local/lib64/deadbeef/ddb_infobar_gtk3.so
loading plugin /home/slava/.local/lib64/deadbeef/ddb_misc_filebrowser_GTK3.so
loading plugin /home/slava/.local/lib64/deadbeef/ddb_misc_quick_search_GTK3.so
loading plugin /home/slava/.local/lib64/deadbeef/ddb_misc_waveform_GTK3.so
loading plugin /home/slava/.local/lib64/deadbeef/stereo_widener.so
loading plugins from /home/slava/.local/lib/deadbeef
loading plugins from /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 49 files
loading plugin /usr/lib64/deadbeef/aac.so
loading plugin /usr/lib64/deadbeef/adplug.so
loading plugin /usr/lib64/deadbeef/alac.so
loading plugin /usr/lib64/deadbeef/alsa.so
loading plugin /usr/lib64/deadbeef/artwork.so
loading plugin /usr/lib64/deadbeef/cdda.so
loading plugin /usr/lib64/deadbeef/converter.so
loading plugin /usr/lib64/deadbeef/converter_gtk3.so
loading plugin /usr/lib64/deadbeef/dca.so
loading plugin /usr/lib64/deadbeef/ddb_dumb.so
loading plugin /usr/lib64/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib64/deadbeef/ddb_shn.so
loading plugin /usr/lib64/deadbeef/dsp_libsrc.so
loading plugin /usr/lib64/deadbeef/ffap.so
loading plugin /usr/lib64/deadbeef/ffmpeg.so
loading plugin /usr/lib64/deadbeef/flac.so
loading plugin /usr/lib64/deadbeef/gme.so
loading plugin /usr/lib64/deadbeef/hotkeys.so
loading plugin /usr/lib64/deadbeef/in_sc68.so
loading plugin /usr/lib64/deadbeef/lastfm.so
loading plugin /usr/lib64/deadbeef/m3u.so
loading plugin /usr/lib64/deadbeef/mms.so
loading plugin /usr/lib64/deadbeef/mp3.so
loading plugin /usr/lib64/deadbeef/musepack.so
loading plugin /usr/lib64/deadbeef/notify.so
loading plugin /usr/lib64/deadbeef/nullout.so
loading plugin /usr/lib64/deadbeef/oss.so
loading plugin /usr/lib64/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib64/deadbeef/psf.so
loading plugin /usr/lib64/deadbeef/pulse.so
loading plugin /usr/lib64/deadbeef/rg_scanner.so
loading plugin /usr/lib64/deadbeef/shellexec.so
loading plugin /usr/lib64/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib64/deadbeef/sid.so
loading plugin /usr/lib64/deadbeef/sndfile.so
loading plugin /usr/lib64/deadbeef/supereq.so
loading plugin /usr/lib64/deadbeef/tta.so
loading plugin /usr/lib64/deadbeef/vfs_curl.so
loading plugin /usr/lib64/deadbeef/vfs_zip.so
loading plugin /usr/lib64/deadbeef/vorbis.so
loading plugin /usr/lib64/deadbeef/vtx.so
loading plugin /usr/lib64/deadbeef/wavpack.so
loading plugin /usr/lib64/deadbeef/wildmidi.so
loading plugin /usr/lib64/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin Headphone crossfeed (bs2b)
starting plugin Infobar
starting plugin File Browser
starting plugin Quick search
starting plugin Waveform Seekbar
starting plugin Stereo widener
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK3 UI
starting plugin dts decoder
starting plugin DUMB module player
starting plugin Mono to stereo
starting plugin Shorten player
starting plugin Resampler (Secret Rabbit Code)
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Game-Music-Emu player
starting plugin Hotkey manager
starting plugin SC68 player (Atari ST SNDH YM2149)
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin OSD Notify
starting plugin Null output plugin
starting plugin OSS output plugin
starting plugin Playlist browser GTK3
starting plugin PSF player using Audio Overload SDK
starting plugin PulseAudio output plugin
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin Shellexec GTK3 UI
starting plugin SID player
starting plugin WAV/PCM player
starting plugin SuperEQ
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin VTX player
starting plugin WavPack decoder
starting plugin WildMidi player
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
streamer_set_output
selected output plugin: ALSA output plugin
INFO: from file /home/slava/.config/deadbeef/playlists/0.dbpl
plt_load: failed to open /home/slava/.config/deadbeef/playlists/0.dbpl
INFO: from file /home/slava/.config/deadbeef/playlists/1.dbpl
plt_load: failed to open /home/slava/.config/deadbeef/playlists/1.dbpl
INFO: from file /home/slava/.config/deadbeef/playlists/2.dbpl
INFO: from file /home/slava/.config/deadbeef/playlists/3.dbpl
INFO: from file /home/slava/.config/deadbeef/playlists/4.dbpl
INFO: from file /home/slava/.config/deadbeef/playlists/5.dbpl
INFO: from file /home/slava/.config/deadbeef/playlists/6.dbpl
fb api2
gtkui plugin compiled for gtk version: 3.24.7

(deadbeef:12318): Gtk-WARNING **: 09:12:39.836: Theme parsing error: gtk-contained.css:30:66: Using one color stop with linear-gradient() is deprecated.

(deadbeef:12318): Gtk-WARNING **: 09:12:39.836: Theme parsing error: gtk-contained.css:64:76: Using one color stop with linear-gradient() is deprecated.

(deadbeef:12318): Gtk-WARNING **: 09:12:39.836: Theme parsing error: gtk-contained.css:118:2: Expected semicolon

(deadbeef:12318): Gtk-WARNING **: 09:12:39.837: Theme parsing error: gtk-contained.css:195:22: 'none' is not a valid color name

(deadbeef:12318): Gtk-WARNING **: 09:12:39.837: Theme parsing error: gtk-contained.css:252:20: 'solid' is not a valid color name

(deadbeef:12318): Gtk-WARNING **: 09:12:39.838: Theme parsing error: gtk-contained.css:538:22: 'none' is not a valid color name

(deadbeef:12318): Gtk-WARNING **: 09:12:39.843: Theme parsing error: gtk-contained.css:1846:34: 'theme_bg_color' is not a valid color name

(deadbeef:12318): Gtk-WARNING **: 09:12:39.846: Theme parsing error: gtk-contained.css:2780:28: Junk at end of value for background-color

(deadbeef:12318): Gtk-WARNING **: 09:12:39.846: Theme parsing error: gtk-contained.css:2807:24: 'solid' is not a valid color name

(deadbeef:12318): Gtk-WARNING **: 09:12:39.851: Theme parsing error: gtk-contained.css:4126:2: Expected semicolon

(deadbeef:12318): Gtk-WARNING **: 09:12:39.851: Theme parsing error: gtk-contained.css:4326:2: Expected semicolon

(deadbeef:12318): Gtk-WARNING **: 09:12:39.852: Theme parsing error: gtk-contained.css:4392:2: Expected semicolon

(deadbeef:12318): Gtk-WARNING **: 09:12:39.853: Theme parsing error: gtk-contained.css:4808:2: Expected semicolon

(deadbeef:12318): Gtk-WARNING **: 09:12:39.853: Theme parsing error: gtk-contained.css:4869:22: Not using units is deprecated. Assuming 'px'.

(deadbeef:12318): Gtk-WARNING **: 09:13:07.094: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

(deadbeef:12318): Gtk-WARNING **: 09:13:07.094: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
Segmentation Fault
backtrace() returned 21 addresses
deadbeef() [0x404a63]
/lib64/libc.so.6(+0x37830) [0x7f7475525830]
/usr/lib64/libgtk-3.so.0(+0x2f38db) [0x7f7474e4c8db]
/usr/lib64/libgtk-3.so.0(+0x2f4c83) [0x7f7474e4dc83]
/usr/lib64/libgtk-3.so.0(gtk_text_layout_get_line_display+0xfd) [0x7f7474e562ad]
/usr/lib64/libgtk-3.so.0(+0x2fe6a2) [0x7f7474e576a2]
/usr/lib64/libgtk-3.so.0(+0x2dfaa5) [0x7f7474e38aa5]
/usr/lib64/libgtk-3.so.0(gtk_text_layout_validate_yrange+0x27e) [0x7f7474e5549e]
/usr/lib64/libgtk-3.so.0(+0x30d233) [0x7f7474e66233]
/usr/lib64/libgtk-3.so.0(+0x30dcb3) [0x7f7474e66cb3]
/usr/lib64/libgtk-3.so.0(+0x30e0d9) [0x7f7474e670d9]
/usr/lib64/libgdk-3.so.0(+0x2dc48) [0x7f7474a8cc48]
/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x138) [0x7f747418a6d8]
/lib64/libglib-2.0.so.0(+0x51a98) [0x7f747418aa98]
/lib64/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f747418ab1c]
/usr/lib64/libgio-2.0.so.0(g_application_run+0x1ed) [0x7f747438ccbd]
/usr/lib64/deadbeef/ddb_gui_GTK3.so(gtkui_thread+0xcf) [0x7f74752c5c2f]
/usr/lib64/deadbeef/ddb_gui_GTK3.so(+0x5fcd2) [0x7f74752c5cd2]
deadbeef() [0x404795]
/lib64/libc.so.6(__libc_start_main+0xeb) [0x7f747551208b]
deadbeef() [0x40497a]

```

**Comment by dikonov** [comment] 2019-05-07 07:03
Closing a bug does not fix it.
I need time to get any gdb output because I need a missing debuginfo package from my distro. (I do not want to rebuild deadbeef myself every week after regular automatic updates).

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 07:07
I'm closing the issues which don't contain information that was requested in the New Issue form.

**Comment by kuba160** [comment] 2019-05-07 07:08
could this issue be related to infobar plugin? (see #2112)

**Comment by Alexey-Yakovenko** [comment] 2019-05-07 07:09
Ok, now that you provided a log.. I can see it's a duplicate of #2112 
I think it's explained well enough, especially if you follow to the infobar issue tracker and read there what the issue is.

**Closed by Alexey-Yakovenko** 2019-05-07 07:09 UTC
